### ISSUE TITLE
not found @import GoogleMobileAds

### ISSUE THREAD

**Issue by Clowning** [sbugert/react-native-admob#100]
Hi ! Thank for your plugin but i have a problem after 'react-native run-ios'

node_modules/react-native-admob/ios/BannerView.h:7:9: fatal error: module 'GoogleMobileAds' not found
@import GoogleMobileAds;

Do you have an idea?

**Comment by Bobby-hewitt** [comment]
Did you find a solution to this? I'm having the same problem

**Comment by irfanayazfm** [comment]
Have the same issue. What was the solution?

**Comment by Bobby-hewitt** [comment]
For me it was just a matter of installing Firebase correctly.  Either use cocoapods or install manually.  https://firebase.google.com/docs/ios/setup#frameworks

**Comment by rahulje9** [comment]
the following comment fixed my issue
https://github.com/thecodrr/react-native-google-admob/issues/5
