### ISSUE TITLE
"Native Component does not exist" error

### ISSUE THREAD

**Issue by JustinDFuller** [sbugert/react-native-admob#102]
Hi,

I am attempting to add this to my project but I get errors when I follow the directions. 

# What I did:

First I do `npm i react-native-admob -S` then I run `react-native link` from the root of my project.

Then I ran `pod init` in the `ios` directory and have this in my `ios/podfile`:

```
target 'VerseOfTheDayIOS' do
  pod 'Firebase/Core'
  pod 'Firebase/AdMob'
end
```

After that I ran `pod install` which worked perfectly fine, no errors.

At this point I add this to my component:

```javascript
import React, { Component } from 'react';
import {
  View
} from 'react-native';
import {
  AdMobBanner,
} from 'react-native-admob'

export default class MyComponent extends Component {
  render() {
    return (
      <View>
        <AdMobBanner
            bannerSize="banner"
            adUnitID="MYID"
            testDeviceID="EMULATOR" />
      </View>
    );
  }
}

// ... removed rest for brevity
```

At this point I run `react-native run-ios` and the rest of the app works perfectly except the ads.

# Errors:

`Warning: Native component for "RNAdMob" does not exist`

And:

`Warning: Native component for "RNAdMobDFP" does not exist`

Does anyone have any ideas?

# Versions of things:

react-native-cli: 2.0.1
react-native: 0.42.0
npm: 4.1.2
node: 6.5.0
xcode: 8.2.1
osx: 10.12.3

**Comment by JustinDFuller** [comment]
Closed this issue because it was my fault. I missed a step.

**Comment by tomasfrancisco** [comment]
@JustinDFuller Would you mind to specify the step you missed? I'm getting the same error and I cannot find the solution

**Comment by JustinDFuller** [comment]
@tomasfrancisco I think it was 

> Add react-native-admob static library to your Xcode project like explained here. (Step 3 of this guide is not needed)

**Comment by tomasfrancisco** [comment]
Thank you @JustinDFuller !
