### ISSUE TITLE
failure after install the package

### ISSUE THREAD

**Issue by GalFriD** [sbugert/react-native-admob#103]
after i install it (run this commands:
npm i react-native-admob -S
react-native link
)

i tried to run it in android and getting this errors:
error: package com.babisoft.ReactNativeLocalization does not exist
error: package com.i18n.reactnativei18n does not exist
error: package com.sbugert.rnadmob does not exist
error: cannot find symbol  new ReactNativeLocalizationPackage(),
error: cannot find symbol  new ReactNativeI18n(),
error: cannot find symbol  new RNAdMobPackage()

how can i fix it? thanks

**Comment by dancherb** [comment]
how did you fix this?
