### ISSUE TITLE
Not working on 0.42 (iOS)

### ISSUE THREAD

**Issue by smakazmidd** [sbugert/react-native-admob#106]
No events are fired, The ad is not displayed. I have verified by setting breakpoints in XCode that ad is being requested and received but its not displayed in the app. Also checked that its working properly on version 0.36. The code is the same.

**Comment by yelkamel** [comment]
Same issue with me react-native 0.42, doesn't fired the AdMobBanner.

**Comment by smakazmidd** [comment]
@yelkamel try this

https://github.com/Sh3rawi/react-native-admob/commit/20829f13b46a986f5001bb5a49e3ccd1575d0cd5

**Comment by yelkamel** [comment]
When I do that the project didn't build because I got 7 issue on the RNAdMobManager lib.

**Comment by melihmucuk** [comment]
+1

**Comment by smakazmidd** [comment]
[react-native-admob.zip](https://github.com/sbugert/react-native-admob/files/836822/react-native-admob.zip)

try this, have added the required changes

**Comment by melihmucuk** [comment]
did you create pr for this ? @smakazmidd

**Comment by yelkamel** [comment]
Thank you so much for that :)

**Comment by alvaromb** [comment]
This should work with v1.2.1.
