### ISSUE TITLE
How to check if Rewarded Video isReady? Like with Interstitial. 

### ISSUE THREAD

**Issue by booboothefool** [sbugert/react-native-admob#107]
@alvaromb This seems more important with Rewarded Video so you can prompt the user:

"Watch this video to earn _____?"

So you can pre-load the Rewarded Video, but how do you check if it's ready? Interstitial has `isReady()`: https://github.com/sbugert/react-native-admob#methods

Obviously, you don't want to prompt the user if there is no Rewarded Video available. If you prompt the user every time before requesting and showing the video, and you don't get a Rewarded Video fill, then you just prompted them for no reason.

**Comment by alvaromb** [comment]
There's an `isReady` but I think it's not visible in the js https://github.com/sbugert/react-native-admob/blob/master/ios/RNAdMobRewarded.m#L64

Will try to add it today.

**Comment by alvaromb** [comment]
You could access to it through `NativeModules.RNAdMobRewarded.isReady()` though.

**Comment by booboothefool** [comment]
@alvaromb Thanks a ton. I was able to do exactly what I needed with:

```
NativeModules.RNAdMobRewarded.isReady(isReady => console.log(isReady))
```

Hopefully this will convert to revenue. 😈

**Comment by booboothefool** [comment]
@alvaromb Thanks a bunch for the tip! Works great!

```
export const promptRewarded = (condition) => {
  const adFree = store.getState().adFree;
  if (adFree) {
    return;
  }

  if (!config.admob.rewarded.show) {
    return;
  }

  if (!condition) {
    return;
  }

  NativeModules.RNAdMobRewarded.isReady((isReady) => {
    if (!isReady) {
      return;
    }

    const adLocked = store.getState().adLocked;

    SimpleStore.get('lastRewardedTime')
      .then((lastRewardedTime) => {
        log('lastRewardedTime:', lastRewardedTime);
        if (moment(lastRewardedTime).isValid()) {
          log('lastRewardedTime isValid');
          const now = moment();
          const then = moment(lastRewardedTime);
          const minutesSinceLastRewarded = moment.duration(now.diff(then)).asMinutes();
          log('lastRewardedTime minutes:', minutesSinceLastRewarded);
          if (minutesSinceLastRewarded < config.admob.rewarded.frequencyCapMinutes) {
            if (adLocked) {
              store.dispatch({
                type: 'SET_AD_LOCKED',
                value: false,
              });
            }
            return;
          }
        }

        if (!adLocked) {
          store.dispatch({
            type: 'SET_AD_LOCKED',
            value: true,
          });
        }
      });
  });
};
```

Hopefully this will convert to revenue. 😈

**Comment by nicolas-besnard** [comment]
Should be in the doc :)
