### ISSUE TITLE
Rewarded video example doesn't work on android's simulator

### ISSUE THREAD

**Issue by mcoeur** [sbugert/react-native-admob#109]
Hey,

I couldn't get rewarded videos to work with android on my project so I gave the examples a try.
No problem with ios, but I always get the same error with android when calling the requestAd method :

```
rewardedVideoDidFailToLoad Object {error: "ERROR_CODE_INTERNAL_ERROR"}
index.android.js:40 ERROR_CODE_INTERNAL_ERROR
```

I know my adUnitId is correct, or else it wouldn't be working on ios, I guess...

Any idea what could cause this problem ?

(Everything is running on the emulator)

**Comment by emrecanozkok** [comment]
yes there is a problem.i'm dont finish my app successfully.i hope any body can fix this.

**Comment by emrecanozkok** [comment]
im checked its working on live device on my galaxt tab 3

**Comment by mcoeur** [comment]
I'll try running the app on a real device (on wednesday, I need to get a proper transfer cable) and will keep you posted !

**Comment by alvaromb** [comment]
We've experienced this too. Rewarded ad only loaded on a real device.
