### ISSUE TITLE
Cannot evaluate module RNAdMob : Configuration with name 'default' not found.

### ISSUE THREAD

**Issue by hasen6** [sbugert/react-native-admob#11]
Trying to install on Android. As far as I can see I've followed all the steps but I'm getting this error trying to build the app. The app worked fine before I added this module.

EDIT: OK I fixed this error. You also need this step: $ npm i react-native-admob -S to be pard of the Android installation instructions. But now it still doesn't work because I think it needs the Google Admob Framework added? But I don't know how that is added for Android. Now I get the errors:

> Could not resolve all dependencies for configuration ':RNAdMob:_debugCompile'.
   > Could not find com.google.android.gms:play-services-ads:8.3.0.

**Comment by sbugert** [comment]
Have you installed the library manually or via rnpm?
If manually can you show me your `android/settings.gradle` and `android/build/app.gradle` files?
Which react-native version are you using?

Simon Bugert

**Comment by hasen6** [comment]
Wow you replied so quick. I actually already edited my original post.

**Comment by sbugert** [comment]
Ah, this seems to be an issue when installing it for the first time. Seems like my android sdk already downloaded the play services once and I did not see the error in the clean test project I tested it with.
I guess I have to include it in a gradle file somehow.

Meanwhile you can test if the soulution in this issue works for you:
https://github.com/sbugert/react-native-admob/issues/10

**Comment by hasen6** [comment]
Well I don't use Android studio. Is there any other way to fix it? I'm just using Atom with Genymotion on Mac.

**Comment by sbugert** [comment]
There is a section "Prerequisites for Android" in this project's readme: https://github.com/idehub/react-native-google-analytics-bridge/

That could be working! If it works I will add imatructions to the readme.

**Comment by hasen6** [comment]
I tried installing the Google Play Services in the Android SDK manager and rebuilt the project but it still can't find the google play services...it still basically reports the same error.

**Comment by hasen6** [comment]
There are a lot of other Google play libraries in the SDK manager that I'm not sure are required or not.

**Comment by sbugert** [comment]
I have installed these:
![screenshot 2016-04-19 12 14 40](https://cloud.githubusercontent.com/assets/2883939/14635819/5e0550c2-0628-11e6-8aad-1baab20795ed.png)

I'm not sure if all of the packages are needed for it to work but it works for me.

**Comment by hasen6** [comment]
Ok thanks. I installed those and am not getting errors about Google play anymore but the build still fails with error:

:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.

**Comment by sbugert** [comment]
Unfortunately, this is a very generic error.
Is there nothing else in the logs? Any file, code excerpt or something?

**Comment by sbugert** [comment]
Any news on this? Did you get it to work?

**Comment by hasen6** [comment]
Well no, I kind of gave up on it because I'm new to Android anyway and I checked your installation guide and seemed to have followed it, have also installed all the same plugins you have. Here is all my installation code and plugins. Maybe you can see something I missed.

![android packages](https://cloud.githubusercontent.com/assets/15882674/14805192/5f101848-0b9c-11e6-99de-dd6b390fa998.png)
![mainactivityjava](https://cloud.githubusercontent.com/assets/15882674/14805193/5f1039a4-0b9c-11e6-972f-e4549bc85126.png)
![buildgradle](https://cloud.githubusercontent.com/assets/15882674/14805195/5f1689bc-0b9c-11e6-8d80-11ba46120d41.png)
![settingsgradle](https://cloud.githubusercontent.com/assets/15882674/14805194/5f1593ea-0b9c-11e6-8316-098cf5b3f165.png)

**Comment by sbugert** [comment]
That looks right...
Which react-native version are you using?

Also, you could try to run the project in the Example directory of this project. If it works, then we know at least that the sdk is correctly installed.

**Comment by hasen6** [comment]
I'm trying it again with the latest version of RN 25.1 and used RNPM to install this time. However I noticed it currently doesn't work with 25.1 on iOS. The error is:

ReactNative.createElement is deprecated etc

Normally I can fix it but i can't quite see how to do it this time. I'm editing the index file in the module but not sure what to do about requiring the requireNativeComponent.  Any idea how to fix the minor error warning that comes up with 25.1? It works ok, I can see the ad showing but that error message still needs to be fixed.

**Comment by sbugert** [comment]
> it currently doesn't work with 25.1
>  It works ok, I can see the ad showing but that error message still needs to be fixed.

So does it work or not? I guess this is only a deprecation warning because the new way to use react in react-native is now to require react directly (before react-native exported react).
I'm not quite sure if I will fix this yet because it would result in breaking everyone else's codes if they are below 25.1.

**Comment by hasen6** [comment]
Yes I realise you can't fix the code since it would break it for older version of RN but can you provide here the changes that are required for the index.js? I've managed to fix the code for so many plugins by requiring react and react native in the new way, but yours is the only one that I can't seem to fix. The problem lies with 'requireNativeComponent'. I can't seem to require it correctly - any ideas?

Yes the code does work on iOS but the ad is hidden behind the yellow warning.

I fixed it temporarily by commenting out the line for interstitials ie `// const AdMobInterstitial = React.NativeModules['RNAdMobInterstitial'];` since the error is regarding `React.NativeModules` but obviously this would prevent me from using interstitials which I do plan on using.

**Comment by sbugert** [comment]
I'm quite sure that you have to change `const AdMobInterstitial = React.NativeModules['RNAdMobInterstitial'];`to `const AdMobInterstitial = ReactNative.NativeModules['RNAdMobInterstitial'];
`

It works on 0.22.0 and I will try 0.19.0 tonight which is the lowest version this library.
And if it does I will commit the changes tonight! Thanks for reporting this.

Btw, you can [disable the yellow warnings](https://facebook.github.io/react-native/docs/debugging.html#yellowbox-redbox), completely or even for specific warnings.

**Comment by hasen6** [comment]
No that doesn't work. The key is, how do you change the top imports ie this part:

`import React, {
  requireNativeComponent,
  View,
} from 'react-native';`

**Comment by sbugert** [comment]
You have to change it so it looks like this:
```
import React, { Component } from 'react';
import {
  requireNativeComponent,
  View,
  NativeModules,
} from 'react-native';
```

This fixed the warnings for me. The example project has two more warnings which are in the index.ios.js of the project.

**Comment by hasen6** [comment]
Yep that's fixed it! Great, thanks very much.
