### ISSUE TITLE
did not show anything

### ISSUE THREAD

**Issue by KurenaiKami** [sbugert/react-native-admob#115]
sometimes it can show real ads 
but sometimes it show noting

**Comment by Angelk90** [comment]
Were you able to solve?

**Comment by vinhtq** [comment]
+1 I have same issue. Sometimes it display ads, sometimes not.

Very weird and not stable

**Comment by jcarlosjl** [comment]
Hi,

I have a couple of ads in a listview but each of them takes many time to load their content (from 10 to 15 seconds) but finally the content is displayed. Somebody has the same problem?

**Comment by koenpunt** [comment]
You could try the 2.0.0 alpha version, because the way views are vended has changed there and might prevent your issue from happening: https://github.com/sbugert/react-native-admob/releases/tag/v2.0.0-alpha.4

**Comment by koenpunt** [comment]
Closing now, because of lack of activity. If you still encounter the same problem feel free to open a new issue.
