### ISSUE TITLE
ad sharing /  this component replaces my Admob id ??

### ISSUE THREAD

**Issue by ghost** [sbugert/react-native-admob#118]
Does component  have ad sharing?
Does Component always show Developers Ads?

**Comment by userTestGit** [comment]
@alvaromb   Does this component have ad sharing?

**Comment by userTestGit** [comment]
this component replaces  my Admob ID  for ad sharing? like others  plugin admob does ??  
Always use my  admob ID or  have any % for your Id ?
@alvaromb

**Comment by userTestGit** [comment]
LIKE  some bad developers does:
https://github.com/floatinghotpot/cordova-admob-pro/issues/544
https://github.com/floatinghotpot/cordova-admob-pro/issues/470
https://github.com/floatinghotpot/cordova-admob-pro/issues/450

how about your component?   @alvaromb

**Comment by alvaromb** [comment]
I don't know, I haven't developed that part. We use it with our own Admob codes. Ping @sbugert.

**Comment by userTestGit** [comment]
@sbugert  ?

**Comment by userTestGit** [comment]
@sbugert   ?

**Comment by koenpunt** [comment]
There's no ad sharing in this library, we only use Google's test ads in the example project.
