### ISSUE TITLE
Testing on iOS (Simulator & Device)

### ISSUE THREAD

**Issue by skizzo** [sbugert/react-native-admob#12]
Hi,
I'd like to show a banner on bottom of my main screen, but when I run it from XCode (on my actual device), XCode logs:
`<Google> To get test ads on this device, call: request.testDevices = @[ @"615c4841bc5e4ccd710f24b51e39b64b" ];`
How would I implement this? Thanks.

**Comment by sbugert** [comment]
Hi skizzo,
do you see a test ad despite seeing the logged message?

Unfortunately, there is not yet a test id prop for the banner component, so right now there is no way to set the device id. This should be an optional property.
I will probably add it soon but you should be seeing ads even without it.
If not something else is probably wrong.

**Comment by 29decibel** [comment]
Hi @sbugert Thanks for the awesome lib. 

Now I am getting the same issue with @skizzo , it works fine in Simulator(iOS), but the banner was not showing in real device (iPhone 6). I got the same error like ```<Google> To get test ads on this device, call: request.testDevices = @[ @"xxxxxxxxxxxxxxxxxx" ];```

When I looked into the source code, I found this:

https://github.com/sbugert/react-native-admob/blob/master/ios/BannerView.m#L73

```objective-c
  GADRequest *request = [GADRequest request];
    if(_testDeviceID) {
//      request.testDevices = @[_testDeviceID];
      request.testDevices = @[kGADSimulatorID];
    }
```

Does that mean it will always set testDevices to ```kGADSimulatorID```?

**Comment by 29decibel** [comment]
Please ignore the above comment, looks like the first one works. It just takes a while to load :-)

**Comment by sbugert** [comment]
Yes it will load but you are still right that it will always be *kGADSimulatorID*!
I will fix this, thanks for finding out :)
