### ISSUE TITLE
TypeError: expected dynamic type `double', but had type `string'

### ISSUE THREAD

**Issue by ilyago** [sbugert/react-native-admob#120]
Banner and Interstitial works fine but on Rewarded Ad i'm getting error.
Please advise .

import { AdMobRewarded } from 'react-native-admob'

showRewarded() {
    AdMobRewarded.setAdUnitID('ca-app-pub-3940256099942544/1033173712');
    AdMobRewarded.requestAd(AdMobRewarded.showAd);
}

console log shows  'rewardedVideoDidFailToLoad', { error: 'ERROR_CODE_INTERNAL_ERROR' }

Red Screen 

TypeError: expected dynamic type `double', but had type `string' (constructing arguments for RNAdMobRewarded.showAd at argument index 0)
invoke
    BaseJavaModule.java:339
invoke
    JavaModuleWrapper.java:136
run
    NativeRunnable.java:-2
handleCallback
    Handler.java:739
dispatchMessage
    Handler.java:95
dispatchMessage
    MessageQueueThreadHandler.java:31
loop
    Looper.java:148
run
    MessageQueueThreadImpl.java:196
run
    Thread.java:818

**Comment by ilyago** [comment]
Got it working on android device, but emulator still fails

**Comment by tanotify** [comment]
I got this working on emulator, but on android device it's not working. Did you solve it @ilyago?

**Comment by ilyago** [comment]
@tanotify works on device but not on emulator, so i'm testing on device

**Comment by hnliyuan** [comment]
I have the same problem~ Did you solve it ?

**Comment by jdobrowner** [comment]
I was having the same problem. It ended up being that I was using 'ca-app-pub-3940256099942544~1458002511' instead of 'ca-app-pub-3940256099942544/1033173712' as the sample ID in AdMobInterstitial.setAdUnitID('ID');

It was the ~

**Comment by PBBassily** [comment]
I had the same issue , i figured out that i was using the sample unit id of the banner with the interstitial 

![screenshot from 2017-08-14 19-34-03](https://user-images.githubusercontent.com/26141338/29283624-d2548076-8127-11e7-9ea4-21a945707ba5.png)

you can find the full docs here : https://developers.google.com/admob/android/test-ads

**Comment by koenpunt** [comment]
Apparently you're using the interstitial ad unit id for a rewarded video, so that might be it too? And since other people managed to get this is issue solved I'm going to close this.

And for the ones interested; I would love to get some feedback on the changes I introduced in the 2.0.0 alpha version, so if you could give that a try, that would be great! 

https://github.com/sbugert/react-native-admob/releases/tag/v2.0.0-alpha.4
