### ISSUE TITLE
AdMobRewarded.showAd never calls positive callback

### ISSUE THREAD

**Issue by eranbes** [sbugert/react-native-admob#124]
When calling `AdMobRewarded.showAd(cb)` in Android, `cb` is never called in positive case. 
Root cause may be the fact that in `android/src/main/java/com/sbugert/rnadmob/RNAdMobRewardedVideoAdModule.java`, the field `showAdCallback` is never used (only two occurrences: declaration and setting the value, no read of the value anywhere).

**Comment by koenpunt** [comment]
This is fixed in version 2. See the README on how to install this version, and check [the release notes](https://github.com/sbugert/react-native-admob/releases/tag/v2.0.0-beta.1) to see what changed.
