### ISSUE TITLE
DFP multiple size support

### ISSUE THREAD

**Issue by Johan-dutoit** [sbugert/react-native-admob#128]
As per the DFP spec

- Android: https://developers.google.com/mobile-ads-sdk/docs/dfp/android/banner#multiple_ad_sizes
- iOS: https://developers.google.com/mobile-ads-sdk/docs/dfp/ios/banner#multiple_ad_sizes

> Multiple ad sizes
> 
> DFP allows you to specify multiple ad sizes which may be eligible to serve into a PublisherAdView.

**Comment by koenpunt** [comment]
See #151 for a work in progress. Should be usable for both iOS and Android, although there might still be some inconsistencies between the two.

**Comment by koenpunt** [comment]
I would love to get some feedback on the changes I introduced in the 2.0.0 alpha version, so if you could give that a try, that would be great! 

https://github.com/sbugert/react-native-admob/releases/tag/v2.0.0-alpha.4

**Comment by Johan-dutoit** [comment]
Hi,

I'm happy to give the new version a go.
I do have a question though, does this use the DFP sdk?

I got an email the other day stating that we're using a deprecated version
of the sdk, but I haven't investigated where yet.

**Comment by koenpunt** [comment]
Hi @Johan-dutoit, the library uses the "Google Mobile Ads SDK", which is the official library that both serves DFP and AdMob. However, the version of the SDK being used is defined in your project (`Podfile` and/or `build.gradle`).

For reference; I use version 7.21 of the Google Mobile Ads SDK for my iOS project.

If you follow the installation instructions it should get you in the right direction: 
https://github.com/sbugert/react-native-admob/tree/next#installation

**Comment by koenpunt** [comment]
Version 2 is in beta and being tracking on the master branch. See the README on how to install this version, and check [the release notes](https://github.com/sbugert/react-native-admob/releases/tag/v2.0.0-beta.1) to see what changed.
