### ISSUE TITLE
smartBannerPortrait arrow showing in middle of the add every time

### ISSUE THREAD

**Issue by mmckinley8** [sbugert/react-native-admob#129]
Android is showing up fine but iOS is showing up like this every time.

<img width="380" alt="screen shot 2017-05-10 at 8 18 05 am" src="https://cloud.githubusercontent.com/assets/11301364/25900480/3ae73f54-3559-11e7-8319-4ce7eaa4f48a.png">

**Comment by koenpunt** [comment]
This is not related to this library, since it doesn't control the content. Might be a decision on Google's end to display it differently on Android than on iOS?
