### ISSUE TITLE
app crash when open admob interstitial more than 2 times

### ISSUE THREAD

**Issue by magicvn** [sbugert/react-native-admob#13]
HI Sbugert,

I tried to use your component with Admob interstitial. It's work fine for the first time but on the second the android app is crashed and the ios app crashes on the third. 

There are many apps using Admob interstitial many time as they want. 

Can you take a look about this bug?

Thanks in advances!

**Comment by sbugert** [comment]
Hi magicvn!

I just ran the example project but have not been able to crash it no matter how. Can you give me any information on how I can? I cannot debug it without reproducing the bug.

**Comment by magicvn** [comment]
Hi Sbugert,

Thanks for your response,

I fixed that, its seem the React Native Navigator conflict with banner Interstitial.

Best,

**Comment by yusufseyrek** [comment]
Hi @magicvn, how did you solved this problem? Could you please explain.

Thanks
