### ISSUE TITLE
What's prop name for AdMob App ID?

### ISSUE THREAD

**Issue by Tiendq** [sbugert/react-native-admob#131]
When I created a new AdMob app, I got an App ID and Ad unit ID for every ad unit. But I don't see where to assign App ID, for example, with `AdMobBanner` there is only `adUnitID` prop.

Thanks,

**Comment by Tiendq** [comment]
I know how to do it now :)

**Comment by Dictory** [comment]
@Tiendq and how?

**Comment by Kris4an7** [comment]
Can write how you did it ?

I tried what @Dictory said but I get errors in Android Studio. 

Can you maybe provide a sample of how the full code in MainActivity.java ?

Thank you !

**Comment by Dictory** [comment]
@Kris4an7 
```java
package ...
import ...
import com.google.android.gms.ads.MobileAds;

public class MainActivity extends AppCompatActivity {
    ...
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        // Sample AdMob app ID: ca-app-pub-3940256099942544~3347511713
        MobileAds.initialize(this, "YOUR_ADMOB_APP_ID");
    }
    ...
}
```
from [quick start](https://firebase.google.com/docs/admob/android/quick-start)

**Comment by booboothefool** [comment]
@Tiendq @Dictory Out of curiosity, what is the point of assigning the AdMob App ID if ads seem to work fine with just the adUnitId? Do I miss out on anything? I didn't know about AdMob App ID.

**Comment by Kris4an7** [comment]
@booboothefool Well, none from my experience.
I thought I need it, hence the question, but it turned out to work fine without it.

Thanks for the answer @Dictory !

**Comment by Tiendq** [comment]
@booboothefool it's for reporting, you could have several ad units in an app.

**Comment by MiLeung** [comment]
When I try @Dictory's method, my app "keeps stopping"
