### ISSUE TITLE
Module 'GoogleMobileAds' not found

### ISSUE THREAD

**Issue by laurion** [sbugert/react-native-admob#132]
Getting this error after installing and linking with `react-native link` and adding `pod 'Firebase/AdMob'` to the podfile and running `pod install`

**Comment by hangwoo** [comment]
solution https://stackoverflow.com/questions/29485189/module-googlemobileads-not-found-in-ios

**Comment by koenpunt** [comment]
Please follow the AdMob getting started guide to install the required frameworks

**Comment by dtiburciosf** [comment]
Continuo com o problema
