### ISSUE TITLE
AdMobBanner Android don't show empty field

### ISSUE THREAD

**Issue by Angelk90** [sbugert/react-native-admob#133]
For android.
I did the following:
1) npm and react-native-admob-S
2) react-native link
3) Included in my code:
       <AdMobBanner
       bannerSize = "mediumRectangle"
       AdUnitId = "ca-app-pub-mycode"
       testDeviceID = ""
       DidFailToReceiveAdWithError = {(err) => {console.log (err);}} />
But the banner space remains completely empty.
Does not work.
What type of ad unit should I submit?
Banner, Interstitial, Video Award with or Native?
And testDeviceID I leave it empty?

**Comment by adrianchancy** [comment]
+1

**Comment by adrianchancy** [comment]
If I input test ad like "ca-app-pub-3940256099942544/6300978111" (from https://developers.google.com/admob/android/test-ads) in AdUnitId, the test banner can show. 

However, if I input the one I created in Admob console, it does not show anything.
I also tried to input "testDeviceID" of my device and build onto my device to try. No ad is shown neither. :(

**Comment by adrianchancy** [comment]
I fixed it by chance. In android > app > build.gradle, I marked "play-services-ads" to use 11.0.1

```
    compile ('com.google.android.gms:play-services-ads:11.0.1'){
        force = true;
    }
```
And then I opened Android Studio, it says it does not have the Google repository for 'com.google.android.gms:play-services-ads:11.0.1' and I confirm to upgrade. After that, I build in device and genymotion, they both work.

Hope it may also help you

**Comment by Angelk90** [comment]
@adrianchancy: Do you know how to use code for test ads, native?

**Comment by koenpunt** [comment]
Since this is a pretty old issue and in the meantime a new version is about to be released (currently available as beta) I'm going to close it. If the problem still exists please open a new issue.
