### ISSUE TITLE
Empty vs. unassigned test device ID

### ISSUE THREAD

**Issue by Tiendq** [sbugert/react-native-admob#134]
As far as I know, `testDeviceID` is not required for production (released app), but it has inconsistent behaviors with falsy values.

1. Empty `testDeviceID`: both banner and interstitial work.

```
<AdMobBanner
      bannerSize="banner"
      adUnitID={adUnitId}
      testDeviceID={''}
      adViewDidReceiveAd={null}
      didFailToReceiveAdWithError={handleAdMobBannerError}
    />
```

```
AdMobInterstitial.setAdUnitID(adUnitId);
AdMobInterstitial.setTestDeviceID('');
AdMobInterstitial.requestAd(/*omitted*/);
```

2. Unassigned `testDeviceID`: banner not shown on 32-bit iDevices e.g. iPhone 5, iPad 2; interstitial not shown at all.

```
<AdMobBanner
      bannerSize="banner"
      adUnitID={adUnitId}
      adViewDidReceiveAd={null}
      didFailToReceiveAdWithError={handleAdMobBannerError}
    />
```

```
AdMobInterstitial.setAdUnitID(adUnitId);
AdMobInterstitial.requestAd(/*omitted*/);
```

**Comment by koenpunt** [comment]
v2 of the library has a `testDevices` property, which accepts an array of test device ids, so I think this issue is no longer relevant.
