### ISSUE TITLE
My execution remains blocked on Configuring > 3/4 projects react native project

### ISSUE THREAD

**Issue by Sofiane-13** [sbugert/react-native-admob#136]
Please I have a soutenance I have to solve the problem, My execution remains blocked on Configuring > 3/4 projects 
![capture du 2017-05-28 12-20-27](https://cloud.githubusercontent.com/assets/11254768/26528372/b07195b2-43aa-11e7-8a13-99bf628817f2.png)

![capture du 2017-05-28 14-43-38](https://cloud.githubusercontent.com/assets/11254768/26528405/bb31039c-43ab-11e7-8c4c-a2a31cacc7f3.png)

**Comment by koenpunt** [comment]
I'm going to close this since I don't think your problem is related to this library, because `react-native-admob` isn't a dependency.
