### ISSUE TITLE
Banner native full width

### ISSUE THREAD

**Issue by Angelk90** [sbugert/react-native-admob#139]
You can make use of a native banner, which length has the device screen size?

**Comment by koenpunt** [comment]
@Angelk90 it's unclear to me what you're asking. Can you elaborate?

**Comment by dandesz198** [comment]
I think they were asking for a banner size that has the same width as the device's screen. But that's what `smartBanner` does, isn't it?

**Comment by koenpunt** [comment]
I would say the same, but that's still an assumption. But since there hasn't been a reply for over a month I'm going to close this.

**Comment by Angelk90** [comment]
@koenpunt, @dandesz198: Correct, you say good.

**Comment by dandesz198** [comment]
The ‘smartBanner’ is created exactly for this purpose.
