### ISSUE TITLE
adding mediation network linker error

### ISSUE THREAD

**Issue by bsy** [sbugert/react-native-admob#14]
Has anyone successfully added support for mediation networks like ChartBoost or UnityAds?  

I'm running into a linker error after installing the SDK and adapter file for ChartBoost:
http://stackoverflow.com/questions/36923517/xcode-install-admob-with-chartboost-as-mediation-network-linker-error-library

**Comment by sbugert** [comment]
Any news on this?
Do you think this is related to react-native-admob?

**Comment by bsy** [comment]
@sbugert pretty sure it was related to some xcode configuration, but I actually ended up going with Fyber instead and also working on my own RN package to interface with their native SDK, thanks!
