### ISSUE TITLE
Conflict with google analytics package

### ISSUE THREAD

**Issue by TUNER88** [sbugert/react-native-admob#15]
It seems to conflict with [react-native-google-analytics-bridge](https://github.com/idehub/react-native-google-analytics-bridge) package.

[My compile output](https://github.com/idehub/react-native-google-analytics-bridge/issues/31#issue-154306448)

Any idea how to fix it?

**Comment by TUNER88** [comment]
Could be fixed by adding:
```java
compile("com.google.android.gms:play-services-analytics:8.3.0"){
    force = true
}
```

[Check this issue for more details](https://github.com/idehub/react-native-google-analytics-bridge/issues/26#issuecomment-210077133)

**Comment by cbrevik** [comment]
I recommend updating the `play-services` dependency to `8.+` instead.
