### ISSUE TITLE
Rewarded Video Did Fail To Load

### ISSUE THREAD

**Issue by 9geeks** [sbugert/react-native-admob#150]
I have just follow example but rewarded video seem not running

rewardedVideoDidFailToLoad
ERROR_CODE_INTERNAL_ERROR

**Comment by jsoutherner** [comment]
I have same problem, only works with interstitial pub id.
How did you solve the problem?

And also cant handle "rewardedVideoDidRewardUser" event.

**Comment by edencakir** [comment]
@9geeks what's your fix?

**Comment by 9geeks** [comment]
I think it is admob's problem. Sometime no ads available. Maybe it dependence your admob account, if it is new account, ads is not stable.
