### ISSUE TITLE
AdMobRewarded sample ad unit id always returns ERROR_CODE_NO_FILL

### ISSUE THREAD

**Issue by jsoutherner** [sbugert/react-native-admob#155]
Helllo

I have a problem with AdMobRewarded video

First of all, i'm using this example https://github.com/sbugert/react-native-admob/blob/master/Example/index.android.js
But I've changed UnitID from Interstitial to Rewarded Video (https://developers.google.com/admob/android/test-ads#sample_ad_units)
`AdMobRewarded.setAdUnitID('ca-app-pub-3940256099942544/5224354917');`

and commented TestDeviceID
`//AdMobRewarded.setTestDeviceID('EMULATOR');`

So now I expected to see some dummy video when click on the button

```
<TouchableHighlight>
<Text onPress={this.showRewarded} style={styles.button}>
<Show Rewarded Video and preload next
</Text>
</TouchableHighlight>
```
But nothing. In console I see permanent error
![image](https://user-images.githubusercontent.com/28982953/28201359-54f6d94c-6879-11e7-8054-3afdc87b8427.png)

So no video and no chances to testing rewardedVideoDidRewardUser event

I know that problem probably not in react-native-admob package and probably even not in react-native, I just want to ask how did anyone use it and first of all getiing rewardedVideoDidRewardUser event
And what _I am_ maybe doing wrong

P.S Also a question why is in an example for AdMobRewarded setted Interstitial test ID?

**Comment by hnliyuan** [comment]
the same to you ...

**Comment by edencakir** [comment]
any updates on this?

**Comment by koenpunt** [comment]
Not sure what could cause this here; I had no problem with displaying any of the ads in the example. But since I would love to get some feedback on the changes I introduced in the 2.0.0 alpha version, you could give that a try, and see if that works for you. 

https://github.com/sbugert/react-native-admob/releases/tag/v2.0.0-alpha.4
