### ISSUE TITLE
Test Banner Ad UnitID is working but Newly created UnitID from my account is not working ??

### ISSUE THREAD

**Issue by sunrawat** [sbugert/react-native-admob#156]
I am facing a weired situation where i have implemented a googleadmob in react native app.

```
<AdMobBanner
          bannerSize="fullBanner"
          adUnitID="ca-app-pub-3940256099942544/6300978111"
          testDeviceID="EMULATOR"
          didFailToReceiveAdWithError={this.bannerError} />
```
where ca-app-pub-3940256099942544/6300978111 is the test id provided by googleadmob

but when i created new Adunit ID and replaced test id with the newly created ad unit id i am unable to any ads Why ??
Note : i am working on dev environment i guess it won't affect but still ...

**Comment by koenpunt** [comment]
It often takes some time for ad units to come available, so I can imagine this problem resolved itself. If you still have an issue with this please let me know and I'm happy to reopen.
