### ISSUE TITLE
click event for banner

### ISSUE THREAD

**Issue by vu-dang** [sbugert/react-native-admob#157]
Please add support for detecting banner click events to prevent invalid click activity when the user already click on the ad.   It looks like Admob API supports this.

/// Tells the delegate that a user click will open another app (such as
/// the App Store), backgrounding the current app.
func adViewWillLeaveApplication(_ bannerView: GADBannerView) {
  print("adViewWillLeaveApplication")
}

**Comment by koenpunt** [comment]
> prevent invalid click activity

What do you mean with that?
