### ISSUE TITLE
iOS: Interstitial ads won't load when 'Limit Ad Tracking' setting turned on

### ISSUE THREAD

**Issue by d3zza** [sbugert/react-native-admob#160]
When 'Limit Ad Tracking' (under Settings > Privacy > Advertising) is turned on, interstitial ads will not load. 

interstitialDidFailToLoad event is fired with:

Error Domain=com.google.ads Code=1 "Request Error: No ad to show." UserInfo={NSLocalizedDescription=Request Error: No ad to show., NSLocalizedFailureReason=Request Error: No ad to show.}

**Comment by koenpunt** [comment]
This is not an issue with this library but with the Google Mobile Ads SDK. And from what I read this has to do with Google using the IDFA for limiting and such, so when that ID is not available, they have no way to associate the limit to a client, and could decide to not serve anything. This is however my interpretation, but in any case this is not an issue with this library so I'm going to close this now.
