### ISSUE TITLE
interstitial ad show this error how to solve it???

### ISSUE THREAD

**Issue by yogeshmoradiya121** [sbugert/react-native-admob#161]
![screenshot_2017-07-28-13-08-50-744_com loveromanticsms](https://user-images.githubusercontent.com/27858885/28707463-27314402-7396-11e7-925f-ef258cc30da5.png)

**Comment by jdobrowner** [comment]
Check out #120

**Comment by koenpunt** [comment]
Please provide the code you're using, otherwise it's just guessing.
