### ISSUE TITLE
Change size of banner

### ISSUE THREAD

**Issue by MariusGarbea** [sbugert/react-native-admob#163]
When rotating the device (onLayout is called) is it possible to change the size of a banner or at least center it?

**Comment by koenpunt** [comment]
There's a 2.0.0 alpha version available, which is more or less a rewrite. And I have been able to center banners in this version. And for DFP banners the `allowedAdSizes` property has been added, which might serves your need here.

I would love to get some feedback on the changes I introduced in this version, so if you could give that a try, that would be great! 

https://github.com/sbugert/react-native-admob/releases/tag/v2.0.0-alpha.4

**Comment by MariusGarbea** [comment]
Thank you for the update. Unfortunately, I decided to remove the landscape orientation option. If, however, future versions of my app will include this functionality, I will give you my input.

**Comment by koenpunt** [comment]
In that case I'm going to close. Feel free to open a new issue when the issue still exist in the future
