### ISSUE TITLE
RNAdmodBanner.js not working with RN 16.

### ISSUE THREAD

**Issue by thiensubs** [sbugert/react-native-admob#170]
Please see error bellow:

>Warning: PropTypes has been moved to a separate package. Accessing React.PropTypes is no longer supported and will be removed completely in React 16. Use the prop-types package on npm instead. (https://fb.me/migrating-from-react-proptypes)

Please fix it.

**Comment by koenpunt** [comment]
Have a look at the 2.0.0-alpha. I would love to get some feedback on the changes I introduced in that version, so if you could give that a try, that would be great! 

https://github.com/sbugert/react-native-admob/releases/tag/v2.0.0-alpha.4
