### ISSUE TITLE
rewardedVideoDidRewardUser callback

### ISSUE THREAD

**Issue by PeterLeeHyfn** [sbugert/react-native-admob#171]
Hello, 
I am able to load videos and leave the video ad. But i can not seem to get the callback user rewarded to fire. Is this code below the correct implementation? I looked in the code base and all seems correct but its just not firing. Any suggestions?

Thanks

AdMobRewarded.addEventListener('rewardedVideoDidRewardUser',
          (type, amount) => console.log('rewardedVideoDidRewardUser', type, amount)
   );

IOS: iphone 6s
"react-native-admob": {
      "version": "1.3.0",

**Comment by koenpunt** [comment]
The rewarded video callback is broken in the 1.x version. For a working implementation I suggest you check out the v2 version (currently in development) here: #165
