### ISSUE TITLE
Example on how to use AdMobInterstitials

### ISSUE THREAD

**Issue by Kliton** [sbugert/react-native-admob#173]
There is an example for AdMobInterstitials?

Thank you

**Comment by TarCode** [comment]
https://github.com/sbugert/react-native-admob/pull/176/files

**Comment by koenpunt** [comment]
The example @TarCode references to is correct for the current version (1.3):

```js
AdMobInterstitial.requestAd(error => {
  AdMobInterstitial.showAd((error) => { });
});
```

But in the 2.0 version it's going to be:

```js
AdMobInterstitial.requestAd()
  .then(() => AdMobInterstitial.showAd())
  .catch(error => console.warn(error));
```

You can check out the 2.0 version here: #165
