### ISSUE TITLE
That plugin run with Google Ad Exchange (AdX)?

### ISSUE THREAD

**Issue by 1fabiopereira** [sbugert/react-native-admob#174]
I've seen that this implementation (AdMob) is very similar with Google Ad Exchange (AdX), my ask is, this plugin work with Adx or i need change something?

**Comment by koenpunt** [comment]
From what I understand, AdX is just a network, so you should be able to use it with the `PublisherBanner`

**Comment by elgambet** [comment]
@1fabiopereira could you use it with "adx"?

**Comment by 1fabiopereira** [comment]
> @1fabiopereira could you use it with "adx"?

Yes, you just need use "Adx" as __*PublisherBanner*__
