### ISSUE TITLE
DFP for interstitials support ?

### ISSUE THREAD

**Issue by soapcreativegithub** [sbugert/react-native-admob#175]
We need to show interstitial ads, that use/are directed to DFP. Is that possible with the current release? I could only seem to find DFP for banner ads in the documentation here but wanted to double check.

**Comment by koenpunt** [comment]
I believe you can just use the `AdMobInterstitial` for DFP ad units, since the DFP specific classes extend from the admob classes., Although support for app events and custom rendered interstitials is currently lacking, since those require use of the admob classes.
