### ISSUE TITLE
RNAdMobInterstitial.requestAd was called with 1 arguments but expects 0 arguments.

### ISSUE THREAD

**Issue by gsdias** [sbugert/react-native-admob#179]
I have `AdMobInterstitial.requestAd(()=>AdMobInterstitial.showAd)` but I'm getting the following error: `RNAdMobInterstitial.requestAd was called with 1 arguments but expects 0 arguments. If you haven't changed this method yourself, this usually means that your versions of the native code and JavaScript code are out of sync. Updating both should make this error go away.`

"react-native": "^0.48.3",
"react-native-admob": "^2.0.0-alpha.5",

**Comment by koenpunt** [comment]
That's correct, the v2 uses a promise instead of a callback. So you should use it like this:

```js
AdMobInterstitial.requestAd()
  .then(() => AdMobInterstitial.showAd())
  .catch(error => console.warn(error))
```

This is also documented in the README (on the `next` branch): https://github.com/sbugert/react-native-admob/blob/9a426ca532812f174865cefbbede0508bbaf8e3e/README.md
