### ISSUE TITLE
Interstitials currently working?

### ISSUE THREAD

**Issue by hasen6** [sbugert/react-native-admob#18]
Its down as a todo list on npmjs.com so I wasn't sure. I tried it using the code from the example project and I'm getting an undefined is not an object error on iOS for `Interstitual.setAdUnitId`

Its ok with this:

`var Interstital = require('react-native-admob').AdMobInterstitial;`

It throws the error with this:

Interstital.setAdUnitId('ca-app-pub-9647718344871529/9452502879');

I tried reverting the index.js code back to its original (pre 25.1 format) but it still throws the same error.

**Comment by sbugert** [comment]
Interstitials are working for me.

Can you show me your code and the full error message?

**Comment by hasen6** [comment]
The code is this:

`
import { AdMobBanner, AdMobInterstitial } from 'react-native-admob';

var Interstital = require('react-native-admob').AdMobInterstitial;

Interstital.setAdUnitId('ca-app-pub-9647718344871529/9452502879');
`
Its important to note that the banner is already working on this page. I just add in the lower two lines and from above and

 it throws the error message:

![c](https://cloud.githubusercontent.com/assets/15882674/15352893/00fa277e-1d19-11e6-8c63-38c2ad7c07d8.png)

**Comment by sbugert** [comment]
Then there must be a mistake in your index.js of react-native-admob if you changed it.

This is working for me in the Example project:
``` javascript
'use strict';

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
} from 'react-native';
import { AdMobBanner as Banner, AdMobInterstitial as Interstital } from 'react-native-admob';

console.ignoredYellowBox = ['Warning: ReactNative.createElement is deprecated. Use React.createElement from the "react" package instead.'];

Interstital.setAdUnitId('ca-app-pub-3940256099942544/1033173712');

var Example = React.createClass({
  getInitialState: function() {
    return {
      size: 'banner',
    };
  },
  press(size) {
    this.setState({
      size: size,
    });
  },
  showInterstital() {
    Interstital.tryShowNewInterstitial(null);
  },
  render: function() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to react-native-admob!
        </Text>
        <Text onPress={this.showInterstital} style={styles.instructions}>
          Show Interstital
        </Text>
        <Text onPress={this.press.bind(this, 'banner')} style={styles.instructions}>
          Set banner size to 'banner'
        </Text>
        <Text onPress={this.press.bind(this, 'largeBanner')} style={styles.instructions}>
          Set banner size to 'largeBanner'
        </Text>
        <Text onPress={this.press.bind(this, 'mediumRectangle')} style={styles.instructions}>
          Set banner size to 'mediumRectangle'
        </Text>
        <Text onPress={this.press.bind(this, 'smartBannerPortrait')} style={styles.instructions}>
          Set banner size to 'smartBannerPortrait'
        </Text>
        <Text onPress={this.press.bind(this, 'smartBannerLandscape')} style={styles.instructions}>
          Set banner size to 'smartBannerLandscape'
        </Text>
        <Banner
          style={styles.banner}
          bannerSize={this.state.size}
          adUnitID={"ca-app-pub-3940256099942544/2934735716"} />
      </View>
    );
  }
});

var styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 15,
  },
  banner: {
    backgroundColor: '#055',
  },
});

AppRegistry.registerComponent('Example', () => Example);
```

**Comment by hasen6** [comment]
Tried the example code on got the same error. So I thought something must be up with the plugin so I reinstalled react-native-admob from scratch and now the example code works and so does my own.

But I still get the same warning that ReactNative.createElement is deprecated of course. If I try to edit the index.js file for the admob plugin replacing the code as you described in the other thread I then get the above error.....what's even more weird is even reverting the code back to how it was for index.js still throws that same error. Only a re-install will fix it?? Rebooting xcode and npm doesn't change anything either.

Any ideas? Very odd. At the moment I'm stuck with the deprecation warning.

**Comment by sbugert** [comment]
Well, then I would recommend inserting `console.ignoredYellowBox = ['Warning: ReactNative.createElement is deprecated. Use React.createElement from the "react" package instead.'];
` into your code to disable the deprecation warning until this library is updated to the new react-native api.

The fact that you can't get it to work again after reverting the changes is really weird. Did you restart the react-native packager?

**Comment by hasen6** [comment]
I restarted npm in terminal if that's what you mean?

**Comment by hasen6** [comment]
Anyway its all working now with your workaround and interstitials are showing fine.

**Comment by sbugert** [comment]
I made the false assumption that requiring react independently will break projects under 0.21.1.
I still works, the only breaking change would be to have react in the dependencies.

So, after the PR #19 merges the warning will disappear.
