### ISSUE TITLE
Android: "The ad size and ad unit ID must be set before loadAd is called"

### ISSUE THREAD

**Issue by gsdias** [sbugert/react-native-admob#180]
I get this error on Android when I use
`<AdMobBanner
      bannerSize="smartBannerPortrait"
      adUnitID={admob.banner}
      adViewDidReceiveAd={null}
      testDeviceID={__DEV__ ? 'EMULATOR' : ''}
      didFailToReceiveAdWithError={bannerError}
    />`

**Comment by kidmysoul** [comment]
has the same problem.I use 2.0.0 beta

**Comment by koenpunt** [comment]
@kidmysoul please show an example of how you're using this banner. If you check out the example project in the repo you'll see it works just fine there, so it should be something related to how the library is used.

**Comment by koenpunt** [comment]
Oh btw, the 2.0 has an `adSize` property instead of `bannerSize`

**Comment by kidmysoul** [comment]
@koenpunt 

can't get it work. My code is simple like:

```
import { AdMobBanner } from 'react-native-admob'

  render() {
    return (
      <View style={styles.container}>
        <MyNavigator />
        {Platform.OS === 'android' &&
        <AdMobBanner
            adUnitID="ca-app-pub-1213123123123123123"/> }
      </View>
    );
  }
```

and I use 2.0.0 beta
`    "react-native-admob": "^2.0.0-beta.2",`

**Comment by kidmysoul** [comment]
@koenpunt 

I finally got it work by add "adSize="banner"

**Comment by kidmysoul** [comment]
but in the 1.* version,if no adSize property provided,  the ad will automatically adjust it's widthe to the device width. How to do it in veresion 2? the "adSize="banner"" forces the width to 50 which looked not very well.
<img width="334" alt="2017-10-13 15 42 11" src="https://user-images.githubusercontent.com/15664045/31533429-2471fbac-b02d-11e7-9e1f-4e13e7707d41.png">

**Comment by koenpunt** [comment]
@kidmysoul please open a new issue if you have problems with positioning, because that's no longer related to this issue.

**Comment by koenpunt** [comment]
@gsdias that you close this is because your problem is now solved?

**Comment by gsdias** [comment]
The error is no longer there. At least using test id.

**Comment by koenpunt** [comment]
Good :)

**Comment by inceabdullah** [comment]
> 
> 
> @koenpunt
> 
> I finally got it work by add "adSize="banner"

it solved my problem. But not centered or it does not use device width.
