### ISSUE TITLE
in React 16, PropTypes will not be supported

### ISSUE THREAD

**Issue by kidmysoul** [sbugert/react-native-admob#184]
the error occured at `bannerSize: React.PropTypes.string,`

when you create a new react native app, the package.json will be like
`  "dependencies": {
    "react": "16.0.0-alpha.12",
    "react-native": "0.48.3",`
 .....................

so cannot use this library.

**Comment by kidmysoul** [comment]
OK, I solved it by `npm install react@16.0.0-alpha.12`

[the same issue](https://github.com/facebook/react-native/issues/14588)

**Comment by koenpunt** [comment]
For React 16 support I recommend using the 2.0.0-alpha version, currently being developed in #165
