### ISSUE TITLE
Move PropTypes to own prop-types package

### ISSUE THREAD

**Issue by deadcoder0904** [sbugert/react-native-admob#185]
[prop-types](https://npm.im/prop-types) must be used otherwise warning appears in development mode.

Source [here](https://github.com/sbugert/react-native-admob/blob/master/RNAdMobBanner.js#L47)

**Comment by deadcoder0904** [comment]
My bad #182 resolves this

**Comment by koenpunt** [comment]
@deadcoder0904 see #165 for the next version of this library.

I would love to get some feedback on the changes I introduced in that version, so if you could give that a try, that would be great! 

https://github.com/sbugert/react-native-admob/releases/tag/v2.0.0-alpha.4

**Comment by deadcoder0904** [comment]
@koenpunt Yep I will tonight.

Also checkout #186 & please merge #182

**Comment by deadcoder0904** [comment]
Sorry @koenpunt at the time I am a bit busy with tons of projects so it'll take me sometime to get around the alpha version. It might take a month. If u think its good enough to use then push it to `npm` under some different name & then when people start using it they will encounter a lot of issues. So apps in production will be able to give some good reviews. If u keep it in alpha for too long it will die. My advice u make it beta in some other repo. Or in this repo itself. I know its a lot of risk in this repo so try making it on different repo. U have been working on it since July so its high time just ship it. Opinions will come. But if u don't ship it, it won't happen. & maybe write some docs.

**Comment by koenpunt** [comment]
@deadcoder0904 I now released as beta on npm, and the master branch is tracking that version.
