### ISSUE TITLE
Ad Size and Ad unit id must be set before loadAd is called

### ISSUE THREAD

**Issue by priya-vr** [sbugert/react-native-admob#188]
I got this error on android

**Comment by koenpunt** [comment]
The error is very explanatory, so not sure what your problem is. How are you using the library?

**Comment by seonetartem** [comment]
@priya-vr it may help you https://github.com/sbugert/react-native-admob/issues/180#issuecomment-334711388

**Comment by priya-vr** [comment]
Thanks @seonetartem ,Issue is solved
