### ISSUE TITLE
Not compatible with React Native 0.49.x

### ISSUE THREAD

**Issue by thekiwi** [sbugert/react-native-admob#195]
React Native 0.49.1 has upgraded React to 16-beta which removes support for React.PropTypes. 

I'm currently getting the following error:
```
undefined is not an object (evaluating "_react3.default.PropTypes.string)"
```
at RNAdMobBanner.js:63:30

You'll need to include the 'prop-types' npm and use this instead, as done in this PR in another project: https://github.com/oblador/react-native-shimmer/pull/12/files

**Comment by itchingpixels** [comment]
+1 for this, unfortunately blocking us!

**Comment by koenpunt** [comment]
Use the `2.0.0-beta` for react 0.48+ support. Installable using `yarn add react-native-admob@next` or `npm install --save react-native-admob@next`

**Comment by thekiwi** [comment]
@koenpunt Thanks for the prompt reply, I'll try that tonight. 
Might also be worth putting that note at the top of the Readme on the 1.x branch?
