### ISSUE TITLE
Internal error, an invalid response was received from the ad server.

### ISSUE THREAD

**Issue by daiyunchao** [sbugert/react-native-admob#196]
I get this Error by adRequest load AD 
can change request host ?

**Comment by yogeshmoradiya121** [comment]
i have same error please help some one

**Comment by daiyunchao** [comment]
@yogeshmoradiya121 , in china?

**Comment by koenpunt** [comment]
This error message is based on the error code returned from the sdk, and thus is not caused by this library.

What do you mean with "can change request host ?"?

**Comment by daiyunchao** [comment]
@koenpunt  ok !
maybe my step has error 

i use android 
react-native version: 0.47
my step:
1.npm i react-native-admob
2.react-native link react-native-admob
3.use this in my app:
import {
  AdMobBanner,
  AdMobInterstitial,
  PublisherBanner,
  AdMobRewarded,
} from 'react-native-admob'

// Display a banner
<AdMobBanner
  adSize="fullBanner"
  adUnitID="my_id"
  testDevices={[AdMobBanner.simulatorId]}
  onAdFailedToLoad={error => console.error(error)}
/>
but request result :Internal error, an invalid response was received from the ad server

has some question ?
thx!

**Comment by yogeshmoradiya121** [comment]
@daiyunchao i'm from india
 i have integrated i one one app two day's ago in that app working perfect.
and today i have integrated in new app and shows that error.
testing ad shows but when i change to my admob id it show's that error

**Comment by daiyunchao** [comment]
@yogeshmoradiya121  use id: ca-app-pub-3940256099942544/2934735716 try again!
i use this id work ok but use my id has this error

**Comment by NayCho** [comment]
try to create another project, this works for me :100:

**Comment by sonthen** [comment]
hi, I also experienced the same issue, I saw @bhargav82 comment in almost every issue here hahaha.
can @sbugert confirm it if thats the case?

**Comment by koenpunt** [comment]
I've mentioned what @bhargav82 said before, and you would experience the same with using the google ads SDK natively. 
Still probably hard to confirm, since there probably will be cases where it happens under different circumstances. But I think it's safe to assume that in the majority of the cases it will be that.
