### ISSUE TITLE
Native module cannot be null - IOS

### ISSUE THREAD

**Issue by brkrtp** [sbugert/react-native-admob#197]
"react": "16.0.0-beta.5",
"react-native": **"0.49.3"**,
"react-native-admob": "^2.0.0-beta.2"
İPHONE SE IOS 11.0
Im import GoogleMobileAds.framework in Frameworks folder.
![simulator screen shot - iphone se - 2017-10-14 at 23 41 24](https://user-images.githubusercontent.com/18514716/31579548-51dbcde2-b141-11e7-80ef-4460122f4e49.png)

**Comment by koenpunt** [comment]
Which version of the library are you using? Also how did you implement it?

**Comment by brkrtp** [comment]
"react-native-admob": "^2.0.0-beta.2"
install manuel document, download admob sdk zip and extrack fremawork folder in xcode

**Comment by koenpunt** [comment]
Was this on a new project? Or an existing? Did you try cleaning the project?

**Comment by koenpunt** [comment]
Oh and you did add the framework to the linked frameworks? Accesible from bottom of the General section and on the build phases section.

**Comment by brkrtp** [comment]
Yes i will trying project. 
Also im trying downgrade my version to
"react": "16.0.0-alpha.12",
"react-native": "0.46.0",
"react-native-admob": "^1.3.2",
and automatic linking with react-native link
im getting this error:
![simulator screen shot - iphone 6 - 2017-10-15 at 12 30 53](https://user-images.githubusercontent.com/18514716/31583446-b318d5ec-b1a4-11e7-9715-2fbcbe5d88b0.png)

**Comment by brkrtp** [comment]
Any solution?

**Comment by ashrafonline** [comment]
Same here , The problem seems to be due to a conflict with the React version : "react": "16.0.0-beta.5" .

**Comment by koenpunt** [comment]
I have no problems using the library in a new newly created react-native (`0.49.3`) project. 

The `GoogleMobileAds.framework` should be in "Linked Frameworks and Libraries" too:

![image](https://user-images.githubusercontent.com/351038/31850751-464823ba-b658-11e7-87fc-ee370a1a6027.png)

**Comment by ashrafonline** [comment]
@koenpunt Thanks , your suggestion worked !

**Comment by koenpunt** [comment]
@brkrtp did you manage to solve your problem?

**Comment by garyrutland** [comment]
I'm facing the same issue, I'm not 100% sure what I'm doing with Xcode but I'm installing AdMob via Pods which claims it has linked the library for me.
I can't see the AdMob framework in the list of linked frameworks but I do see a Pod link thing.

**Comment by koenpunt** [comment]
> I can't see the AdMob framework

You mean you don't see the `GoogleMobileAds.framework`? 

If so, press the `+`, and add it to the list.

**Comment by garyrutland** [comment]
I tried that, but it wasn't in the list.

**Comment by koenpunt** [comment]
@garyrutland since your issue is related to CocoaPods I suggest you open a new issue, since the topic starter is no longer responding, and the issue has been resolved for others having the same problem (without CocoaPods)

**Comment by davidcort** [comment]
@koenpunt "The GoogleMobileAds.framework should be in "Linked Frameworks and Libraries" too:"

How i do that? I can´t see the option in Xcode  :(  Thanks
