### ISSUE TITLE
Could not find method compile() for arguments [project ':RNAdMob'] 

### ISSUE THREAD

**Issue by magicvn** [sbugert/react-native-admob#2]
Hi sbugert,

I have a issues when compile android:

Could not find method compile() for arguments [project ':RNAdMob'] on org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler_Decorated@5c748168

How can i fix them!

Tks

**Comment by sbugert** [comment]
Is it possible that you added `compile project(':RNAdMob')`to *android/build.gradle*? It has to be in *android/app/build.gradle*.

I hope that helps!
