### ISSUE TITLE
Work banner test in android device but not real banner

### ISSUE THREAD

**Issue by pmella16** [sbugert/react-native-admob#20]
hi i can't show real banner in android device, this work fine with banner test but not with real banner code, in ios emulator work fine too, i can't understand what is wrong
![screenshot_2016-05-19-12-11-02](https://cloud.githubusercontent.com/assets/19208317/15400871/952747ce-1dc3-11e6-8838-7d705bb15f2c.png)
![screenshot_2016-05-19-09-54-13](https://cloud.githubusercontent.com/assets/19208317/15400872/952d92b4-1dc3-11e6-9597-ad12ca0cf099.png)
![screenshot_2016-05-19-09-54-21](https://cloud.githubusercontent.com/assets/19208317/15400873/9533a1f4-1dc3-11e6-8e80-61a398e31509.png)
![screenshot_2016-05-19-09-53-57](https://cloud.githubusercontent.com/assets/19208317/15400874/95828b98-1dc3-11e6-8d9a-98d62cd39ecc.png)

**Comment by sbugert** [comment]
So it works with an admob test ID but does not work with your real id?

**Comment by pmella16** [comment]
yes, don't work with real id only in android

**Comment by pmella16** [comment]
I reinstalled all the project and now works fine, please close this, best regards
