### ISSUE TITLE
How to let the banner width fit to the screen width in android?

### ISSUE THREAD

**Issue by kidmysoul** [sbugert/react-native-admob#200]
this code 
```
        <AdMobBanner
            adSize="banner"
            adUnitID="ca-app-pub-*********"/>
```

lead to this:
<img width="341" alt="2017-10-20 13 19 05" src="https://user-images.githubusercontent.com/15664045/31805119-4adfcd8e-b599-11e7-95b7-3851677ad1fe.png">

in ios , "smartBannerPortrait" is OK to fit to screensize but how to do it in android?

**Comment by jslok** [comment]
Use smartBannerPortrait for android. Currently it is bugged so you will need to implement this fix until the package is updated. https://github.com/sbugert/react-native-admob/pull/194

**Comment by koenpunt** [comment]
A `"banner"` has a fixed size of 320x50, so the only thing you can do is center it horizontally, or use a different size like @jslok suggested.
