### ISSUE TITLE
package com.sbugert.rnadmob does not exist

### ISSUE THREAD

**Issue by egvrcn** [sbugert/react-native-admob#202]
Hi, i use reactnative 0.48.0 version and react-native-admob version 2.
I get the following error when I run it.

:app:compileDebugJavaWithJavac
C:\Users\ereng\RNA\Pratik\android\app\src\main\java\com\deerlabs\pratikuygulamalar\MainApplication.java:6: error: package com.sbugert.rnadmob does not exist
import com.sbugert.rnadmob.RNAdMobPackage;
                          ^
C:\Users\ereng\RNA\Pratik\android\app\src\main\java\com\deerlabs\pratikuygulamalar\MainApplication.java:31: error: cannot find symbol
            new RNAdMobPackage(),
                ^
  symbol: class RNAdMobPackage
2 errors
Incremental compilation of 1 classes completed in 0.527 secs.
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by Kuluum** [comment]
@egvrcn Try to check if you have `compile project(':react-native-admob')` in `dependencies `section of `android/app/build.gradle`. 
Also check 
`
include ':react-native-admob'
project(':react-native-admob').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-admob/android')
`
 in `android/app/settings.gradle`.
I have same problem and adding this works for me.
I gues it's some problems with linking (both react-native and rnpm) of this package.

**Comment by koenpunt** [comment]
Like @Kuluum described; you probably forgot to link the library into your project.
