### ISSUE TITLE
UNMET PEER DEPENDENCY react@16.0.0-alpha.12

### ISSUE THREAD

**Issue by egvrcn** [sbugert/react-native-admob#203]
npm i --save react-native-admob@next
I get the following error when I run it. Then i guess install nothing.

+-- UNMET PEER DEPENDENCY react@16.0.0-alpha.12

**Comment by koenpunt** [comment]
Which version of React and React native do you use?

**Comment by egvrcn** [comment]
react-native-cli: 2.0.1
react-native: 0.48.0

**Comment by koenpunt** [comment]
`react-native-admob` has no `peerDependency` on  react, so this is probably an issue with a different library.
