### ISSUE TITLE
1.3.2 fails on run with RN 0.49.0

### ISSUE THREAD

**Issue by ou2s** [sbugert/react-native-admob#205]
It is not working because of the use of `React.PropTypes` which is prohibited with react 16 & RN 0.49.0.

Refer to this for more information: https://reactjs.org/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes

I'm aware that 1.3.2 is no longer maintained so I will try to do a PR fix this problem.

PS: thanks for the library!

**Comment by koenpunt** [comment]
This a known issue, an you should use version 2 for anything higher than RN48
