### ISSUE TITLE
Request Error: Received invalid response. V2

### ISSUE THREAD

**Issue by serdarde** [sbugert/react-native-admob#207]
I receive this error when I turn off my internet in debug mode. There is no error if I connect phone to interner. 

**Versions:**
"react": "16.0.0",
"react-native": "0.50.0",
"react-native-admob": "^2.0.0-beta.2",

**Platform:** Android / IOS

**Current Code**

      componentDidCatch(error, info) {
        console.log(error, info); // never called
      }
    
      render () {
        return (<View style={styles.container}>
          <AdMobBanner
            adSize="banner"
            testDevices={testCode}
            adUnitID={banner}
            onAdFailedToLoad={error => console.error(error)} 
            />
        </View>)
      }

Error Details:
![simulator screen shot - iphone 6 - 2017-11-03 at 20 36 29](https://user-images.githubusercontent.com/6826944/32392831-6fbb3316-c0d7-11e7-8d06-c7988c082b6d.png)

More About error:
![screen shot 2017-11-03 at 20 55 26](https://user-images.githubusercontent.com/6826944/32393407-a062aa7e-c0d9-11e7-93ae-6efa6a999270.png)

**Comment by koenpunt** [comment]
This error is because you’ve set `onAdFailedToLoad` to a function that outputs the error with `console.error`. If you remove that, or replace it with something else you should be fine.
