### ISSUE TITLE
UIManager.RNGADBannerView is undefined

### ISSUE THREAD

**Issue by PhilTheAir** [sbugert/react-native-admob#208]
In the RNAdMobBanner.js, in the loadBanner(), the UIManager.RNGADBannerView is undefined.

Version of "react-native-admob": "^2.0.0-beta.2"

My react-native code is as below:
<AdMobBanner adSize="fullBanner" adUnitID="....."  onAdFailedToLoad={error => console.error(error)} />

I used create-react-native-app rather than react-native init to initialize my app.

Is anyone facing the same problem as I am ?

**Comment by TheeOMM** [comment]
Have the same problem over here

**Comment by yassineHub** [comment]
i faced the same issue .
this is my post : https://github.com/sbugert/react-native-admob/issues/212

**Comment by KamranKhankhail** [comment]
+1

**Comment by mustafakucuk** [comment]
react-native link react-native-admob after that restart app.

**Comment by koenpunt** [comment]
Since `create-react-native-app` uses Expo you will have to “eject” to make it work I’m afraid.

https://github.com/react-community/create-react-native-app/blob/master/EJECTING.md

**Comment by LeaveNhA** [comment]
The issue is continuing.

**Comment by macloving** [comment]
Now I have the same issue
