### ISSUE TITLE
Can't build due to "Argument list too long" error

### ISSUE THREAD

**Issue by giladno** [sbugert/react-native-admob#209]
When trying to run my app using `react-native run-ios`, I receive the following error:

```
=== BUILD TARGET RNAdMobManager OF PROJECT RNAdMobManager WITH CONFIGURATION Debug ===


Check dependencies

Argument list too long: recursive header expansion failed at /Users/gilad/MyProject/node_modules/react-native-admob/ios/../../../ios/Pods/React/node_modules/fsevents/node_modules/ajv/dist.



** BUILD FAILED **
```

I have the following in my `package.json`:
```
    "react-native-admob": "^2.0.0-beta.2",
```

And inside my `Podfile`:
```
  pod 'Google-Mobile-Ads-SDK'
```

I've tried to clean my `build` folder, as well as XCode's `DerivedData` - but it doesn't help...

**Comment by patw0929** [comment]
Same here.

```
Argument list too long: recursive header expansion failed at /Users/patw/Projects/news/node_modules/react-native-admob/ios/../../../ios/Pods/Target Support Files/Pods-news.
```

**Comment by cinder92** [comment]
same issue here 

```
Argument list too long: recursive header expansion failed at /Users/dantecervantes/Documents/react-native/FinanceApp/node_modules/react-native-admob/ios/../../../ios/Pods/React/node_modules/react-tools/src/isomorphic.
```

**Comment by NabilZaki** [comment]
Same error here :
`Argument list too long: recursive header expansion failed at /Users/username/Documents/work/repos/Mobile/node_modules/react-native-admob/ios/../../../ios/Pods/React/node_modules/react-tools/src/renderers/dom/client/__tests__.`

any solution ?

**Comment by muhammetdemirci** [comment]
same issue

**Comment by Young-Je** [comment]
the same issue, I even uninstalled the Xcode, but the issue still hangs there.

**Comment by Furqankhanzada** [comment]
Same issue 

`Argument list too long: recursive header expansion failed at /Users/USERNAME/Documents/work/repos/APPNAME/node_modules/react-native-admob/ios/../../../ios/Pods/React/node_modules/react-tools/src/renderers/dom/client/__tests__.`
