### ISSUE TITLE
Can't add AdMobBanner [Element type is invalid]

### ISSUE THREAD

**Issue by ehhuang** [sbugert/react-native-admob#21]
Trying to add AdMobBanner, but got the following error: 

`Unhandled JS Exception: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of X.`

Here's my code, it works without the AdMobBanner.
```
import AdMobBanner from 'react-native-admob';
...
render() {
    return (
      <View style={styles.container}>
        <NavigatorIOS
          style={styles.container}
          barTintColor='#004860'
          ... />
          <AdMobBanner
            bannerSize='banner'
            adUnitID='xxx' />
      </View>
    );
```

**Comment by sbugert** [comment]
`Check the render method of X.`
Is there an 'X' in the error?

Your code looks right.

**Comment by ehhuang** [comment]
What do you mean? 'X' is my component.

**Comment by sbugert** [comment]
Ah, I found the mistakte!
You're importing the whole (default) module but the AdMobBanner component is a named export.

So instead of `import AdMobBanner from 'react-native-admob';` you should `import { AdMobBanner } from 'react-native-admob';`.

**Comment by ehhuang** [comment]
It worked! Thanks, didn't realize that made a difference.

**Comment by sbugert** [comment]
Great!
[This](http://www.2ality.com/2014/09/es6-modules-final.html) is a very good article about the topic if you want to read up on it.
