### ISSUE TITLE
Android: Production admob id

### ISSUE THREAD

**Issue by gsdias** [sbugert/react-native-admob#211]
Hello, anyone got to work using v2.0.0-beta.2 in production. Even using production id for admob, it shows the test ad. It works in iOS but in Android it renders all the time test one.

**Comment by koenpunt** [comment]
I use the library in production for both iOS and Android without issues. Can you maybe show the code you're using?

**Comment by gsdias** [comment]
`import React from 'react'
import { Platform } from 'react-native'
import { View } from 'native-base'
import { AdMobBanner } from 'react-native-admob'
import FirebaseCrash from 'react-native-firebase-crash-report'
import { admob, tracker } from '../../lib/vars'

const bannerError = (error) => {
  FirebaseCrash.log(error)
  tracker.trackEvent('exception', error)
}

export default props => (!props.purchased && <View
  style={{ position: 'absolute', left: 0, right: 0, bottom: 0 }}
>
  <View style={{ flex: 1, flexDirection: 'column', alignItems: 'center' }}>
    <AdMobBanner
      adSize="banner"
      adUnitID={__DEV__ ? admob.test : admob.banner}
      adViewDidReceiveAd={null}
      testDeviceID={__DEV__ ? 'EMULATOR' : ''}
      didFailToReceiveAdWithError={bannerError}
    />
  </View>
</View>)
`
and vars exports 

`export const admob = {
  banner: Platform.select({
    ios: 'ca-app-pub-xxx',
    android: 'ca-app-pub-xxx',
  }),
  test: 'ca-app-pub-3940256099942544/6300978111',
  }`

**Comment by koenpunt** [comment]
There's no point in setting `adUnitId` when configure a test device.
Also you're mixing props of v1 with v2.

I think if you use the following you should be good:

```jsx
    <AdMobBanner
      adSize="banner"
      adUnitID={admob.banner}
      testDevices={[AdMobBanner.simulatorId]}
      onAdFailedToLoad={bannerError}
    />
```

NB. I've updated the formatting of your comment.

**Comment by gsdias** [comment]
Is it possible to test on simulator with release apk to check admob real ads or it will always show the test ads? With xcode simulator I can test and see real ads.

**Comment by koenpunt** [comment]
Just remove the `testDevices` prop, and real ads should show.
But keep in mind that Google actually forbids this, and can possibly cancel your account if you do this too often.

**Comment by gsdias** [comment]
I just want to test once to see if it real works. Tks for the advise
