### ISSUE TITLE
AdMobBanner is not displayed

### ISSUE THREAD

**Issue by yassineHub** [sbugert/react-native-admob#212]
I have tried to add admob to my project  .
my project is running correctely without error but no banner is dispayed .
my code is : 
`    <ScrollView>	
			  <AdMobBanner
  bannerSize="banner"
  adUnitID="ca-app-pub-3207834634154483/6974060636"
  testDeviceID="EMULATOR"
  didFailToReceiveAdWithError={this.bannerError} 
  adViewDidReceiveAd ={null}
adViewDidDismissScreen={null}
adViewWillLeaveApplication={null}/>
      </ScrollView>`

Can someone tell me what are probable reason  why my banner is not dispayed .

Thanks

**Comment by Mimble-Wimble** [comment]
Have you tried changing "bannerSize" to "adSize" and "didFailToRecieveAdWithError" to "onAdFailedToLoad"?

**Comment by TheeOMM** [comment]
@Mimble-Wimble the change worked for me. Thanks

**Comment by yassineHub** [comment]
i was in 1.x branch version . i use now the version 2.
my code now is : 
`<AdMobBanner
  adSize="fullBanner"
  adUnitID="ca-app-pub-3207834634154483/6974060636"
   testDevices={"EMULATOR"}
  onAdFailedToLoad={error => console.error(error)}
/>`

But i have this error 
![capture](https://user-images.githubusercontent.com/17007962/32680563-8e82f40c-c66b-11e7-9770-28dc947ba741.PNG)

could you help me to fix this problem .
what should set as a value in testDevices to let my code determine dynamicly the device ID .

**Comment by koenpunt** [comment]
For v2 you should use `testDevices={[AdMobBanner.simulatorId]}` instead of the `EMULATOR` string.

**Comment by yassineHub** [comment]
i tried with `testDevices={[AdMobBanner.simulatorId]}` , but it  generate another error 


![capture](https://user-images.githubusercontent.com/17007962/32748921-058ba392-c8be-11e7-989e-9c83ffe9bb47.PNG)

**Comment by shubhangi-asgola** [comment]
@yassineHub any update on above issue? Are you able to use version 2 without any issues on android?

**Comment by yassineHub** [comment]
I'm still stuck with the above issue .
Any one have the same problem ?

**Comment by svallen** [comment]
I am getting the same UIManager.RNGADBannerView issue.  testing with iOS.

"react": "16.0.0-beta.5",
    "react-native": "https://github.com/expo/react-native/archive/sdk-22.0.2.tar.gz",
    "react-native-admob": "^2.0.0-beta.3",

Followed the directions that were given.  

Any insight would be great.

**Comment by KamranKhankhail** [comment]
+1

**Comment by KamranKhankhail** [comment]
@sbugert can you please help us fix this issue?

**Comment by yassineHub** [comment]
@KamranKhankhail  i have no update about issue :(
i think i will return to the version 1.0

**Comment by koenpunt** [comment]
@yassineHub could it be that you updated the NPM package, but did not rebuild the project? Because I can't reproduce this with the example application..

**Comment by koenpunt** [comment]
Or are you by any change running an Expo project? Which I believe have no direct support for packages that need native modules.

**Comment by svallen** [comment]
Yes, running expo. Bummer that this won't work properly with it. Was looking forward to getting my google ads loading on my app.  Any suggestions or will there be compatibility coming down the line?

**Comment by koenpunt** [comment]
> Any suggestions or will there be compatibility coming down the line?

Well I think since the library depends on the `Google-Mobile-Ads-SDK`, this will never work out of the box.

The only probable option is to ["eject"](https://github.com/react-community/create-react-native-app/blob/master/EJECTING.md), and then follow the installation steps in the [README](https://github.com/sbugert/react-native-admob/blob/master/README.md).

**Comment by koenpunt** [comment]
But if you have any more questions regarding use with Expo, please open a new issue. (Unless @yassineHub is also using Expo?)

**Comment by koenpunt** [comment]
Just realized that `create-react-native-app` uses Expo by default. So my guess is that’s the case here too. If not let me know and I’m happy to reopen.

**Comment by akiradeveloper** [comment]
Please reopen this issue. It's not fixed yet.

I've confirmed the banner appear in Android emu + phy but the error shows when I `react-native run-ios`

![2018-03-04 16 55 34](https://user-images.githubusercontent.com/785824/36943455-195631ce-1fcd-11e8-84d8-3163996a653b.png)

**Comment by akiradeveloper** [comment]
I also insert interstitial ad in my app and it also fails. They are ok in Android though.

![2018-03-04 17 00 59](https://user-images.githubusercontent.com/785824/36943486-a5622038-1fcd-11e8-9cf2-3763801426b4.png)
