### ISSUE TITLE
DFP ADS on iOS

### ISSUE THREAD

**Issue by risto1913** [sbugert/react-native-admob#215]
I have been trying to get the DFP ads to work on iOS with 
```
<PublisherBanner
  adSize="mediumRectangle"
  testDevices={[PublisherBanner.simulatorId]}
  adUnitID="***DFP ADUNIT ID***"
   onAdFailedToLoad={error => console.log(error, 'mediumRectangle')}
    onAppEvent={event => console.log(event.name, event.info)}
  />
```

It works out of the box for android. But on iOS I have never seen any ads. I have installed the pod with cocoa pods.  But it always renders without an ad.

The strange thing  I am experiencing is that if I make use of
 ```
<AdMobBanner
  adSize="mediumRectangle"
  adUnitID="***DFP ADUNIT ID***"
  testDevices={[AdMobBanner.simulatorId]}
  onAdFailedToLoad={error => console.error(error)}
/>
```

This shows the ad, clicks and views ar registered. 
All is done with a typical DFP adunitid not an AdMob adunitid.

What am I missing? How can it not work with PublisherBanner? And how can it work with AdMobBanner using a DFP adunitit?

The cocoapod pod is obviously working.

xcode 9.1
Google-Mobile-Ads-SDK (7.25.0)
react-native 0.49.5
react-native-admob 2.0.0-beta.2

should I, or can I use this in production ?

**Comment by koenpunt** [comment]
That’s strange, I’m using both the `PublisherBanner` and `AdMobBanner` in production without any problems. Could you try to add `validAdSizes={[‘mediumRectangle’]}` and see if it works then?

**Comment by risto1913** [comment]
Sadly Same thing. 

this is the error I'm getting:
`Error: Request Error: No ad to show.
    at createErrorFromErrorData (utils.js:6)
    at PublisherBanner.handleAdFailedToLoad (RNPublisherBanner.js:53)
    at PublisherBanner.proxiedMethod (createPrototypeProxy.js:44)
    at Object._invokeGuardedCallback (ReactNativeFiber-dev.js:75)
    at Object.invokeGuardedCallback (ReactNativeFiber-dev.js:49)
    at Object.invokeGuardedCallbackAndCatchFirstError (ReactNativeFiber-dev.js:52)
    at executeDispatch (ReactNativeFiber-dev.js:127)
    at Object.executeDispatchesInOrder (ReactNativeFiber-dev.js:132)
    at executeDispatchesAndRelease (ReactNativeFiber-dev.js:3316)
    at executeDispatchesAndReleaseTopLevel (ReactNativeFiber-dev.js:3320) "PublisherBanner -> mediumRectangle"`

again, this works nicely on android.

**Comment by risto1913** [comment]
Looks like it has been a styling issue. flexing made the ad collapse on iOS.

**Comment by koenpunt** [comment]
> flexing made the ad collapse on iOS.

My next question would've been about how you positioned the banner.
But good to hear you figured it out!

**Comment by redwind** [comment]
any body still face this problem ?
It show for test adUnitID PublisherBanner but show error for my real adUnitID. I move banner to root layout without flex style but still face this problem. This is my code:
`<View>
                <PublisherBanner
                    style={{ height: 50, width: 320, backgroundColor: 'green' }}
                    adSize="banner"
                    validAdSizes={['banner', 'smartBannerPortrait', 'largeBanner', 'mediumRectangle']}                   
                    adUnitID='/6499/example/banner' 
                    testDevices={[PublisherBanner.simulatorId]}
                    didFailToReceiveAdWithError={(e) => console.log('Banner:onAdFailedToLoad', e)}
                    onAdLoaded={() => console.log('Banner:onAdLoaded')}
                    onAdFailedToLoad={(e) => console.log('Banner:onAdFailedToLoad', e)}
                    onAdOpened={() => console.log('Banner:onAdOpened')}
                    onAdClosed={() => console.log('Banner:onAdClosed')}
                    onAdLeftApplication={() => console.log('Banner:onAdLeftApplication')}
                    onAppEvent={(event) => console.log('Banner:onAppEvent', event)}
                />
            </View>`

I use RN 0.46.4 and latest react-native-admob version

Thanks !!!

**Comment by fernando-pascoal** [comment]
some problem, not work with real Id
