### ISSUE TITLE
undefined is not an object

### ISSUE THREAD

**Issue by TornHub** [sbugert/react-native-admob#222]
I did everything right, but when I import the library I get an error. What should I do?
![cropped_11898035025a1c8c5e1d4ff7 92168016](https://user-images.githubusercontent.com/25257157/33290971-7334d298-d3d5-11e7-8ab0-d790e2245eff.png)

**Comment by TornHub** [comment]
Problem solved.

**Comment by hindsricardo** [comment]
@TornHub  what was the solution?

**Comment by TornHub** [comment]
@hindsricardo I forgot to write the command. "react-native link"

**Comment by shruti8597** [comment]
Getting the error even after linking

**Comment by shruti8597** [comment]
Solved the error with version 2

**Comment by amulyaAmmu** [comment]
Getting the same error.. what is the solution

**Comment by shinriyo** [comment]
version2?

**Comment by shinriyo** [comment]
`yarn add react-native-admob@2.0.0-beta.5`
