### ISSUE TITLE
Facebook Audience Network Mediation

### ISSUE THREAD

**Issue by jslok** [sbugert/react-native-admob#223]
Has anybody gotten facebook audience network mediation to work for android? I am trying with banner ads but no luck. In admob, it's showing requests are being made (see pic) but no impressions are shown. In my facebook developer account, it shows status as "Not started - please send an ad request". I am testing using a real device and I am signed into Facebook on the device with my FB app's admin account.

I tried with audience network sdk 4.26.1 and 4.22.1 with corresponding mediation adapters.

![fb audience](https://user-images.githubusercontent.com/22921326/33372155-dbcbc942-d4b1-11e7-8726-5e8c195366db.png)

RN 0.49.3
RN-admob 2.0.0-beta3
FB audience network sdk 4.26.1
Admob FB mediation adapter 4.26.1.0
FB SDK 4.22.1

**Comment by jslok** [comment]
I got it working. Needed to increase the ecpm for Facebook mediation so admob would actually send a request to FB for my test device.

**Comment by IbrahimYounas** [comment]
> I got it working. Needed to increase the ecpm for Facebook mediation so admob would actually send a request to FB for my test device.

<img width="625" alt="Image" src="https://user-images.githubusercontent.com/49093392/55274963-c35faf00-52ef-11e9-9aa8-2e9cf527fca3.PNG">


Hello
I am having similar issue as attached, can u guide me how to fix this issue?
<img width="625" alt="Image" src="https://user-images.githubusercontent.com/49093392/55275008-821bcf00-52f0-11e9-9568-da70d2acebf2.PNG">

**Comment by IbrahimYounas** [comment]
Hi,

<img width="507" alt="image1" src="https://user-images.githubusercontent.com/49093392/55275138-c314e300-52f2-11e9-8730-01fa23caacb4.PNG">
Please check the attached image, would you spare few minutes to guide us on this mediation issue.

**Comment by IbrahimYounas** [comment]
Anyone who can help? Please guide how to fix the issue of mediation
