### ISSUE TITLE
Native module cannot be null - CocoaPods

### ISSUE THREAD

**Issue by garyrutland** [sbugert/react-native-admob#224]
Hi,

I've been trying to install this package using CocoaPods but getting the error "Native module cannot be null".
After running `pod install` I can see the AdMob framework listed in Xcode on the left menu, however, I can't seem to see a way of adding it to the linked frameworks.

Any idea why this is happening?

Thanks,
Gary

**Comment by garyrutland** [comment]
To clarify, even though I cannot see the `GoogleMobileAds` framework in the available to add to the list of linked frameworks, I do have `libPods-ProjectName.a` (project name is obviously not what I see, but my actual project name) in the list of linked frameworks.
I assume this just includes all installed pods?

**Comment by garyrutland** [comment]
Any assistance with this would be greatly appreciated.

**Comment by koenpunt** [comment]
Please provide some more information; this could be anything. For example; did you open the `xcodeproj` instead of the `xcworkspace`? Can you show the contents of your `Podfile`?

**Comment by garyrutland** [comment]
I did open `xcworkspace` instead of `xcodeproj`.  
I don't have the `Podfile` to hand right now (but will confirm within the next couple of hours), however, it is just the default `Podfile` created after running `pod init` and removing the extra block that causes errors.

I've followed the instructions on this page: https://developers.google.com/admob/ios/quick-start
Added `pod 'Google-Mobile-Ads-SDK'` to the relevant block and then run `pod install --repo-update`.

I can see the framework listed inside the workspace on the left menu.

However, when running my app in the emulator via `react-native run-ios` I get that error.

**Comment by garyrutland** [comment]
```
platform :ios, '9.0'

target 'ProjectName' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ProjectName
  pod 'Google-Mobile-Ads-SDK'

  target 'ProjectNameTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ProjectName-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ProjectName-tvOS

  target 'ProjectName-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

**Comment by garyrutland** [comment]
@koenpunt Do you need any more information?

**Comment by jonnyn** [comment]
I got this same issue yesterday and managed to resolve it.
I think you're missing the linking step after installing the module. 
https://facebook.github.io/react-native/docs/linking-libraries-ios.html#content

Try to unlink & remove the module, then install & link it again.
You may have to restart the whole session.

**Comment by garyrutland** [comment]
Awesome, that seems to have done the trick.
Thanks for the help.

**Comment by koenpunt** [comment]
@jonnyn thanks for helping out!
