### ISSUE TITLE
App Crashes while importing the library when No internet

### ISSUE THREAD

**Issue by shruti8597** [sbugert/react-native-admob#228]
I am checking for the internet and then displaying add in a component but it is unable to import the library while there is no internet 

Error: The adRequest was unceessful due to network connectivity

	import React, { Component } from 'react';

	import {
	    NetInfo,
	} from 'react-native';

	import {
	  AdMobBanner,
	} from 'react-native-admob'

	export default class AdMob extends Component { 

		constructor(props) {

		    super(props);
		    this.state = {
		      internet: false,
		    };
		    
		}

		componentWillMount() 
		{
		    NetInfo.isConnected.fetch().then(isConnected => {
		      this.setState({internet:isConnected})
		    });
		    NetInfo.isConnected.addEventListener('connectionChange',this.handleFirstConnectivityChange);
		}

		handleFirstConnectivityChange(isConnected) {
		  this.setState({internet:isConnected})
		}

		componentWillUnmount() 
		{
		  NetInfo.isConnected.removeEventListener(
		    'connectionChange',
		    this.handleFirstConnectivityChange
		  );

		}

		render() 
		{
			if(this.state.internet===true)
			    return (
			    
			     <AdMobBanner
			       adSize="fullBanner"
			       adUnitID="ca-app-pub-3940256099942544/6300978111"
			       onAdFailedToLoad={error => console.error(error)}/>
			   
			    );
			else
				return null;
		}

	}

**Comment by itchingpixels** [comment]
I'm not sure if this is related, but we're seeing this relatively frequent crash: http://crashes.to/s/83fd4bcf5e6

**Comment by shruti8597** [comment]
No it's not releated..
My issue is in the import statement when there is no internet.
It generates a error in Android

**Comment by koenpunt** [comment]
Well the “crash” you mention is probably the `console.error` in the `onAdFailedToLoad`.
That the error message says that there’s no internet connectivity has actually nothing to do with this library.

**Comment by shruti8597** [comment]
@koenpunt  Thank you so much!! I missed it.
