### ISSUE TITLE
Crash: Fatal Exception: java.lang.RuntimeException Illegal callback invocation from native module. This callback type only permits a single invocation from native code.

### ISSUE THREAD

**Issue by itchingpixels** [sbugert/react-native-admob#229]
http://crashes.to/s/83fd4bcf5e6

We're seeing this relatively frequent crash with beta-3.
Is there anything we could do about it?
I'm not sure if we could resolve this on the JS side.

**Comment by koenpunt** [comment]
It’s the promise for load that is rejected twice, but should be easy to fix.

Problematic part: https://github.com/sbugert/react-native-admob/blob/master/android/src/main/java/com/sbugert/rnadmob/RNAdMobInterstitialAdModule.java#L84

**Comment by itchingpixels** [comment]
@koenpunt : do you have any instructions how we could fix this? I'm not a native Android developer, but we have someone on the team who could get on this and submit a PR soon.
