### ISSUE TITLE
Warning: Native component for "RNAdMob" does not exist

### ISSUE THREAD

**Issue by sajjad26** [sbugert/react-native-admob#23]
I am getting this error or my android device and no banner is showing up just a small red dot appears. Every things seems to work in the emulator though.

**Comment by sbugert** [comment]
That's strange, but I cannot reproduce it without more information.

Any chance you forgot to recompile the app before starting it on the devide? Semms like the native component is missing (maybe because it was not there when compiling).

**Comment by sajjad26** [comment]
On my real device I am getting this error while displaying an Interstitial
```
AdMobInterstitial.tryShowNewInterstitial(null);
```
```
Cannot read property 'tryShowNewInterstitial' of undefined
```
However both kind of ads are working on the release apk and also on the emulator

**Comment by sajjad26** [comment]
Hi, after reinstalling the app on the phone the ads started working.

**Comment by jonigl** [comment]
Hi!

I have the same issue, I tried a lot of times to getting work but I have this warning again and again:
`ExceptionsManager.js:76Warning: Native component for "RNAdMob" does not exist` and my banner doesn't appear.

@sajjad26 How did you solve this?

Any help would be appreciate.

Thanks!

**Comment by sajjad26** [comment]
@jonigl If you installed the module using rnpm then i think you need to reinstall it manually, uninstall the app from the device and reinstall. That should work.

**Comment by jonigl** [comment]
I started a fresh new project and followed `rnpm` installation steps and it works perfect :)

**Comment by jatazoulja** [comment]
I am using expo,
can this be solve with out detaching? manual installation means I will need to detach my expo right?

**Comment by omarshiha** [comment]
i am using expo too, any solution ??
