### ISSUE TITLE
"RNGADBannerView does not exist" error

### ISSUE THREAD

**Issue by rafWork** [sbugert/react-native-admob#230]
Hello,

I've tried to use react-native-admob 2 beta but I'm getting this error.
![screen shot 2017-12-19 at 00 53 00](https://user-images.githubusercontent.com/33734655/34130010-5e47eefa-e457-11e7-91bb-858757914d9e.png)

I don't know what to do, could anyone please help me?

Before anyone asks;  I had started with create-react-native-app command but before then using admob I ejected my app.

My dependencies are below.
"dependencies": {
    "axios": "^0.17.1",
    "expo": "^23.0.4",
    "react": "16.0.0",
    "react-native": "0.50.3",
    "react-native-admob": "^2.0.0-beta.4",
    "react-native-loading-spinner-overlay": "^0.5.2",
    "react-native-render-html": "^3.5.2",
    "react-navigation": "^1.0.0-beta.21",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-promise": "^0.5.3",
    "redux-saga": "0.16.0",
    "redux-thunk": "^2.2.0"
  }

**Comment by koenpunt** [comment]
Looks like you forgot to “link” the project. Please check the [installation section in the README](https://github.com/sbugert/react-native-admob/blob/master/README.md#installation)

**Comment by rafWork** [comment]
Maybe I've screwed up somehow but Xcode and terminal say that it is linked.

![screen shot 2017-12-19 at 01 21 17](https://user-images.githubusercontent.com/33734655/34131005-00168e78-e45b-11e7-9d14-5e961bdf9125.png)


![screen shot 2017-12-19 at 01 16 08](https://user-images.githubusercontent.com/33734655/34130816-4d5a0c24-e45a-11e7-9415-fed0f284db5f.png)
![screen shot 2017-12-19 at 01 16 34](https://user-images.githubusercontent.com/33734655/34130823-55c4a90a-e45a-11e7-8398-5f6031cb55f4.png)

**Comment by koenpunt** [comment]
The icon of the library should not look like that actually..

Can you try to follow the manual linking steps and see if that solves it?

**Comment by koenpunt** [comment]
Glad you figured it out. Going to close this now.

**Comment by koenpunt** [comment]
Btw, you do not need to add the `xcodeproj` file to the linked libs

**Comment by rafWork** [comment]
Thank you! Last quick question, do I need to do anything with my Admob app Id like we should do on swift/xcode?

**Comment by koenpunt** [comment]
It works without, but I believe Google recommends it. To add it you should use the documented way; so just adding it to the `AppDelegate` for iOS, and using the respective way on Android too.

**Comment by Verma-Pooja** [comment]
I also face the same issue. I share a link, this issue mention here with the solution. It might be helpful to you.
Pls refer this link:
https://react-native-solutions.blogspot.com/2018/07/how-to-create-react-native-app-with.html

**Comment by shinriyo** [comment]
me too...
