### ISSUE TITLE
Multiple dex files define Lcom/google/android/gms/internal/zzoo;

### ISSUE THREAD

**Issue by ariona** [sbugert/react-native-admob#233]
I got this error

```
Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzoo;
```

I have tried some suggestion on another issue to change gms version but got no luck making it work, it raise another error, like:
```
Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexIndexOverflowException: Cannot merge new index 68775 into a non-jumbo instruction!
```

react-native: 0.50.3
react-native-admob: ^2.0.0-beta.4,

**Comment by koenpunt** [comment]
Try cleaning the project, from the top of my head;

    ./android/gradlew -w ./android clean

**Comment by ariona** [comment]
@koenpunt `Unknown command-line option '-w'` same with `./android clean` (`./android: command not found`)

**Comment by koenpunt** [comment]
Should have been:

    ./android/gradlew clean -p ./android

**Comment by ariona** [comment]
Still not working. The only package using play-service is `react-native-track-player`. 

```java
// Google Cast (Update this when RN updates the support library to 25+)
    compile 'com.google.android.gms:play-services-cast-framework:9.4.0'
```

**Comment by ariona** [comment]
Got this working by adding this lines on `build.gradle`:
```
dexOptions {
    jumboMode = true
}
```

But the ads won't show, it returned this message on my logcat, this probable not related to this library but any idea why this happen?
```
Ads     : Starting ad request.
Ads     : Use AdRequest.Builder.addTestDevice("9DADAF2D4885D45ACB77099ED1C6B1E2") to get test ads on this device.
Ads     : Received error HTTP response code: 400
Ads     : There was a problem getting an ad response. ErrorCode: 0
Ads     : Failed to load ad: 0
ReactNativeJS: Internal error, an invalid response was received from the ad server.
```

**Comment by ariona** [comment]
Ah, it's seem it won't work on debug mode. Got this working by using [Sample Ads Unit from Google](https://developers.google.com/admob/android/test-ads)
