### ISSUE TITLE
No ad to show

### ISSUE THREAD

**Issue by rafWork** [sbugert/react-native-admob#234]
Hello, it's me again...

I keep getting "no ad to show" error on iOS simulator. Actually it doesn't happen all the time but when I refresh the simulator, error shows up sometimes and it takes 10-20 refreshes to disappear. It happens with both admob test id and my own ad unit id. Android emulator just works fine btw. I am about to publish my app end of this week so is there any chance to solve that? Or is it just problem with simulator?

![screen shot 2017-12-21 at 14 10 41](https://user-images.githubusercontent.com/33734655/34253570-3db6bdac-e659-11e7-8be1-5bc394271919.png)

**Comment by koenpunt** [comment]
It can always happen that there’s no ad to show. But the error is actually caused by the `console.error` in the `onAdFailedToLoad` prop. If you remove that you should be safe.

**Comment by Maxwell2022** [comment]
How can this happen with the admob test id? isn't supposed to serve a video for the purpose of the test?

**Comment by motogod** [comment]
I have the same issue with @rafWork , as @koenpunt advise i remove `onAdFailedToLoad` but my admob screen still doesn't show admob. Should i ignore it or try to fix it ?

**Comment by Maxwell2022** [comment]
@motogod when did you setup your AdMob account? it takes up to 24h to activate sometime, you'll receive an email when activated. Also I think you need to setup AdSense:

https://www.google.com/adsense

Also I found that the test_ids are only working in the simulators, if you test your app on a physical device it's not working

**Comment by motogod** [comment]
@Maxwell2022 Thanks for your information, i just created the Admob id several hours ago for IOS project. I know what happen now, thank you.

**Comment by fspider** [comment]
I am also getting this error.
Is there anyone who has solution?
![Screen Shot 2020-06-01 at 10 25 22 PM](https://user-images.githubusercontent.com/53686427/83483189-625ada80-a4a2-11ea-870d-9d69573332ea.png)

**Comment by Ildar7sins** [comment]
> I am also getting this error.
> Is there anyone who has solution?
> ![Screen Shot 2020-06-01 at 10 25 22 PM](https://user-images.githubusercontent.com/53686427/83483189-625ada80-a4a2-11ea-870d-9d69573332ea.png)

The same error on iOS, any solution???

**Comment by Mrjavaci** [comment]
SoMe PrObLem

**Comment by Manisha-Bacancy** [comment]
I have followed all the steps and set up everything but no matter what ad is not showing on the physical iOS device.I m getting ad in iOS simulator and everything working fine on the android physical device too.
In iOS side getting error [Error: Request Error: No ad to show.]
Is there anyone who has solution?
