### ISSUE TITLE
Invariant Violation: Native component for "RNGADBannerView" does not exist

### ISSUE THREAD

**Issue by vineeth059** [sbugert/react-native-admob#235]
Followed the following steps:

1. create-react-native-app <app-name>
2. cd <app-name>
3. yarn add react-native-admob@next
4. copied the same code as provided in Example folder.
5. Getting following error:
Invariant Violation: Native component for "RNGADBannerView" does not exist

Tried the same process with 
1. react-native init <appname>
2. cd <appname>
3. npm install react-native-admob@next --save
4. copied the same code as provided in Example folder.
5. Getting following error:
Invariant Violation: Native component for "RNGADBannerView" does not exist

**Comment by rafWork** [comment]
I had the same problem. It probably because there is a mistake on linking. My closed issue is below.
https://github.com/sbugert/react-native-admob/issues/230

**Comment by vineeth059** [comment]
verified it. after "react-native link" it worked.

**Comment by Verma-Pooja** [comment]
I also face the same issue. I share a link, this issue mention here with the solution. It might be helpful to you.
Pls refer this link:
https://react-native-solutions.blogspot.com/2018/07/how-to-create-react-native-app-with.html

**Comment by cyb3rsalih** [comment]
I solved my problem with re-install the component ` npm install react-native-admob@next --save ` and ` react-native link` and re-compile the project.

**Comment by shinriyo** [comment]
finally did you use the project by `npm run eject`?
