### ISSUE TITLE
Doesn't work with Android 5.0 lollipop

### ISSUE THREAD

**Issue by basilwood** [sbugert/react-native-admob#238]
Added permission <uses-permission android:name="android.permission.FLASHLIGHT" />
in Androidmanifest.xml still, the flashlight doesn't turn ON on lollipop.

**Comment by koenpunt** [comment]
I don’t think I understand; flashlight? Why would an ad require that?

**Comment by basilwood** [comment]
Hey i'm sorry. Posted a wrong question here by mistake.
