### ISSUE TITLE
Google Mobile Ads SDK

### ISSUE THREAD

**Issue by zmerchant17** [sbugert/react-native-admob#239]
How would I add add the Google Mobile Ads SDK to my React Native without CocoaPods? There isn't much support on importing the SDK here:
https://developers.google.com/admob/ios/quick-start#import_the_mobile_ads_sdk

Has anyone done this without the use of CocoaPods?

**Comment by koenpunt** [comment]
The link you shared tells me the following;

> **Manual download**
>
> You can also download a copy of the SDK framework directly, unzip the file, and import the framework into your project in Xcode

**Comment by koenpunt** [comment]
Also the example project in the repo is not using cocoapods, so that might be of help too

**Comment by zmerchant17** [comment]
Yes, I understand I have to import the framework in Xcode, but I don't understand where in the file structure. I couldn't find it in the example project either. 
Thanks for the help.

**Comment by koenpunt** [comment]
It doesn't actually matter where, but often you'll see projects having `Frameworks` folder. Closing as this is of topic, but feel free to continue the conversation.
