### ISSUE TITLE
No ads showing in AdMobBanner

### ISSUE THREAD

**Issue by LandDragoon** [sbugert/react-native-admob#243]
I have the following versions installed:

* React Native: 0.52.0
* react-native-admob: 2.0.0-beta.4

When I try to display an AdMobBanner, it does not show any ads. I do get to see the following error (on iOS): _"Error: Request Error: A network error occurred"_. However, the device has a working internet connection, so I don't see what could be wrong there. My AdMobBanner code is as follows:

```jsx
<AdMobBanner
    adSize={"smartBannerPortrait"}
    testDevices={[AdMobBanner.simulatorId]}
    adUnitID={ADMOB_UNIT_ID}
    onAdFailedToLoad={error => console.log(error)}
/>
```

The issue is happening on both iOS (simulator and real device) and Android (only tested on a real device). Any idea what could be the reason for the error I'm seeing?

Edit: on Android the exact error message is: _"Error: The ad request was unsuccessful due to network connectivity."_. Again, the device itself has no connectivity issues as it can successfully retrieve other information in the app from the internet.

**Comment by LandDragoon** [comment]
Never mind, this was an issue on my side. I forgot that my internet connection blocks all ads and forgot to turn it off during testing 😐

**Comment by everton15m** [comment]
what was the issue? I am experiencing the same issue :(

**Comment by Muhammad-Yasir1** [comment]
@LandDragoon did you find the solution I m also getting same issue ?

**Comment by catchstar** [comment]
I am experiencing the same issue :(
