### ISSUE TITLE
Malformed calls from JS: field sizes are different.

### ISSUE THREAD

**Issue by brkrtp** [sbugert/react-native-admob#245]
**I have this error in IOS similator for Interstitial,**
 AdMobBanner and AdMobRewarded working succesfully.
```
ExceptionsManager.js:73 Malformed calls from JS: field sizes are different.

[[66,67,67,23],[0,0,2,0],[[],["ca-app-pub-393.../...393"],[4,2000,1516180490756,false]],57]
```

>     "react": "16.2.0",
>     "react-addons-update": "^15.6.2",
>     "react-native": "0.52.0",
>     "react-native-admob": "^2.0.0-beta.4",
>     "react-native-elements": "^0.18.5",
>     "react-native-splash-screen": "^3.0.6",
>     "react-native-vector-icons": "^4.5.0",
>     "react-navigation": "^1.0.0-beta.23",

**Comment by brkrtp** [comment]
I'm changed my code
`AdMobInterstitial.requestAd(AdMobInterstitial.showAd);`
to
 `AdMobInterstitial.requestAd().then(() => AdMobInterstitial.showAd());`
then fixed.

**Comment by khaled-dev** [comment]
did not work for me

**Comment by KrisShin** [comment]
me neither
