### ISSUE TITLE
Help Needed! How to refresh the PublisherBanner in FlatList

### ISSUE THREAD

**Issue by malonguwa** [sbugert/react-native-admob#249]
I added PublisherBanner into the FlatList, I want to do something like, when refreshing the FlatList, and it will also refresh the PublisherBanner, How could I do it in RN? in iOS its quite easy, just tableView.reload, and it will re-sent ad request. But in RN's FlatList how should I achieve similar feature?

**Comment by malonguwa** [comment]
Solved.

**Comment by judemanutd** [comment]
@malonguwa May I ask how you did it?

**Comment by malonguwa** [comment]
@judemanutd in my case, all I need to do is calling API -> get data -> before you give the data to the flatlist, just this.setState({data: []}, () => {  this.setState({data: dataFromServer})  }). It's all about shallow comparison.
