### ISSUE TITLE
How to Display banner in test mode?

### ISSUE THREAD

**Issue by Uysim** [sbugert/react-native-admob#25]

**Comment by sbugert** [comment]
There's currently now way to set a test device ID for banner ads. I will push a big update soon which will enable this feature.

**Comment by sbugert** [comment]
Hey @Uysim, I just published a new version of react-native-admob!
Now you can enable test mode by setting a prop like this:
```javscript
<AdMobBanner
  testDeviceID="..."
  adUnitID="..."
/>
```
Setting testDeviceID to "EMULATOR" will set it to Simulator mode on iOS and Emulator mode on Android.

Hope it works, please give me feedback if it doesn't!
