### ISSUE TITLE
AdMobInterstitial give bunchs of Possible Unhandled Promise Rejection warning.

### ISSUE THREAD

**Issue by mytc** [sbugert/react-native-admob#253]
I want to show full screen ad every few seconds.  

```
AdMobInterstitial.setTestDevices([AdMobInterstitial.simulatorId]);
AdMobInterstitial.setAdUnitID('ca-app-pub-3940256099942544/1033173712');

componentDidMount(){
    AdMobInterstitial.requestAd();  

  }
_showAd() {
   AdMobInterstitial.requestAd();
    AdMobInterstitial.showAd();
}
```

the `_showAd()` will be invoked in certain circumstances like update rendering. It work as expected, but it come with bunch of following warning. 

```
Possible Unhandled Promise Rejection (id: 39):
W/ReactNativeJS(25060): Error: Ad is not ready.
W/ReactNativeJS(25060): createErrorFromErrorData@http://localhost:8081/index.delta?platform=android&dev=true&minify=false:2016:26
W/ReactNativeJS(25060): http://localhost:8081/index.delta?platform=android&dev=true&minify=false:1968:51
W/ReactNativeJS(25060): __invokeCallback@http://localhost:8081/index.delta?platform=android&dev=true&minify=false:2410:23
W/ReactNativeJS(25060): http://localhost:8081/index.delta?platform=android&dev=true&minify=false:2155:34
W/ReactNativeJS(25060): __guardSafe@http://localhost:8081/index.delta?platform=android&dev=true&minify=false:2323:13
W/ReactNativeJS(25060): invokeCallbackAndReturnFlushedQueue@http://localhost:8081/index.delta?platform=android&dev=true&minify=false:2154:21
W/ReactNativeJS(25060): invokeCallbackAndReturnFlushedQueue@[native code]
```
How do I fix this? Or just ignored it? If so, will it affects the performance?

**Comment by hyorax** [comment]
same problem +1

**Comment by koenpunt** [comment]
You can add a rejection handler; 

```js
AdMobInterstitial.showAd().catch((e) => {
  console.log(e)
});
```

But probably better is only show the ad when it's ready;


```js
AdMobInterstitial.requestAd().then(() => {
    AdMobInterstitial.showAd();
});

**Comment by farhanaslam5151** [comment]
any solution i have the same error

**Comment by Deivesilvaka** [comment]
hello. i am with the same problem. Did you got fix it ?

**Comment by suvammeher95** [comment]
The best solution to this is to use the isReady(callback).
isReady(callback) : Calls callback with a boolean value whether the interstitial is ready to be shown.

I have done something like this inside a class component (you can tweak as required):
`componentDidMount() {
AdMobInterstitial.requestAd().catch();
AdMobInterstitial.isReady(this.showAd);
}`
`showAd = isReady => {
    if (isReady) {
      AdMobInterstitial.showAd().catch();
    } else {
      console.log('ad. not ready yet!!');
    }
  };`
