### ISSUE TITLE
My react-native library files disappeared after installing this module

### ISSUE THREAD

**Issue by idavidson12** [sbugert/react-native-admob#26]
Anyone else report that? I'm using RN 0.26.0

**Comment by sbugert** [comment]
Which files disappeared after installing? And by installing do you mean running `npm install react-native-admob`or also linking it? Or did you link it manually?

**Comment by idavidson12** [comment]
The Library folder with React-Native. I installed it with npm and linked it manually.

**Comment by sbugert** [comment]
That's really strange. By library folder you mean *node_modules/react-native/*?

**Comment by idavidson12** [comment]
It was node_modules/react-native/Library

Now, I haven't been able to recreate the issue, so it might be something totally separate. 

At any rate, thanks for the module. Can you tell me what I need to do to get the sample running. Having some problems there.

**Comment by sbugert** [comment]
Alright, tell me if it happens again.

You need to run `npm install` in the *Example* folder and place the `GoogleMobileAds.framework` in the 
ios* folder and it should work.
