### ISSUE TITLE
After react native admob App running, Appear small red dot

### ISSUE THREAD

**Issue by soorix** [sbugert/react-native-admob#276]
After react native admob App running, Appear small red dot
![error](https://user-images.githubusercontent.com/10239734/38033985-3e48c84e-32dc-11e8-8072-4830f90f12c1.png)
my package.json file info..
"dependencies": {
		"react": "16.0.0-alpha.12",
		"react-native": "0.47.0"
	},
	"devDependencies": {
		"babel-jest": "22.4.3",
		"babel-preset-react-native": "4.0.0",
		"jest": "22.4.3",
		"react-native-admob": "^1.3.2",
		"react-test-renderer": "16.0.0-alpha.12"
	},

Here is my code : 
(index.android.js)
(top headr..)
import {
  AdMobBanner,
  AdMobInterstitial,
  PublisherBanner,
  AdMobRewarded,
} from 'react-native-admob'
(class..)
type Props = {};
export default class App extends Component<Props> {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        // Display a banner
<AdMobBanner
  adSize="fullBanner"
  adUnitID="ca-app-pub-1849424635508075~3774639776"
  testDevices={[AdMobBanner.simulatorId]}
  onAdFailedToLoad={error => console.error(error)}
/>
      </View>
    );
  }
andbody can help me? #

**Comment by koenpunt** [comment]
What does the source code look like? Could this be a banner, but due to layout issues it's sized this small?

**Comment by soorix** [comment]
Here is my code : 
(index.android.js)
(top headr..)
import { BannerView } from 'react-native-fbads';
(class..)
export default class fbadsTest extends Component {
  render() {
    return (
      <View>
      <BannerView
        placementId="213594182724982_213594466058287"
        type="rectangle"
        onPress={() => console.log('click')}
        onError={(err) => console.log('error', err)}
      />
    </View>
    );
  }
}

**Comment by koenpunt** [comment]
Your code contains `react-native-fbads`, not `react-native-admob`, are you sure you aren't mixing up libraries?

**Comment by soorix** [comment]
Entering the code was a mistake. The code was corrected and updated. However, the following error occurred.
-------------------
undefined is not an object (evaluating '_react3.default.PropTypes.string')
<unknown>
    RNAdMobBanner.js:63:30
loadModuleImplementation
    require.js:212:12
guardedLoadModule
    require.js:146:36
_require
    require.js:130:20
<unknown>
    index.js:5
loadModuleImplementation
    require.js:212:12
guardedLoadModule
    require.js:146:36
_require
    require.js:130:20
<unknown>
    App.js:15
loadModuleImplementation
    require.js:212:12
guardedLoadModule
    require.js:146:36
_require
    require.js:130:20
<unknown>
    index.js:2
loadModuleImplementation
    require.js:212:12
guardedLoadModule
    require.js:139:45
_require
    require.js:130:20
global code

**Comment by koenpunt** [comment]
You're using version 1.3 of the library, which is not supported with newer versions of React. Try using the [2.0 beta version](https://github.com/sbugert/react-native-admob/releases/tag/v2.0.0-beta.3)
