### ISSUE TITLE
RNGADBannerView does not exist?

### ISSUE THREAD

**Issue by soorix** [sbugert/react-native-admob#279]
After Build , Run. I have 'RNGADBannerView does not exist' Error.
Anybody know way to fix the error?
Log is.

-----------------------------------------------------------------
Invariant Violation: Native component for "RNGADBannerView" does not exist

This error is located at:
    in RNGADBannerView (at RNAdMobBanner.js:51)
    in AdMobBanner (at App.js:38)
    in RCTView (at View.js:78)
    in View (at App.js:33)
    in App (at renderApplication.js:35)
    in RCTView (at View.js:78)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:78)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:34)
getViewConfig
    requireNativeComponent.js:112:6
get$1
    ReactNativeRenderer-dev.js:13525:17
createInstance
    ReactNativeRenderer-dev.js:13688:27
completeWork
    ReactNativeRenderer-dev.js:10152:14
completeUnitOfWork
    ReactNativeRenderer-dev.js:12209:10
performUnitOfWork
    ReactNativeRenderer-dev.js:12372:32
workLoop
    ReactNativeRenderer-dev.js:12384:43
renderRoot
    ReactNativeRenderer-dev.js:12427:17
performWorkOnRoot
    ReactNativeRenderer-dev.js:13034:34
performWork
    ReactNativeRenderer-dev.js:12951:26
performSyncWork
    ReactNativeRenderer-dev.js:12913:16
requestWork
    ReactNativeRenderer-dev.js:12799:6
scheduleWorkImpl
    ReactNativeRenderer-dev.js:12666:24
scheduleWork
    ReactNativeRenderer-dev.js:12622:28
scheduleRootUpdate
    ReactNativeRenderer-dev.js:13324:17
_updateContainerAtExpirationTime
    ReactNativeRenderer-dev.js:13360:6
updateContainer
    ReactNativeRenderer-dev.js:13385:8
render
    ReactNativeRenderer-dev.js:14119:35
renderApplication
    renderApplication.js:58:21
run
    AppRegistry.js:104:10
runApplication
    AppRegistry.js:196:26
__callFunction
    MessageQueue.js:353:47
<unknown>
    MessageQueue.js:118:26
__guardSafe
    MessageQueue.js:316:6
callFunctionReturnFlushedQueue
    MessageQueue.js:117:17

**Comment by sendyputra** [comment]
@soorix same for me, how to resolve this?

**Comment by krkmzugur** [comment]
@soorix how to resolve this. ? Please answer me. Thanks.

**Comment by chathuralakmal** [comment]
I had the same problem. Once you installed you need to link the library. it is explained here. https://facebook.github.io/react-native/docs/linking-libraries-ios.html#content

**Comment by Verma-Pooja** [comment]
I also face the same problem. I share a link, it might be helpful.
Pls Refer this link:
https://react-native-solutions.blogspot.com/2018/07/how-to-create-react-native-app-with.html
