### ISSUE TITLE
react-native-admob:compileReleaseJavaWithJavac FAILED

### ISSUE THREAD

**Issue by ozmaat** [sbugert/react-native-admob#287]
Hello,

I get the following error while running the react-native run-android.

`:react-native-admob:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
...\node_modules\react-native-admob\android\src\main\java\com\sbugert\rnadmob\RNAdMobRewardedVideoAdModule.java:20: error: RNAdMobRewardedVideoAdModule is not abstract and does not override abstract method onRewardedVideoCompleted() in RewardedVideoAdListener
public class RNAdMobRewardedVideoAdModule extends ReactContextBaseJavaModule implements RewardedVideoAdListener {
       ^
1 error
:react-native-admob:compileReleaseJavaWithJavac FAILED`

I have tested with both admob 1.3.2 and v2.0.0-beta.3 versions. 

"react": "16.2.0",
"react-native": "0.52.0",

**Comment by martinlockett** [comment]
There is an open PR to fix this (PR273)

**Comment by ozmaat** [comment]
Thanks @martinlockett.

**Comment by Veeraharikumar** [comment]
App crashes after updating to react-native-admob@2.0.0-beta-5.Now what to do guys???
