### ISSUE TITLE
Undefined is not an object(evaluating'_react3.default.PropType.shape')

### ISSUE THREAD

**Issue by krkmzugur** [sbugert/react-native-admob#304]
Hello;

I've done a lot of research on the subject. I have not reached a conclusion. How can I solve this problem. Thank you.

![screenshot_1](https://user-images.githubusercontent.com/6763434/39700424-d802e774-5205-11e8-9173-edd3ef2384b6.png)

package.json
```

{
  "name": "OlsunBuSefer",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "prop-types": "^15.6.1",
    "react": "16.3.1",
    "react-native": "0.55.3",
    "react-native-admob": "^1.3.2"
  },
  "devDependencies": {
    "babel-jest": "22.4.3",
    "babel-preset-react-native": "4.0.0",
    "jest": "22.4.3",
    "react-test-renderer": "16.3.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

**Comment by hazeeb** [comment]
You're using 1.x version of this package. Please upgrade to latest version.

**Comment by krkmzugur** [comment]
Android Studio update must. Please upgrade react-native-admob to latest version. Thanks.

**Comment by koenpunt** [comment]
I understand you have managed to resolve your issue, so I'm going to close it.

**Comment by ameshkin** [comment]
after upgrading to the newest version, I get this error

TypeError: undefined is not an object (evaluating '_reactNative.UIManager.RNGADBannerView.Constants')
