### ISSUE TITLE
AdMob Interstitial ad not show full size into screen

### ISSUE THREAD

**Issue by templarstone** [sbugert/react-native-admob#307]
I have an Interstitial Ad in DFP. My creative is 320x480 like is recommended for Instertitials by DFP. But when I call the ad from the app, this not showed full size into screen and look so:

<img width="334" alt="captura de pantalla 2018-05-10 a la s 4 50 05 p m" src="https://user-images.githubusercontent.com/9850861/39896136-901d2612-5472-11e8-8c0a-09220e889964.png">

How do to fit the ad to the screen like that?

<img width="355" alt="captura de pantalla 2018-05-10 a la s 5 15 20 p m" src="https://user-images.githubusercontent.com/9850861/39896979-ff4a0264-5475-11e8-96a7-e9922a8db7f6.png">

**Comment by koenpunt** [comment]
320x480 sounds small to me. But I'm sorry to say that you should look for an answer somewhere else, since the sizing of the interstitial is not managed by this library, but by the Google Mobile Ads SDK.
