### ISSUE TITLE
Argument list too long: recursive header expansion 

### ISSUE THREAD

**Issue by bhram** [sbugert/react-native-admob#314]
hi ,
i search i lot and try all solutions but not work's 
 Argument list too long: recursive header expansion failed at /Users/user/Desktop/project/node_modules/react-native-admob/ios/../../../ios/Pods/React/node_modules/react-tools/src/shared.

this error shows after i update pod 
and this my podfile content 

# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'project' do

  pod 'Google-Mobile-Ads-SDK'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

end

**Comment by Esxiel** [comment]
[Do this for node_modules/react-native-admob/ios/RNAdMobManager.xcodeproj/project.pbxproj ](https://github.com/evollu/react-native-firebase-analytics/commit/e8559a2f00eed245a771e5fdea228c8516d86cbd)

**Comment by bhram** [comment]
i do it in Framework search path $(PROJECT_DIR)/../../../ios/Pods/**
but show error 
Module 'GoogleMobileAds' not found

**Comment by bhram** [comment]
instead of Pods/** i add Pods/Google-Mobile-Ads-SDK 
and it's work , thanks

**Comment by l1br3** [comment]
@abhaypai2611 modify the following file:
`node_modules/react-native-admob/ios/RNAdMobManager.xcodeproj/project.pbxproj`

Line 256 and 270 modify to:
`FRAMEWORK_SEARCH_PATHS = "$(PROJECT_DIR)/../../../ios/Pods/**";`

**Comment by l1br3** [comment]
The file is already fixed in last commits but still not pushed on npm

**Comment by sofianegargouri** [comment]
Still having the problem with the `FRAMEWORK_SEARCH_PATHS` updated:

```
Argument list too long: recursive header expansion failed at /path/to/project/node_modules/react-native-admob/ios/../../../ios/Pods/React/node_modules/lazystream/test.
```
