### ISSUE TITLE
RNAdMobRewardedVideoAdModule is not abstract and does not override abstract method onRewardedVideoCompleted() in RewardedVideoAdListener

### ISSUE THREAD

**Issue by Buwaneka1993** [sbugert/react-native-admob#316]
../node_modules/react-native-admob/android/src/main/java/com/sbugert/rnadmob/RNAdMobRewardedVideoAdModule.java:25: error: RNAdMobRewardedVideoAdModule is not abstract and does not override abstract method onRewardedVideoCompleted() in RewardedVideoAdListener
public class RNAdMobRewardedVideoAdModule extends ReactContextBaseJavaModule implements RewardedVideoAdListener {
       ^

**Comment by ray-shawn** [comment]
+1

**Comment by koenpunt** [comment]
This has been fixed already in https://github.com/sbugert/react-native-admob/pull/273 . Are you using the latest version of this library?

**Comment by ray-shawn** [comment]
I am using 1.3.2 @koenpunt

**Comment by wbrickner** [comment]
I'm encountering this issue, installing directly from npm, following the installation instructions exactly.
What can I do to fix this?

Here are my logs:
`$ react-native run-android`
```
> Task :react-native-admob:compileDebugJavaWithJavac FAILED
/home/will/Documents/ReactNative/VideoToolkit/New/GIFit/node_modules/react-native-admob/android/src/main/java/com/sbugert/rnadmob/RNAdMobRewardedVideoAdModule.java:20: error: RNAdMobRewardedVideoAdModule is not abstract and does not override abstract method onRewardedVideoCompleted() in RewardedVideoAdListener
public class RNAdMobRewardedVideoAdModule extends ReactContextBaseJavaModule implements RewardedVideoAdListener {
       ^
1 error


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-admob:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```
I should mention:
```
Ubuntu 18.10
react-native-cli: 2.0.1
react-native: 0.57.8
```
Thank you for all the hard work you've done, I really appreciate it <3.

**Comment by zxxza11** [comment]
same problem

**Comment by Batuhan-Akkaya** [comment]
same problem

**Comment by amnan181** [comment]
same problem

**Comment by Anandks1993** [comment]
same problem

**Comment by sonicsmith** [comment]
I'm having the same issue. 
`RewardedVideoAdModule is not abstract and does not override abstract method onRewardedVideoCompleted() in RewardedVideoAdListener`
react-native v0.58.4, react-native-admob v1.3.2

**Comment by jdgalani** [comment]
+1
exact same problem

**Comment by kaiserleka** [comment]
+1

**Comment by breakerof** [comment]
+1

**Comment by kinjal111** [comment]
Hello , haivng the issue , please help me
RewardedVideoAdModule is not abstract and does not override abstract method onRewardedVideoCompleted() in RewardedVideoAdListener
react-native v0.58.4, react-native-admob v1.3.2

**Comment by breakerof** [comment]
hi guys, 

if you install the latest version (v2.0.0-beta5) than the bug is gone.

**Comment by kinjal111** [comment]
ok thanks let me try then

    On Saturday, 2 March, 2019, 12:16:49 pm IST, Arton Berisha <notifications@github.com> wrote:  
 
 
hi guys,

if you install the latest version (v2.0.0-beta5) than the bug is gone.

**Comment by kaiserleka** [comment]
I have tried v2.0.0-beta5 
on react-native-cli: 2.0.1 / react-native: 0.58.6

But it makes "application has stopped"

**Comment by breakerof** [comment]
@kaiserleka have you looked at the emulator/device logs? maybe the application-id is wrong or missing?

**Comment by kinjal111** [comment]
@kaiserleka . i was also getting that same issue. but my issue is fixed after i added below statement in 
android\app\build.gradle file
dependencies {
......
    compile 'com.google.android.gms:play-services-ads:15.0.0'
    implementation project(':react-native-admob')
 ...
}

**Comment by bosz** [comment]
> This has been fixed already in #273 . Are you using the latest version of this library?

Thanks man, this saved me hours,

**Comment by laptran-sym** [comment]
> > This has been fixed already in #273 . Are you using the latest version of this library?
> 
> Thanks man, this saved me hours,

That PR resolve this problem but it create new one => stop application

**Comment by Osamasomy** [comment]
> hi guys,
> 
> if you install the latest version (v2.0.0-beta5) than the bug is gone.

But after that app is not load and screen is stuck on "Loading dependency graph, done".

help me if you know !

**Comment by Osamasomy** [comment]
> > > This has been fixed already in #273 . Are you using the latest version of this library?
> > 
> > 
> > Thanks man, this saved me hours,
> 
> That PR resolve this problem but it create new one => stop application

**Comment by Osamasomy** [comment]
> I have tried v2.0.0-beta5
> on react-native-cli: 2.0.1 / react-native: 0.58.6
> 
> But it makes "application has stopped"

 implementation ('com.google.android.gms:play-services-ads:16.+') { force = true; }

put in android/app/build.gradle 
its work for me i am using react-native 0.16.4

**Comment by iLevye** [comment]
Some versions (don't ask which one) of [com.google.android.gms.ads.reward.RewardedVideoAdListener](https://developers.google.com/android/reference/com/google/android/gms/ads/reward/RewardedVideoAdListener) requires onRewardedVideoCompleted function. RNAdMobRewardedVideoAdModule class implements that class. 

If you don't want to manage gms versions you can just create an empty function. 

RNAdMobRewardedVideoAdModule.java
```
    @Override
    public void onRewardedVideoCompleted(){

    }
```

If your version of react-native-admob has onRewardedVideoCompleted function and you are getting 'method doesnt override' error, then remove the @Override annotation from method.

**Comment by Sanan4li** [comment]
> @Override
>     public void onRewardedVideoCompleted(){
> 
>     }

It Worked but Now the App is Crashed...

**Comment by amnan181** [comment]
Hi @Sanan4li please add this ------=> 
```
<meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-xxxxxxxxxxxxxxxx~yyyyyyyyyy"/>
```
into android AndroidManifest.xml

**Comment by amnan181** [comment]
For more information you can visit official link https://developers.google.com/admob/android/quick-start

**Comment by Sanan4li** [comment]
> Hi @Sanan4li please add this ------=>
> 
> ```
> <meta-data
>             android:name="com.google.android.gms.ads.APPLICATION_ID"
>             android:value="ca-app-pub-xxxxxxxxxxxxxxxx~yyyyyyyyyy"/>
> ```
> 
> into android AndroidManifest.xml
> you can find AndroidManifest.xml from your_project_name/android/app/src/main

Thanks... I have tried it but still my app crashes when I install it.

**Comment by amnan181** [comment]
can you send me AndroidManifest.xml code

**Comment by Sanan4li** [comment]
> can you send me AndroidManifest.xml code

I updated the comment.. after reinstalling the app it worked..

**Comment by amnan181** [comment]
> > Hi @Sanan4li please add this ------=>
> > ```
> > <meta-data
> >             android:name="com.google.android.gms.ads.APPLICATION_ID"
> >             android:value="ca-app-pub-xxxxxxxxxxxxxxxx~yyyyyyyyyy"/>
> > ```
> > 
> > 
> > into android AndroidManifest.xml
> > you can find AndroidManifest.xml from your_project_name/android/app/src/main
> 
> Thanks... it worked but having another issue... I think it will be fixed... Thanks a lot.

Great

**Comment by amnan181** [comment]
> > Hi @Sanan4li please add this ------=>
> > ```
> > <meta-data
> >             android:name="com.google.android.gms.ads.APPLICATION_ID"
> >             android:value="ca-app-pub-xxxxxxxxxxxxxxxx~yyyyyyyyyy"/>
> > ```
> > 
> > 
> > into android AndroidManifest.xml
> > you can find AndroidManifest.xml from your_project_name/android/app/src/main
> 
> Thanks... it worked but having another issue... I think it will be fixed... Thanks a lot.

Great
