### ISSUE TITLE
Interstitial ad frequency cap

### ISSUE THREAD

**Issue by mmelitzer** [sbugert/react-native-admob#32]
I've configured a frequency cap on a interstitial ad to show no more than 1 per 30 minutes but each time the call request(show) it displays the ad?
Do you know if that's just because I'm testing with deviceId("EMULATOR") or is this cap not supported and I've to implement it myself in the app?

Great work by the way, it's awesome

**Comment by sbugert** [comment]
If you call `request(show)` it is expected behavior that it displays the ad.
`request` has a callback as its argument so if you pass `show`, it will display the ad right away after loading.

Does [this](https://github.com/sbugert/react-native-admob/blob/master/Example/index.ios.js) example help you?

**Comment by mmelitzer** [comment]
No, I mean frequency capping, when I create a Interstitial on AdMob where I get the unitId, there's the option Frequency capping with the following description: "Limits the number of times ads are shown to the same person per minute, per hour, or per day."
So basically you're saying this capping isn't considered and I'd have to implement the capping in the app directly, right?

**Comment by mmelitzer** [comment]
Or do I misunderstand the capping and it just means that the user gets the 'same' ad in the capped period, wouldn't really make much sense to me that way, why would I care which ad is shown vs how often the user is 'bothered'

**Comment by sbugert** [comment]
Ah, I see!
I haven't used this feature myself but I understand it like you.

[This](http://stackoverflow.com/questions/28544875/ios-dfp-and-google-mobile-sdk-frequency-capping-fails) stackoverflow post suggests that it could have something to do with using the emulator mode.

**Comment by mmelitzer** [comment]
Seems reasonable, I'll comment once I'm running on a device and tested it

**Comment by mmelitzer** [comment]
Long time but finally my app made it in the appStore and I was able to try it out, yes, frequency works perfectly fine in prod and exactly the way it's supposed to be (capping the times the interstitial is shown in total in the period).

**Comment by booboothefool** [comment]
@mmelitzer So what was the issue? Did you ever run any betas e.g. TestFlight/Google Play Beta/HockeyApp?

In Dev yeah, they show up every time. But in my HockeyApp, it seems like sometimes they obey the timer, sometimes they don't.

Are you saying that once I get these out to the App Store/Google Play Store it'll magically obey the timers?

**Comment by manuhook** [comment]
@booboothefool  @mmelitzer any news on that ?
I'm running the app throught Tesflight and the capping is not respected for interstitials.
Same on Beta Version throught Google Play ... :(
i'm afraid to go in production because of that ...
