### ISSUE TITLE
feature suggestion: Support Ad Targeting

### ISSUE THREAD

**Issue by xing-zheng** [sbugert/react-native-admob#33]
Hi @sbugert , I'm so appreciate in your great plugin, and is there any plan to support Ad Targeting?

**Comment by sbugert** [comment]
Hi @xing-zheng,
yes it's a planned feature. I can't give any estimates though, but I have more time in August.

**Comment by firangistan** [comment]
Well [this fork](https://github.com/adeelraza/react-native-admob) has implemented Ad Targeting and could be of use :)
