### ISSUE TITLE
Couldn't implement publisher ads

### ISSUE THREAD

**Issue by SergiOnGit** [sbugert/react-native-admob#333]
Can anyone help? I did everything correctly but ads doesn't show up and what can be a reason?Admob ads work but publisher ads not

**Comment by joseph-engelmajer** [comment]
Currently experiencing the same behavior. PublisherBanner component doesn't show anything for either test ads or real ads from the ad inventory. Ad mounts, onAdLoaded is called but nothing shows. Would be interested to know if others are having the same experience and if/how you've managed to solve it
