### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RNGADBannerView" was not found in the UIManager.

### ISSUE THREAD

**Issue by jasrajput** [sbugert/react-native-admob#339]
**I recently installed admob for react-native.but i m getting an error "RNGADBannerView" was not found in the UIManager".I don't know what that supposed to mean?**

`_can anyone help?_`

import {AdMobBanner} from 'react-native-admob';

      export default class Home extends Component{
       render(){
        return <View>
            <Text>helo</Text>
            <AdMobBanner
                adSize="fullBanner"
                adUnitID="ca-app-pub-"my_id"
                onAdFailedToLoad={error => console.error(error)}
            />
        </View>
    }

 

**dependencies:**

       "react": "16.4.1",
       "react-native": "0.56.0",
       "react-native-admob": "^2.0.0-beta.5",
       "react-native-fbsdk": "^0.7.0",
        "react-navigation": "^2.6.2"

**Comment by Verma-Pooja** [comment]
In {adUnitID="ca-app-pub-"my_id"} you can put Sample ad Unit ID for testing or Original ad Unit Id which you might be created
I use sample ad unit Id here,
adUnitID="ca-app-pub-3940256099942544/6300978111"
You can refer to this link:
https://react-native-solutions.blogspot.com/2018/07/how-to-create-react-native-app-with.html


"

**Comment by jasrajput** [comment]
@Verma-Pooja I  use my own ad unit id too.But it didn't work as i expected

**Comment by elena87** [comment]
I have the same issue. @jasrajput have you found the solution in the meantime?

**Comment by Momazo7u7** [comment]
Hi, i had the same issue, apparently you don´t need to press "reload" in the app for this package to work, i fixed it by just doing" react-native run-android " in the project console and then on the app the ads were showing and not giving this error.
Hope i helped someone , might be a stupid solution , but if you only use adb to reaload your problem , this simple solution can go over your head ;)

**Comment by Verma-Pooja** [comment]
@jasrajput, @elena87 Did you guys link admob?
react-native link react-native-admob. then run your code. It is working.
you can refer to this link:
https://react-native-solutions.blogspot.com/2018/08/problems-related-to-admob-updated.html

**Comment by snapxtp** [comment]
I've tried all the solutions written here in react-native link react-native-admob but I keep getting the same error.

**Comment by steventiro** [comment]
I have the same problem. 
I followed the installation manual step by step and make sure googleMobileAds framework and React native admob linked to my app but i got the same warning: "RNGADBannerView" was not found in the UIManager.

these are my dependencies:
    "react": "16.4.1",
    "react-native": "0.56.0",
    "react-native-admob": "^2.0.0-beta.5"

can any one help?

![simulator screen shot - iphone 6 - 2018-08-29 at 06 54 45](https://user-images.githubusercontent.com/30956559/44755407-ab0c9380-ab58-11e8-9179-1ef093ecf8e2.png)

**Comment by Momazo7u7** [comment]
Yep , after building a new project and installing this admob module i got an error.
Solved it with the solution posted in https://react-native-solutions.blogspot.com/2018/08/problems-related-to-admob-updated.html

1)go to your app main folder
2)then go inside node_modules bla bla
"/node_modules/react-native-admob/android/src/main/java/com/sbugert/rnadmob/"

3)Then open RNAdMobRewardedVideoAdModule.java with any text editor of your choice.

4) Finally Go to line 89 and delete "@Override" from that line 

5)react native run-android (i didn't tested this on ios, since there the linking process is different while in android is just "react-native link"

**Comment by Momazo7u7** [comment]
Oh , i should say that i'm using react-native 0.55.4, maybe they broke something in 0.56/0.57

**Comment by jetonk** [comment]
did anyone found a solution for this issue?

**Comment by manojkumawat003** [comment]
Have you linked admob using `react-native link react-native-admob`

**Comment by nilde** [comment]
**react-native run-ios** worked for me.

**Comment by azsidhu** [comment]
react-native-admob is linked, I've verified, still getting the same error. Any solution?

**Comment by erdemozveren** [comment]
I try everything and found @nqtuyen92's solution and it worked for me (sort of) and now error turned a yellow box error but app is running and ad is showing.
Current i have this yellow box error 

> "Accessing view manager configs directly off UIManager via UIManager['RNGADBannerView'] is no longer supported. Use UIManager.getViewManagerConfig('RNGADBannerView') instead."

What i did is 
find build.gradle in "node_modules/react-native-admob/android" and change 
`compile 'com.google.android.gms:play-services-ads:+'` to `compile 'com.google.android.gms:play-services-ads:15.0.0'`

**Comment by RoderickJDunn** [comment]
For me I was getting this error even after running `react-native link react-native-admob`

There must have been a problem linking it the first time because I solved it by running `react-native unlink react-native-admob`, then `react-native link react-native-admob` again.

**Comment by magic990619** [comment]
I also have the same issue on ios. 
`Invariant Violation: requireNativeComponent: "RNGADBannerView" was not found in the UIManager.`

I tried the solutions but it did not work for me.
```
    "react": "16.8.6",
    "react-native": "0.60.5",
    "react-native-admob": "^2.0.0-beta.5",
```
I tried react-native link react-native-admob.
But after that, I got an error in building. I could not run the app.
Please help.

**Comment by taha4954** [comment]
> I also have the same issue on ios.
> `Invariant Violation: requireNativeComponent: "RNGADBannerView" was not found in the UIManager.`
> 
> I tried the solutions but it did not work for me.
> 
> ```
>     "react": "16.8.6",
>     "react-native": "0.60.5",
>     "react-native-admob": "^2.0.0-beta.5",
> ```
> 
> I tried react-native link react-native-admob.
> But after that, I got an error in building. I could not run the app.
> Please help.

Same issue!!

**Comment by shairamiri** [comment]
> I also have the same issue on ios.
> `Invariant Violation: requireNativeComponent: "RNGADBannerView" was not found in the UIManager.`
> 
> I tried the solutions but it did not work for me.
> 
> ```
>     "react": "16.8.6",
>     "react-native": "0.60.5",
>     "react-native-admob": "^2.0.0-beta.5",
> ```
> 
> I tried react-native link react-native-admob.
> But after that, I got an error in building. I could not run the app.
> Please help.

Did anyone solve this? 
Can't get it working on iOS.
Android works fine

**Comment by sasssssha** [comment]
I did cmd+shift+k
then cleaned derived-data folder
and then got the problem gone

**Comment by ayciceksahin** [comment]
> I also have the same issue on ios.
> `Invariant Violation: requireNativeComponent: "RNGADBannerView" was not found in the UIManager.`
> 
> I tried the solutions but it did not work for me.
> 
> ```
>     "react": "16.8.6",
>     "react-native": "0.60.5",
>     "react-native-admob": "^2.0.0-beta.5",
> ```
> 
> I tried react-native link react-native-admob.
> But after that, I got an error in building. I could not run the app.
> Please help.

Same Problem.. Please help

**Comment by jasrajput** [comment]
> > I also have the same issue on ios.
> > `Invariant Violation: requireNativeComponent: "RNGADBannerView" was not found in the UIManager.`
> > I tried the solutions but it did not work for me.
> > ```
> >     "react": "16.8.6",
> >     "react-native": "0.60.5",
> >     "react-native-admob": "^2.0.0-beta.5",
> > ```
> > 
> > 
> > I tried react-native link react-native-admob.
> > But after that, I got an error in building. I could not run the app.
> > Please help.
> 
> Same Problem.. Please help

kindly wait for some time to get refresh your account on admob & don't forget to run react-native run-android or ios based on the platform you are using afterwards..It took me 2 days to get verified at admob.

**Comment by minhchienwikipedia** [comment]
I found the best way to resolve this issue. Seem `react-native link react-native-admob` not work as well on iOS, so you need to manual linking like React Native docs ([link](https://reactnative.dev/docs/linking-libraries-ios#manual-linking)). It's works as well for me!

**Comment by tgreco** [comment]
I resolved this by running these commands: 
`react-native link react-native-admob && cd ios && pod install`

**Comment by YousefAlsbaihi** [comment]
Solved it by doing the following: 
**Android**
1. run `react-native link react-native-admob`
    this will give you the following log 
    <img width="582" alt="Screen Shot 2020-08-17 at 4 47 47 PM" src="https://user-images.githubusercontent.com/19701357/90454922-69f54d00-e0a9-11ea-8998-bca2ef19102e.png">

2. Open Android Studio and go to **Build** -> **Clean Project**
3. Delete the app from the simulator
4. run `npx react-native start`
    After the bundle started if you faced this error 
    <img width="911" alt="Screen Shot 2020-08-17 at 4 51 24 PM" src="https://user-images.githubusercontent.com/19701357/90455095-ee47d000-e0a9-11ea-8d2c-50585b9de5da.png">
    ignore it and open Android Studio Clean your project and run it from Android Studio


This solution worked for me perfectly 👍

**Comment by yussems** [comment]
actually know. emulator is crush 3 times i try but didn't work. my  didnt app open

**Comment by YousefAlsbaihi** [comment]
i'm not sure if this is still useful but 
i installed the library again 

1. run this command to unlink if it's linked, remember react native auto-linking is working fine 
`npx react-native unlink react-native-admob`
2. remove the library from the project 
`npm unlink react-native-admob -S`
3. run pod install 
`npx pod-install` OR `cd ios && pod install`
4. install the library again 
`npm i react-native-admob -S` OR `yarn react-native-admob`
5. after installation complete, open ios/Podfile file and add the following 
` pod 'Google-Mobile-Ads-SDK', '7.69.0' `
6. run pod install


that should solve it.

**Comment by otacilioricardo** [comment]
Hello.

After installing AdMob the following error occurs: "RequireNativeComponent: RNGDBannerView was not found in the UIManager".

I tried all the alternatives indicated and it didn't work.

Can anyone help?

What's another way to place ads in the App using React Native?

Thanks.

**Comment by HannesHuwe** [comment]
I also still got this problem.
As I'm trying to unlink admob i get: info Android module "react-native-admob" is not installed
Even though I've just run the link command with a success message.
