### ISSUE TITLE
RN 0.29.2 requestAd causes freezing

### ISSUE THREAD

**Issue by hasen6** [sbugert/react-native-admob#34]
This error did not happen for me in RN 26.3 but is happening in 29.2. I isolated it to this call 

`AdMobInterstitial.requestAd((error) => error && console.log(error));`

It causes the component to freeze for a second or two so for example you can't press any buttons during this time. Then after the two seconds pass the delayed response to the button presses occurs. With this line commented out there is not freeze at all so the error is definitely with this. I got all the code from the example program and it was working fine in 26.3 as I say.

**Comment by sbugert** [comment]
Is this happening on Android or iOS? 0.29 introduced some changes to the Android template, this could be related.

**Comment by hasen6** [comment]
Ok I should have said, yeah its iOS.

**Comment by sbugert** [comment]
I can't reproduce this. I just updated the example project to 0.29.2 and it still works fine.

**Comment by hasen6** [comment]
That's because the example project doesn't do anything other than show ads. It causes a freeze in the midst of other actions being executed by other code.

**Comment by sbugert** [comment]
I added a slider and a background video (using react-native-video) but I still can't see any blocking of the UI thread. Are you sure there isn't something else blocking?
AdMob is indeed running on the main thread but it's mandatory and it throws an exception if it does not.
But this shouldn't be the problem.
![demo](https://cloud.githubusercontent.com/assets/2883939/17020923/a6693e86-4f44-11e6-867c-ebce0c8bfbef.gif)

**Comment by hasen6** [comment]
Try some kind of animation delayed with setInterval set at ComponentDidMount that takes a few seconds to complete. Its hard to notice even in my code. If there were no animation controlled by setInterval I wouldn't have noticed it. It must be the AD since if I comment out that single line it fixes the problem completely. It must be some kind of delay with the ad request.

It also only happens on the first time the component loads. If I exit back one page with navigator.pop and then go back in, it doesn't freeze.

**Comment by hasen6** [comment]
I tried it with your example code that you've just updated, with all the console logging and at the exact point it freezes the log outputs:  `'interstitialDidLoad event'`

**Comment by sbugert** [comment]
Can you show me the part of your code where you do the animation?

**Comment by hasen6** [comment]
That's the point it freezes when it returns the log message. Exactly at that point. I checked specifically that its not just sending the log message before.....it really is exactly at the point where it freezes.

Ok here is some of my code but its a bit too long to show much so I've just included those parts that are experiencing the freeze.. The renderChars() function is what draws the animation and then freezes at some point during:

`componentDidMount() {
  AdMobInterstitial.setAdUnitID('ca-app-pub-9647718344871529/3219214476');
  AdMobInterstitial.addEventListener('interstitialDidLoad',
    () => console.log('interstitialDidLoad event'));
  AdMobInterstitial.addEventListener('interstitialDidClose',
    this.interstitialDidClose);
  AdMobInterstitial.addEventListener('interstitialDidFailToLoad',
    () => console.log('interstitialDidFailToLoad event'));
  AdMobInterstitial.addEventListener('interstitialDidOpen',
    () => console.log('interstitialDidOpen event'));
  AdMobInterstitial.addEventListener('interstitialWillLeaveApplication',
    () => console.log('interstitalWillLeaveApplication event'));

  AdMobInterstitial.requestAd((error) => error && console.log(error));
  this.interval = setInterval(() => {this.tick()}, 50);
}
tick() {
  if (this.state.counter >= entries.length-1) return;
  this.setState({counter: this.state.counter + 1});
}
renderChars() {
  var temp=[];
  for (var i = 0; i < entries.length && i <= this.state.counter; i++) {
      temp.push(this.chars(i,style))
  }
  return temp;
}
chars(number,style) {
  return (<Animated.View key={number} style={style} onTouchStart={() => this.clickTileOn(number)} onTouchEnd={() => this.clickTileOff(number,entries[number])}>
    <Text style={styles.charboxtext}>{entries[number]}</Text>
    </Animated.View>);
}`

**Comment by sbugert** [comment]
(I edited your comment to use three backticks for the code)

I don't fully understand how your code works but I guess you should not be calling setState for your animation every 50 milliseconds. All the [animation examples](https://facebook.github.io/react-native/docs/animations.html) in the docs are using the Animated api to change the values. Maybe that helps?

Also as I said, when you see `interstitialDidLoad event` the interstitial code should not be doing anything anymore and is done. But it's still weird that removing this line solves the problem.

**Comment by hasen6** [comment]
Well its not an animation in that sense, its just a normal render with a for loop but every step of the for loop is delayed by interval. So for example it could generate all the letters of the alphabet but with this code instead of just generating them all simultaneously, it generates the letters in order one after the other with a small pause in between each one. So it creates a kind of domino/waterfall effect if you can imagine to render the letters instead of them all appearing at once.

That line of ad code clearly interrupts it for some reason. Its the same code I was using before with RN 26.3 which had no issues at all.

**Comment by sbugert** [comment]
Could you try debugging with a systrace? Or give me a minimal working code (maybe a github gist?) so I can make a systrace? I think this would clear things really quickly.
[This issue](https://github.com/facebook/react-native/issues/7995) could also be related but I still can't reproduce it.


This is what my systrace looks like with a [simple looped animation](https://rnplay.org/apps/QlPJ2Q) and showing the interstitial. No freezing, nothing takes too long, everything normal.
![screenshot 2016-07-23 15 59 15](https://cloud.githubusercontent.com/assets/2883939/17078264/759ffd5c-50ee-11e6-90b4-f2f2d36242ce.png)
The blue marked block is the call of requestAd. The invoked callback also does not take long.

**Comment by hasen6** [comment]
That appears to be an Animation using Animated? Not like what I'm using at all. If you just generate anything like, the text from a-z with a for loop and then have it broken up with delays between each letter using setInterval that will be the same as my code.

I've attached my systrace.

[Trace from _tmp_dump_1469335227214.json.html.zip](https://github.com/sbugert/react-native-admob/files/380125/Trace.from._tmp_dump_1469335227214.json.html.zip)

**Comment by sbugert** [comment]
I know that you are not using Animated. But I think you should be. My example demonstrates that `requestAd` does not slow down anything (for me at least).
(Btw, why are you using `Animated.View` in your code?)

I can't open the systrace, I get an error `Uncaught TypeError: Object.observe is not a function`. Could you send me just the json file please?

**Comment by hasen6** [comment]
Well it only slows down certain things. I noticed other parts of the render were not slowed down at all, so may be something to do with the setInterval. It uses Animated.View for a separate animation which occurs only when clicking on the characters, not when they initially render.

Not sure how to send you a json. I noticed the systrace didn't open in Chrome, it just returned a blank screen so I searched regarding this problem and it suggested saving it and then opening it with chrome://tracing. I think if you just delete the .html at the end it will be a json file? Or if you use Chrome then try opening it with chrome://tracing

Initially the systrace is opened in Chrome but the file is not saved anywhere at that point is it? At least I couldn't find it anywhere.

Yes I noticed 0.30.0 has been released but haven't tried it yet. Worth a try although it may make things worse even.

**Comment by sbugert** [comment]
No, just changing the file extension won't make it a json file.
How did you install trace2html? Because I think the current homebrew version is broken as it assumes that Chrome still ships with Object.observes which it does not anymore.
When I run the systrace it saves the file in `/tmp/` so for example `/tmp/dump_1469287910008.json`.

**Comment by hasen6** [comment]
It says `trace2html-06-23 already installed` but it opens with .html attached. I installed it with `brew install trace2html`

I think the simplest way is to just open it with Chrome.

http://stackoverflow.com/questions/36865899/react-native-android-systrace-html-is-blank-in-ubuntu-14-04/37549425#37549425

**Comment by sbugert** [comment]
It worked, thank you!

I still believe that you're doing way too many things in react. You can clearly see that the javascript thread is swamped. (if you select *highlight VSYNC* you can see that)

What I can suggest is taking all this code for the letters into a seperate component and optimizing it there.
If that does not help I don't have any ideas anymore and I think this is out of my scope as the maintainer of this library until I can cleary reproduce admob to be the problem.
