### ISSUE TITLE
Do I paste the app ID anywhere? My ads are not showing on my testing device with a minimal example.

### ISSUE THREAD

**Issue by Alanz2223** [sbugert/react-native-admob#345]
**Edit - I've browsed the docs and found that using the test ad unit id `ca-app-pub-3940256099942544/6300978111` displays an ad. So that tells me that my app id configuration is wrong, still can't get that to work since I am sure it may have something to do with me not adding my app ID.

**Edit 2- I set the app ID as per issue #131 ,I've built my app for production with the ad unit id that I know for sure exists since I can see it in the console as a banner ad and I get the following error `The ad request was successful, but no ad was returned due to lack of ad inventory`

Hello, I have a minimal implementation going and I can't seem to get any ads to display. My app is already in the app store so I added it in the admob console and created a banner unit on that app. Then I pasted the id inside my banner like so

        <AdMobBanner
        adSize="banner"
        adUnitID="the-unit-id-for-the-app"
        testDevices={[AdMobBanner.simulatorId]}
        adViewDidReceiveAd={(a) => console.log("RECEIVED AD " + a)}
        didFailToReceiveAdWithError={this.bannerError} />

However I have not used the app ID anywhere since it hasnt been mentioned in any of the instructions.

I am linking against

`include ':RNAdMob', ':app'
project(':RNAdMob').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-admob/android')
`

and my dependency inside build.graddle

`    compile project(':RNAdMob')`

` targetSdkVersion 24`

`"react-native-admob": "^2.0.0-beta.5",`

I even tried adding 

`<activity
  android:name="com.google.android.gms.ads.AdActivity"
  android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize" />`

as per his solution in issue #38 but nothing... I've ran both debug and release versions on my device (6.0.1). There is nothing being logged by log cat or the didFailToReceiveAdWithError prop. Thanks.

**Comment by Alanz2223** [comment]
I waited some time and added a new banner, it works now.

**Comment by AbdulrahmanAfify** [comment]
do you paste app id anywhere ? or it run without it ? 
and is it show real ads or test ads

**Comment by AbdulrahmanAfify** [comment]
@Alanz2223
