### ISSUE TITLE
The ad request was successful, but no ad was returned due to lack of ad inventory.

### ISSUE THREAD

**Issue by zymethyang** [sbugert/react-native-admob#349]
Hi, I faced a problem when using react-native-admob with reward ads. The error code here `{ [Error: The ad request was successful, but no ad was returned due to lack of ad inventory.] framesToPop: 1, code: 'ERROR_CODE_NO_FILL' }`. Do you have any idea?

**Comment by SergiOnGit** [comment]
Use test ads https://developers.google.com/mobile-ads-sdk/docs/dfp/android/test-ads

**Comment by zymethyang** [comment]
It worked with the test ads, but when I replace with my ads I received an error.

**Comment by SergiOnGit** [comment]
Then problem is in your ads not in code

**Comment by zymethyang** [comment]
How about another problem? I had created ads on Admob, wait 6 hours after that replace ads id. Where I wrong?

**Comment by SergiOnGit** [comment]
I don't know what you did in admob panel, but i can say that if test ads showing up then code is ok

**Comment by koenpunt** [comment]
As @sergiongit says; this had to do with the ads, not this library

**Comment by zymethyang** [comment]
Thank you very for help!. I have already found out the problem. Sometimes we have to wait several days for the ads delivery.

**Comment by vision669** [comment]
It such a pain how they never said anything on waiting for days before showing ads. In my case, I have to wait 3 days before ads start showing. During that wait period you could be trying to fix something that is not broken.

**Comment by Viktor19931** [comment]
I have same issue just on android. I tried on test id and got this error. 
Do you guys have any suggestion?

**Comment by ricardoneves93** [comment]
If your app is getting few requests to ads, from my personal experience, it can take a while to return ads. If the test ads are working fine, you don't need to worry, you'll have ad inventory soon. It may take 2/3 days after releasing to play store or getting some meaningful real ads requests.

**Comment by Viktor19931** [comment]
Thanks for quick response! I also used test ads ... still same result(

**Comment by vammu920** [comment]
> I don't know what you did in admob panel, but i can say that if test ads showing up then code is ok

@SergiOnGit  hey iam facing the same error in test ads also please help me with this

**Comment by Sanan4li** [comment]
facing same issue... its been 2 days i created the ad unit but still this error occurs.. It works with test ads.

**Comment by anasalsaadi14** [comment]
any update?

**Comment by Krasnovyd** [comment]
Just use test ads id
https://developers.google.com/admob/android/test-ads

**Comment by Sanan4li** [comment]
I solved the issue ..
You have to verify your address by submitting id card to google. Check your linked adsense account. They will ask you to fill a form, after that you can serve ads.

**Comment by genesy** [comment]
I tried a blank expo app and installed their version of admob and used the ids i have and it shows the ads there properly.

**Comment by fernando-pascoal** [comment]
I have some problem.How did you solve?

**Comment by ricardoneves93** [comment]
Hey @fernando-pascoal!
That is a normal behavior, it usually means that everything is good with your configuration.
You'll need to wait a few days so that google starts delivering ads.
I've already had this problem with app released to the Google Play Store.

**Comment by Sanan4li** [comment]
> I have some problem.How did you solve?
> 
> ```dash
> The ad request was successful, but no ad was returned due to lack of ad inventory.
> ```

You have to submit your address and other information they ask..
And wait for couple of days

**Comment by fernando-pascoal** [comment]
@Sanan4li Thank you. But my adUnitID is used in another app build with Swift and Java. Both are in the store and works. I created my app with react-native now and need admanager.

**Comment by Sanan4li** [comment]
If you are using the same ads in another app.. don't do it.. make a new app in admob and use new ads..

**Comment by fernando-pascoal** [comment]
It's not in stores yet. I will replace the two with a react-native app.

**Comment by eflez** [comment]
How can I fix lack of inventory issues in my admob

**Comment by Sanan4li** [comment]
> How can I fix lack of inventory issues in my admob 

How many days you have been seeing this error?
You have to wait for couple of days before ads start working.

**Comment by Revathicolourmoon0140** [comment]
You have to wait for couple of days before ads start working.

please help me,

even test ids are not working

**Comment by fernandopascoalbr** [comment]
@Revathicolourmoon0140 the test ids works. Maybe you set something wrong. In my repositories has a fork of this project and works fine. (customTargets also). https://github.com/fpgce/react-native-admob

**Comment by Revathicolourmoon0140** [comment]
<View style={styles.container}>                <Text>AdMobBanner</Text>        <AdMobBanner          height="20%"          width="50%"          adSize="smartBannerPortrait"          adUnitID="ca-app-pub-3940256099942544/6300978111"          //testDeviceID="B6499E4085FA67BE43006DB7DB54F3B3"          onAdFailedToLoad={error => console.log(error)}        />        <Text>AdMobBanner</Text>      </View>
Hello sir,
thank you for your reply.
i am doing this way as i mention the above attachment . but i got an error can u help me please,

The ad request was successful, but no ad was returned due to lack of ad inventory.

this only iam getting.
Thanks and Regards,
Revathi 

    On Wednesday, September 23, 2020, 06:34:32 PM GMT+5:30, Fernando Pascoal <notifications@github.com> wrote:  
 
 


@Revathicolourmoon0140 the test ids works. Maybe you set something wrong. In my repositories has a fork of this project and works fine. (customTargets also). https://github.com/fpgce/react-native-admob

**Comment by Mrjavaci** [comment]
SoMe PrObLeM

**Comment by ankitpatel7225** [comment]
I have same issue in my project with test unit in banner app . see my app.js if any kind of error in that ?
I m new in react native so please help me for that 

import React, { Component } from 'react';
import {
  Button,
  StyleSheet,
  View,
} from 'react-native';
import admob, { MaxAdContentRating, BannerAd, TestIds, BannerAdSize } from '@react-native-firebase/admob';

export default class App extends Component {

  componentDidMount() {
    admob()
      .setRequestConfiguration({
        // Update all future requests suitable for parental guidance
        maxAdContentRating: MaxAdContentRating.G,

        // Indicates that you want your content treated as child-directed for purposes of COPPA.
        tagForChildDirectedTreatment: true,

        // Indicates that you want the ad request to be handled in a
        // manner suitable for users under the age of consent.
        tagForUnderAgeOfConsent: true,
      })
      .then(() => {
        // Request config successfully set!
      });

  }

  render() {
    return (
      <View style={styles.body}>
        <BannerAd
            unitId={TestIds.BANNER}
            size={BannerAdSize.SMART_BANNER}
            requestOptions={{
            requestNonPersonalizedAdsOnly: true,}}
            onAdLoaded={() => {
            console.log('Advert loaded');}}
            onAdFailedToLoad={(error) => {
            console.error('Advert failed to load: ', error);}}
            />
        <Button title="Click here"  onPress={() => {
   
      }}></Button>
      </View>
    );
  }
};

const styles = StyleSheet.create({
  body: {
    backgroundColor: '#fff',
  }
});



same issue :

Advert failed to load:  [Error: [admob/error-code-no-fill] The ad request was successful, but no ad was returned due to lack of ad inventory.]

please any one help in firebase dashboard show my app was install in steam view but in app no ad load in real device

**Comment by Sanan4li** [comment]
> I have same issue in my project with test unit in banner app . see my app.js if any kind of error in that ?
> I m new in react native so please help me for that 
> 
> import React, { Component } from 'react';
> import {
>   Button,
>   StyleSheet,
>   View,
> } from 'react-native';
> import admob, { MaxAdContentRating, BannerAd, TestIds, BannerAdSize } from '@react-native-firebase/admob';
> 
> export default class App extends Component {
> 
>   componentDidMount() {
>     admob()
>       .setRequestConfiguration({
>         // Update all future requests suitable for parental guidance
>         maxAdContentRating: MaxAdContentRating.G,
> 
>         // Indicates that you want your content treated as child-directed for purposes of COPPA.
>         tagForChildDirectedTreatment: true,
> 
>         // Indicates that you want the ad request to be handled in a
>         // manner suitable for users under the age of consent.
>         tagForUnderAgeOfConsent: true,
>       })
>       .then(() => {
>         // Request config successfully set!
>       });
> 
>   }
> 
>   render() {
>     return (
>       <View style={styles.body}>
>         <BannerAd
>             unitId={TestIds.BANNER}
>             size={BannerAdSize.SMART_BANNER}
>             requestOptions={{
>             requestNonPersonalizedAdsOnly: true,}}
>             onAdLoaded={() => {
>             console.log('Advert loaded');}}
>             onAdFailedToLoad={(error) => {
>             console.error('Advert failed to load: ', error);}}
>             />
>         <Button title="Click here"  onPress={() => {
>    
>       }}></Button>
>       </View>
>     );
>   }
> };
> 
> const styles = StyleSheet.create({
>   body: {
>     backgroundColor: '#fff',
>   }
> });
> 
> 
> 
> same issue :
> 
> Advert failed to load:  [Error: [admob/error-code-no-fill] The ad request was successful, but no ad was returned due to lack of ad inventory.]
> 
> please any one help in firebase dashboard show my app was install in steam view but in app no ad load in real device

Please check this comment https://github.com/sbugert/react-native-admob/issues/349#issuecomment-603538984
If your admob account is new you have to submit address for verification. Also wait for 2,3 days after verification.

**Comment by ankitpatel7225** [comment]
> > I have same issue in my project with test unit in banner app . see my app.js if any kind of error in that ?
> > I m new in react native so please help me for that
> > import React, { Component } from 'react';
> > import {
> > Button,
> > StyleSheet,
> > View,
> > } from 'react-native';
> > import admob, { MaxAdContentRating, BannerAd, TestIds, BannerAdSize } from '@react-native-firebase/admob';
> > export default class App extends Component {
> > componentDidMount() {
> > admob()
> > .setRequestConfiguration({
> > // Update all future requests suitable for parental guidance
> > maxAdContentRating: MaxAdContentRating.G,
> > ```
> >     // Indicates that you want your content treated as child-directed for purposes of COPPA.
> >     tagForChildDirectedTreatment: true,
> > 
> >     // Indicates that you want the ad request to be handled in a
> >     // manner suitable for users under the age of consent.
> >     tagForUnderAgeOfConsent: true,
> >   })
> >   .then(() => {
> >     // Request config successfully set!
> >   });
> > ```
> > 
> > 
> > }
> > render() {
> > return (
> > 
> > <BannerAd
> > unitId={TestIds.BANNER}
> > size={BannerAdSize.SMART_BANNER}
> > requestOptions={{
> > requestNonPersonalizedAdsOnly: true,}}
> > onAdLoaded={() => {
> > console.log('Advert loaded');}}
> > onAdFailedToLoad={(error) => {
> > console.error('Advert failed to load: ', error);}}
> > />
> > <Button title="Click here"  onPress={() => {
> > ```
> >   }}></Button>
> >   </View>
> > );
> > ```
> > 
> > 
> > }
> > };
> > const styles = StyleSheet.create({
> > body: {
> > backgroundColor: '#fff',
> > }
> > });
> > same issue :
> > Advert failed to load:  [Error: [admob/error-code-no-fill] The ad request was successful, but no ad was returned due to lack of ad inventory.]
> > please any one help in firebase dashboard show my app was install in steam view but in app no ad load in real device
> 
> Please check this comment [#349 (comment)](https://github.com/sbugert/react-native-admob/issues/349#issuecomment-603538984)
> If your admob account is new you have to submit address for verification. Also wait for 2,3 days after verification.
thank for reply but it is necessary for test ad also ?

**Comment by ankitpatel7225** [comment]
Thanks for reply but it is also necessary in testad ?

**Comment by ankitpatel7225** [comment]
> > I have same issue in my project with test unit in banner app . see my app.js if any kind of error in that ?
> > I m new in react native so please help me for that
> > import React, { Component } from 'react';
> > import {
> > Button,
> > StyleSheet,
> > View,
> > } from 'react-native';
> > import admob, { MaxAdContentRating, BannerAd, TestIds, BannerAdSize } from '@react-native-firebase/admob';
> > export default class App extends Component {
> > componentDidMount() {
> > admob()
> > .setRequestConfiguration({
> > // Update all future requests suitable for parental guidance
> > maxAdContentRating: MaxAdContentRating.G,
> > ```
> >     // Indicates that you want your content treated as child-directed for purposes of COPPA.
> >     tagForChildDirectedTreatment: true,
> > 
> >     // Indicates that you want the ad request to be handled in a
> >     // manner suitable for users under the age of consent.
> >     tagForUnderAgeOfConsent: true,
> >   })
> >   .then(() => {
> >     // Request config successfully set!
> >   });
> > ```
> > 
> > 
> > }
> > render() {
> > return (
> > 
> > <BannerAd
> > unitId={TestIds.BANNER}
> > size={BannerAdSize.SMART_BANNER}
> > requestOptions={{
> > requestNonPersonalizedAdsOnly: true,}}
> > onAdLoaded={() => {
> > console.log('Advert loaded');}}
> > onAdFailedToLoad={(error) => {
> > console.error('Advert failed to load: ', error);}}
> > />
> > <Button title="Click here"  onPress={() => {
> > ```
> >   }}></Button>
> >   </View>
> > );
> > ```
> > 
> > 
> > }
> > };
> > const styles = StyleSheet.create({
> > body: {
> > backgroundColor: '#fff',
> > }
> > });
> > same issue :
> > Advert failed to load:  [Error: [admob/error-code-no-fill] The ad request was successful, but no ad was returned due to lack of ad inventory.]
> > please any one help in firebase dashboard show my app was install in steam view but in app no ad load in real device
> >
>> Please check this comment [#349 (comment)](https://github.com/sbugert/react-native-admob/issues/349#issuecomment-603538984)
> >If your admob account is new you have to submit address for verification. Also wait for 2,3 days after verification.

Thanks for reply but it is also necessary in testad  also? and this account is also used in android project previously

**Comment by sangolariel** [comment]
I wait for 3 days but it not running. It works well on IOS Simulator?

**Comment by Sanan4li** [comment]
> I wait for 3 days but it not running. It works well on IOS Simulator?

Please check this https://github.com/sbugert/react-native-admob/issues/349#issuecomment-603538984

**Comment by sangolariel** [comment]
> > I wait for 3 days but it not running. It works well on IOS Simulator?
> 
> Please check this [#349 (comment)](https://github.com/sbugert/react-native-admob/issues/349#issuecomment-603538984)

@Sanan4li I wait for 4 days. and the ads did not show for me. My card is verified. My APP has not released on App Store. I just run local and add a device for testing. the simulator works well on IOS but on a real device, it seems not to work. Should I continue to wait for show ads? I am not sure but I don't have an idea for now :(.

**Comment by jorgegvallejo** [comment]
I got this same "lack of inventory" error in production, while test ads and my ads show just fine in dev...

**Comment by sangolariel** [comment]
@jorgegvallejo I fixed this problem. you have to wait until the app be summited on OS and Android. Or you can add device test id on AdMod setting page. You can see the ad in dev because the device is considered as a device test.

**Comment by Eloquence01** [comment]
I am also facing the same issue though my app is yet to be submitted on play store pls can anyone help

**Comment by sangolariel** [comment]
@Eloquence01  you maybe need to wait for 3-4 days after release.

**Comment by Eloquence01** [comment]
I have been waiting for more than 3-4days now. What do I do pls??

**Comment by jorgegvallejo** [comment]
> I have been waiting for more than 3-4days now. What do I do pls??

@Eloquence01 were you able to solve it?

**Comment by Eloquence01** [comment]
No, my app was later disable and I have to cancel the account. Thanks for
your concern

**Comment by juniordnts** [comment]
I created the app and tested with the test ca-app-pub and it worked. But has passed 5 days now and I still getting the `The ad request was successful, but no ad was returned due to lack of ad inventory` error. How can I check if I already have the ads?

**Comment by Niranjan-Baur** [comment]
This fixes my issue ->>

I'm using a different package, `react-native-google-mobile-ads`, but I'm facing the same error while implementing ads from Google Ad Manager. I've checked most of the related articles and documentation, but I'm still unable to find the correct solution.

So, What does this error actually means?
It's simple, you don't have enough ads in your inventory to show ads. BUT BUT BUT most of the cases we have ads in the inventory but still its says `The ad request was successful, but no ad was returned due to lack of ad inventory`. 

So, may be the problem  with the `sizes` of the ads, ***means you have different sizes of ads in your inventory and you are trying to show different sizes of ad***. Which says "Inventory must be available for the banner sizes specified, otherwise a no-fill error will be sent to onAdFailedToLoad"

So double check that the sizes of your ad you are trying to display is present in your the inventory.

```
import { BannerAdSize, GAMBannerAd } from 'react-native-google-mobile-ads'

       <GAMBannerAd
            adSize="fullBanner"
            unitId={adUnitId}
            sizes={[BannerAdSize.LARGE_BANNER]} // pass the correct size(s) here
            onAdFailedToLoad={error => console.error(error)}
            onAppEvent={event => console.log(event.name, event.info)}
            onError={(e) => {
                   console.log(e)
            }}
       />
```

Here is all the different sizes of ads, ( please check the sizes and use it according to your needs )


```

export enum BannerAdSize {
  /**
   * Mobile Marketing Association (MMA) banner ad size (320x50 density-independent pixels).
   */
  BANNER = 'BANNER',

  /**
   * Interactive Advertising Bureau (IAB) full banner ad size (468x60 density-independent pixels).
   */
  FULL_BANNER = 'FULL_BANNER',

  /**
   * Large banner ad size (320x100 density-independent pixels).
   */
  LARGE_BANNER = 'LARGE_BANNER',

  /**
   * Interactive Advertising Bureau (IAB) leaderboard ad size (728x90 density-independent pixels).
   */
  LEADERBOARD = 'LEADERBOARD',

  /**
   * Interactive Advertising Bureau (IAB) medium rectangle ad size (300x250 density-independent pixels).
   */
  MEDIUM_RECTANGLE = 'MEDIUM_RECTANGLE',

  /**
   * @deprecated Use `ANCHORED_ADAPTIVE_BANNER` instead.
   */
  ADAPTIVE_BANNER = 'ADAPTIVE_BANNER',

  /**
   * A (next generation) dynamically sized banner that is full-width and auto-height.
   */
  ANCHORED_ADAPTIVE_BANNER = 'ANCHORED_ADAPTIVE_BANNER',

  /**
   * Inline adaptive banners are larger, taller banners compared to anchored adaptive banners. They are of variable height, and can be as tall as the device screen.
   * They are intended to be placed in scrolling content.
   */
  INLINE_ADAPTIVE_BANNER = 'INLINE_ADAPTIVE_BANNER',

  /**
   * IAB wide skyscraper ad size (160x600 density-independent pixels). This size is currently not supported by the Google Mobile Ads network; this is intended for mediation ad networks only.
   */
  WIDE_SKYSCRAPER = 'WIDE_SKYSCRAPER',
}
```

I hope will also works for you too.

**Comment by Rohitkhandukhairnar** [comment]
go in your device private DNS and select off

**Comment by AbhimanyuHK** [comment]
Refer: https://support.google.com/admob/thread/3494603/admob-error-codes-logs?hl=en

Why is  it Happening : Advertisers can target specific regions, platforms and user profiles based on business relevance, which can sometimes result in lower availability of Ads for a particular region or user profile. Error code suggests that the implementation is correct, and that the Ad Request was not filled because of lack of availability of a suitable Ad at that particular instant of time when an Ad Request was sent from the app.
