### ISSUE TITLE
Error: The ad request was successful, but no ad was returned due to lack of ad inventory.

### ISSUE THREAD

**Issue by tlweiii6465** [sbugert/react-native-admob#360]
Sample code is work fine but this is my result after using my own Admob code

Android show Error: The ad request was successful, but no ad was returned due to lack of ad inventory.

IOS show Error: No ads show

Did some body know why?

![screenshot_1537436282](https://user-images.githubusercontent.com/30071889/45810071-5940ce80-bcfc-11e8-819b-9e97c2f25ab7.png)

**Comment by marf** [comment]
Same error here

**Comment by koenpunt** [comment]
There's a `console.error` in the `handleAdFailedToLoad` that causes the red screen. Remove the handler and it should no longer give you the red screen.

**Comment by arirah** [comment]
i have removed handleAdFailedToLoad but still redbox screen coming .. It is working perfectly in emulator .. but when debug apk run in real device issue still there !! Any idea to hide this error screen in real device permanently

**Comment by PuriaGithub** [comment]
it may take sometimes until Adsense activate your ad unit

**Comment by arirah** [comment]
@PuriaGithub thanks for reply . i searched no where console.error() found .. :(

**Comment by Daneyl** [comment]
> @PuriaGithub thanks for reply . i searched no where console.error() found .. :(

Probably you are searching with brackets, just search console.error...
Actually it's in the prop that says "onAdFailedToLoad" ...

**Comment by buraksahin59** [comment]
I commented "onAdFailedToLoad" tag in AdMobBanner Code and I don't get anymore red screen.

Check my code:
```
<AdMobBanner
    adSize={adSize}
    width={adWidth}
    height={adHeight}
    adUnitID={
        Platform.OS === 'ios' ?
        "YOUR_IOS_AD_CODE":
        "YOUR_ANDROID_AD_CODE"
    }
    testDevices={[AdMobBanner.simulatorId]}
    // onAdFailedToLoad={error => console.error(error)}
/>
```
