### ISSUE TITLE
BUILD FAILED react-native-admob:verifyReleaseResources

### ISSUE THREAD

**Issue by Rushabhshroff** [sbugert/react-native-admob#361]
I get this error on running ./gradlew assembleRelease 
Error:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-admob:verifyReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

package.json
   ` "react": "16.5.0",
    "react-native": "0.57.0",
    "react-native-admob": "^2.0.0-beta.5",`

**Comment by celest67** [comment]
Same here

**Comment by myrsapp** [comment]
Same here. Any help?

**Comment by andylah** [comment]
go to node_module/react-native-admob/android
open build.gradle 
    compileSdkVersion 27
    buildToolsVersion "27.0.3"

**Comment by marhaupe** [comment]
This pull request solved that issue for me: https://github.com/sbugert/react-native-admob/pull/354.

**Comment by celest67** [comment]
@andylah solution did it for me. Thank you!

**Comment by gongsunzan** [comment]
@andylah  Your solution work. but i wondering what about  "targetSdkVersion 22"
Do i need to change to 26 also?

**Comment by marhaupe** [comment]
@gongsunzan @celest67 Can you please upvote #354 if it works for you too?

**Comment by breakerof** [comment]
i tried the solution from @andylah but than another problem is happening. 
```
../node_modules/react-native-admob/android/build.gradle: Error: All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 27.1.1, 26.1.0. Examples include com.android.support:animated-vector-drawable:27.1.1 and com.android.support:customtabs:26.1.0 [GradleCompatible]
```

i extended the build.gradle by adding other dependencies. 
```
dependencies {  
    compile 'com.facebook.react:react-native:+'  
    compile 'com.google.android.gms:play-services-ads:+'  
    implementation 'com.android.support:customtabs:27.1.1'  
    implementation 'com.android.support:animated-vector-drawable:27.1.1'  
    implementation 'com.android.support:support-media-compat:27.1.1'  
    implementation 'com.android.support:support-v4:27.1.1'  
}
```
after this i can build the apk

**Comment by pratigs** [comment]
@andylah Thank you. your solution is working.

**Comment by macci10** [comment]
Try this one, worked for me.
```
subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 27
                buildToolsVersion '27.0.3'
            }
        }
    }
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.android.support'
                    && !details.requested.name.contains('multidex') ) {
                details.useVersion "27.1.1"
            }
        }
    }
}
```

**Comment by losheredos** [comment]
Upgrading buildVersionTools to 28.0.3 solved my issue.

**Comment by abrillo2** [comment]
for me the following  worked

compileSdkVersion 28
buildToolsVersion "28.0.3"

**Comment by anhnt0212** [comment]
worked with me 

```
subprojects {
  project.configurations.all {
      afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 28
                buildToolsVersion '28.0.3'
            }
        }
    }
  }
}
```

**Comment by lfoliveir4** [comment]
> go to node_module/react-native-admob/android
> open build.gradle
> compileSdkVersion 27
> buildToolsVersion "27.0.3"

AOOOOWWW ILOVEDD!!!!!!!!

**Comment by adityajhordan** [comment]
Like @andylah said, we have to update node_module/react-native-admob/android/build.gradle

but in my case I have to update it to 

    compileSdkVersion 28
    buildToolsVersion "28.0.3"

This is the same value like my build.gradle project android
