### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by PuriaGithub** [sbugert/react-native-admob#363]
I used react-native-admob 2.0.0-beta.5 in older version of my app but now when I run react-native run-android it gave me  this error:

FAILURE: Build failed with an exception.
> Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED
D8: Program type already present: com.google.android.gms.common.api.internal.zzd

I test my other packages but when I link react-native-admob  it shows this error!!

**Comment by ltdangkhoa** [comment]
> compile 'com.google.android.gms:play-services-ads:15.0.0'

saved my life >.<

**Comment by marhaupe** [comment]
If you are like me and can't / don't want to edit your node_modules directly, you edit your app/build.gradle to look like this:
```groovy
dependencies {
    implementation (project(':react-native-admob')) {
        exclude group: 'com.google.android.gms', module: 'play-services-ads'
    }
    implementation 'com.google.android.gms:play-services-ads:15.0.1'
}
```
This is basically the same thing @ltdangkhoa suggests, but won't break your CI/CD pipelines.

**Comment by sanket-lathiya** [comment]
@PuriaGithub 
Thanks Man. I are the champ for the day for me.

**Comment by NySiya** [comment]
I have tried, but I still get the same error :(

**Comment by marhaupe** [comment]
@NySixa Which build.gradle did you edit for that?

**Comment by tuanlvEC** [comment]
@marhaupe Thank you so so much <3
