### ISSUE TITLE
Conflict with other packages

### ISSUE THREAD

**Issue by DVassilev** [sbugert/react-native-admob#37]
Hi,

When I add react-native-admob and try to build it I get a build error `com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzpq`. I think this is due to a clash with react-native-maps but I had a look at their dependancies and they both load separate play-services by specifying with gms:play-services-...

Any idea on how to resolve this?

Thanks

**Comment by sbugert** [comment]
Yes, that's a common issue.

Basically, you have to change one or the other build.gradle file.
In [react-native-maps](https://github.com/lelandrichardson/react-native-maps/blob/master/android/lib/build.gradle) version 9.2.0 is specified and [react-native-admob](https://github.com/sbugert/react-native-admob/blob/master/android/build.gradle) will always install the newest version which is 9.2.1 right now.
For example, changing it to `9.2.+` in react-native-maps would suffice.

I'm not really sure what's the best approach here. I guess it would be best if every react-native library using play services would just use the newest version (which could break things of course) or at least use `9.2.+`.

**Comment by DVassilev** [comment]
@sbugert really appreciate the speedy response, will change it now and see if it resolves it :)

**Comment by DVassilev** [comment]
@sbugert I just checked and all the libraries I'm using are using 8.4.0, is it OK to drop this down to that?

**Comment by sbugert** [comment]
Should be alright if you're okay with using that old version :)
Alternatively, send them PRs or change the files of those.

You can check the [release notes](https://developers.google.com/android/guides/releases) and decide if the changes have any impact on your app.

**Comment by DVassilev** [comment]
@sbugert thank you - also I'm getting an error `expected dynamic type 'double' but had type 'string'` when I try to use this line `AdMobInterstitial.requestAd(AdMobInterstitial.showAd);`. Any idea as to why?

**Comment by sbugert** [comment]
I'm not sure. Is this a warning or does it prevent the app from working at all?

**Comment by DVassilev** [comment]
@sbugert it was an error. Now I'm getting a different one that says showAd needs argument 0. Any ideas why?

**Comment by sbugert** [comment]
I've once seen this error but I don't remeber what I did to fix it. Maybe you could try deleting node_modules, reinstalling and linking the project again?

For the first error, [this issue](https://github.com/sbugert/react-native-admob/issues/31) maybe helps, I should really update the documentation but I forgot.

**Comment by studiobrain** [comment]
I am unfortunately seeing the same issue:
![screenshot_2016-07-31-23-57-03_1024](https://cloud.githubusercontent.com/assets/4606770/17283844/a8c011c6-577a-11e6-9eea-d45ec5f67590.png)

However my issue arrises when calling:
```
Java
@ReactMethod
  public void show(String message, int duration) {
    Toast.makeText(getReactApplicationContext(), message, duration).show();
  }
```
via the docs for setting up NativModules: https://facebook.github.io/react-native/docs/native-modules-android.html

Any insight into the solution, this is bringing all progress to a halt...
Thanks in advance!
