### ISSUE TITLE
App crash on startup

### ISSUE THREAD

**Issue by bhavik66** [sbugert/react-native-admob#370]
Here is an android log

    java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException: 
    
    ******************************************************************************
    * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
    * should follow the instructions here: https://goo.gl/fQ2neu to add a valid  *
    * App ID inside the AndroidManifest. Google Ad Manager publishers should     *
    * follow instructions here: https://goo.gl/h17b6x.                           *
    ******************************************************************************
    
    
        at android.app.ActivityThread.installProvider(ActivityThread.java:6242)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5805)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5722)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.IllegalStateException: 
    
    ******************************************************************************
    * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
    * should follow the instructions here: https://goo.gl/fQ2neu to add a valid  *
    * App ID inside the AndroidManifest. Google Ad Manager publishers should     *
    * follow instructions here: https://goo.gl/h17b6x.                           *
    ******************************************************************************
    
    
        at com.google.android.gms.internal.ads.zzmn.attachInfo(Unknown Source:17)
        at com.google.android.gms.ads.MobileAdsInitProvider.attachInfo(Unknown Source:3)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6239)

**Comment by Suraj-Tiwari** [comment]
please add this line in you `AndroidManifest.xml`

inside `<application>`

`<meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="[appid here]"/>`

**Comment by aizuddineismail** [comment]
Thanks @Suraj-Tiwari . It worked for me

**Comment by scaralfred** [comment]
It worked for me too, however i think its not sufficient to make the ad placement work again.
The app works fine, but no more banner are showing. I've been waiting for 2 days...  so i think there is something missing, not just a matter of time.

**Comment by bhavik66** [comment]
Thanks, @Suraj-Tiwari . It's work perfectly

**Comment by NySiya** [comment]
@scaralfred I get the same errors. Did you fix it yet?

**Comment by scaralfred** [comment]
Yes. It has just taken 3 days..... For the banner to show up again. After you add the app code on the manifest file, as mentioned above, the app will work again, you just need to wait up to 3 days to see the banner again :)

**Comment by NySiya** [comment]
@scaralfred Thank so much for this reply. But it takes almost 2 weeks now, my Banners still doesn't show up :(

**Comment by Suraj-Tiwari** [comment]
are you using correct id?

**Comment by NySiya** [comment]
@Suraj-Tiwari Only MREC show up, while other doesn't till now :(

**Comment by nqtuyen92** [comment]
You find grade.build in node_module/react-native-admob/android

change: gg service: + ====> gg service: 15.0.0

**Comment by grean** [comment]
@Suraj-Tiwari  workaround works fine :) Don't understand why this is not in the readme..

**Comment by prataprockerss** [comment]
> please add this line in your project `AndroidManifest.xml`
> 
> inside `<application>`
> 
> `<meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="[appid here]"/>`

It Works 
Just for reference that we have to copy **AppID** from **AdMob** Account. 
Thanks @Suraj-Tiwari

**Comment by magic990619** [comment]
> please add this line in your project `AndroidManifest.xml`
> 
> inside `<application>`
> 
> `<meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="[appid here]"/>`

Thanks, it works!

**Comment by goodhyun** [comment]
Fyi, Appid inside AndroidManifest.xml should has a '~' delimiter, not '/'.

**Comment by koenpunt** [comment]
I've added a link to the documentation in the Android section of the README

**Comment by olegzecamp** [comment]
I faced the same issue and none of these helped me. In my case the issue caused by "The ad unit ID must be set on InterstitialAd before loadAd is called" Error. 
So, be sure you call .requestAd() after .setAdUnitID(). And be sure that .setAdUnitID() incoming param is not either undefined or null or empty string or an object etc.

The problem is that react-native-admob doesn't pass any exceptions to the user and cause immediate crash in case of any problem.
Try to Use Android Device Monitor to get more information about your case.

**Comment by 1453alabanda** [comment]
> please add this line in your project `AndroidManifest.xml`
> 
> inside `<application>`
> 
> `<meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="[appid here]"/>`

Thank you @Suraj-Tiwari . It worked for me

**Comment by gre-dev** [comment]
@Suraj-Tiwari, I got this error after adding the `meta-data` tag to my `AndroidManifest.xml`'s `<application>`:

`Manifest merger failed : Attribute meta-data#com.google.android.gms.ads.APPLICATION_ID@value value=(ca-app-pub-5648488638118120~5124900918) from AndroidManifest.xml:13:75-129
	is also present at [:react-native-firebase_admob] AndroidManifest.xml:18:13-29 value=().
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:13:7-131 to override.`

**Comment by hkniyi** [comment]
IN
...\android\app\src\main\AndroidManifest.xml

CHANGE

```
<meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-3940256099942544/**********"/>
```
TO

```
<meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-3940256099942544~**********"/>
```

Change: / to ~
