### ISSUE TITLE
Compiled but APP stop just before the app start on Android

### ISSUE THREAD

**Issue by imran1992** [sbugert/react-native-admob#372]
I created the empty project to test admob working or not. I just put `react-native-admob` and `react-native`
```
"react": "16.6.0-alpha.8af6728",
"react-native": "0.57.3",
"react-native-admob": "^2.0.0-beta.5"
```
```
ext {
        buildToolsVersion = "27.0.3"
        minSdkVersion = 16
        compileSdkVersion = 27
        targetSdkVersion = 26
        supportLibVersion = "27.1.1"
    }
```
I even tried 
```
subprojects { subproject ->
    afterEvaluate{
        if((subproject.plugins.hasPlugin('android') || subproject.plugins.hasPlugin('android-library'))) {
            android {
                compileSdkVersion rootProject.ext.compileSdkVersion
                buildToolsVersion rootProject.ext.buildToolsVersion
            }
        }
    }
}
```
But still remain without any luck.

**Comment by imran1992** [comment]
> Did you try putting your admob app ID in AndroidManifest.xml?

There is no documentation of putting admob app ID in AndroidManifest.xml in this package.

**Comment by imran1992** [comment]
Well its same result.

**Comment by AbanoubNassem** [comment]
any luck with this issue?

**Comment by imran1992** [comment]
My Android Device: 
Android 8.1
//==============================================================
My Project Specification:
"react": "16.6.1",
"react-native": "0.57.5",
"react-native-admob": "^2.0.0-beta.5"
//==============================================================
My Project's Android Specs:(MyProject/android/build.gradle)
  ext {
        buildToolsVersion = "27.0.3"
        minSdkVersion = 16
        compileSdkVersion = 27
        targetSdkVersion = 26
        supportLibVersion = "27.1.1"
    }
//==============================================================
Admob's Android Specs:(react-native-admob/android/src/build.gradle)
compileSdkVersion 23
buildToolsVersion "23.0.1"
 defaultConfig {
   minSdkVersion 16
   targetSdkVersion 22
 }
dependencies { 
compile 'com.facebook.react:react-native:+' 
compile 'com.google.android.gms:play-services-ads:16.0.0' 
            }

Its Running Good But didnt test it with real ads yet

**Comment by imran1992** [comment]
For Now I am Closing It..
