### ISSUE TITLE
invariant violation requirenativecomponent: 'rngadbannerview' was not found in the uimanager

### ISSUE THREAD

**Issue by SaGaR1084** [sbugert/react-native-admob#382]

**Comment by SagaRPate** [comment]
"react-native": "0.57.5",
    "react-native-admob": "^2.0.0-beta.5"

`import React, { Component } from 'react';
import {
    Platform,
    StyleSheet,
    Text,
    View,
    ScrollView,
    Dimensions,
    TouchableOpacity,
    Image,
    StatusBar,
} from 'react-native';

import { 
    AdMobBanner, 
    AdMobInterstitial, 
    PublisherBanner,
    AdMobRewarded
} from 'react-native-admob'

class Home extends Component {
    render() {
        return (
            <View style={{flex:1}}>  
                <StatusBar
                    backgroundColor="#002171"
                    barStyle="light-content"
                />
                <View style={styles.header}>
                    <Text style={styles.headerTitle}>
                        Home
                    </Text>
                </View>
                <ScrollView style={[styles.container, {flex:1}]} >
                    <View style={styles.mainViewAdd}>
                        <Text style={styles.adTitleText} >
                            Demo Ad
                        </Text>
                        <AdMobBanner
                            bannerSize="fullBanner"
                            adUnitID="ca-app-pub-5852753270075965/3160433581"
                            testDeviceID="EMULATOR"
                            didFailToReceiveAdWithError={this.bannerError} />
                    </View>
                </ScrollView>
            </View>
        );
    }
}


export default Home;

const styles = StyleSheet.create({
    header:{
        width:'100%', 
        height:60, 
        justifyContent:'center', 
        alignSelf:'center', 
        backgroundColor:'#0d47a1',
    },
    headerTitle:{
        alignSelf:'center', 
        color:'#fff', 
        fontSize:25, 
        fontFamily: 'Muli-Bold',
    },  
    container: {
        flex: 1,
        // justifyContent: 'center',
        // alignItems: 'center',
        backgroundColor: '#F5FCFF',
    },
    mainViewAdd:{
        width:'98%', 
        paddingHorizontal:20, 
        paddingVertical:10, 
        alignSelf:'center', 
        marginTop:20, 
        justifyContent:'center', 
        borderColor:'grey', 
        borderWidth:1,
        borderRadius:5,
    },
    adTitleText:{
        // marginLeft:10, 
        fontSize:16, 
        fontFamily: 'Muli-Bold',
    },
    AdView:{
        justifyContent:'center', 
        alignSelf:'center', 
        alignItems:'center'
    },
});`

**Comment by claudio1091** [comment]
Same issue here, but:
`"react-native": "0.57.3"`

**Comment by sergiotucano** [comment]
Same issue : 
"react-native": "0.57.5",
"react-native-admob": "^2.0.0-beta.5"

**Comment by manojkumawat003** [comment]
It seem you have not link admob. `Try react-native link react-native-admob`

**Comment by manojkumawat003** [comment]
#SagaRPate  This react-native-admob library does n't have full documentation. I spend many days to solve many errors in this library and got solution.  
Have you completed admob instructions - 
[https://developers.google.com/admob/android/quick-start?hl=en-US#import_the_mobile_ads_sdk](url)

Follow the above three instructions.
Leave- Initialize MobileAds option.

Then try react-native-admob library.

Send me error if you get any.

**Comment by SagaRPate** [comment]
> #SagaRPate This react-native-admob library does n't have full documentation. I spend many days to solve many errors in this library and got solution.
> Have you completed admob instructions -
> https://developers.google.com/admob/android/quick-start?hl=en-US#import_the_mobile_ads_sdk
> 
> Follow the above three instructions.
> Leave- Initialize MobileAds option.
> 
> Then try react-native-admob library.
> 
> Send me error if you get any.

i am try this solution but it's not working

**Comment by azsidhu** [comment]
react-native-admob is linked, I've verified, still getting the same error. Any solution? @manojkumawat003

**Comment by lucaspiressimao** [comment]
I got the same error...

**Comment by SaGaR1084** [comment]
> it's working Good in this Version of react-native

>    "react": "16.8.3",
>    "react-native": "0.59.9",
>    "react-native-admob": "^2.0.0-beta.5",

**Comment by SaGaR1084** [comment]
> Task :react-native-admob:compileReleaseJavaWithJavac FAILED
/Users/sagar/My App/RN Code Helper/RNCodeHepler/node_modules/react-native-admob/android/src/main/java/com/sbugert/rnadmob/RNAdMobInterst
itialAdModule.java:5: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;

**Comment by kostiantyn-solianyk** [comment]
hello from 2020... same here

**Comment by fernandobonfimandrade** [comment]
hello from 2020... same here 2
