### ISSUE TITLE
ERROR_CODE_NO_FILL Warning

### ISSUE THREAD

**Issue by nakraniyogesh100** [sbugert/react-native-admob#384]
my react-native-admob build.gradle file below:

apply plugin: 'com.android.library'

android {
    compileSdkVersion 27
    buildToolsVersion "27.0.3"

    defaultConfig {
        minSdkVersion 19
        targetSdkVersion 26
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile 'com.facebook.react:react-native:+'
    compile 'com.google.android.gms:play-services-ads:11.0.1'

}

when i try to load live ad device fire ERROR_CODE_NO_FILL warning but test ad id complete working.

**Comment by manojkumawat003** [comment]
try this- `implementation 'com.google.android.gms:play-services-ads:17.1.1'`

**Comment by manojkumawat003** [comment]
are your ads active? 
Can you use app after dismiss the error?

**Comment by Jiang00** [comment]
Is it solved?

**Comment by nakraniyogesh100** [comment]
When you build debug apk file ad not show but in release apk ad show.

This might have one solution for temporary.

Thanks...
