### ISSUE TITLE
can`t initialize correctly on Android

### ISSUE THREAD

**Issue by Viktor19931** [sbugert/react-native-admob#398]
Hello Everyone! I had issue to correctly initialize adMob when app is starting. Please help me correctly initialize it as now it just stopping. Thanks in advance !
That is mine MainActivity.java 

`import com.facebook.react.ReactActivity;
import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.ReactRootView;
import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;
import com.google.android.gms.ads.MobileAds;

public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "Tickets";
    }

    @Override
    protected ReactActivityDelegate createReactActivityDelegate() {
      return new ReactActivityDelegate(this, getMainComponentName()) {
        @Override
        protected ReactRootView createRootView() {
         return new RNGestureHandlerEnabledRootView(MainActivity.this);
        }
      };
    }
}`

in [documentation](https://developers.google.com/admob/android/quick-start) said I have to put at next code
`
import com.google.android.gms.ads.MobileAds;

public class MainActivity extends AppCompatActivity {
    ...
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        // Sample AdMob app ID: ca-app-pub-3940256099942544~3347511713
        MobileAds.initialize(this, "YOUR_ADMOB_APP_ID");
    }
    ...
}`

**Comment by koenpunt** [comment]
You have to add your app id to the `AndroidManifest.xml`: https://developers.google.com/admob/android/quick-start#update_your_androidmanifestxml
