### ISSUE TITLE
No Ads are appearing

### ISSUE THREAD

**Issue by KunalKapadia** [sbugert/react-native-admob#40]
Hi @sbugert 

I am using RN v0.30 and React v15.2.1.

I did the following to integrate react-native-admob into my app:

1. `rnpm install react-native-admob`

2.
```
import { AdMobBanner } from 'react-native-admob';

class Relationship extends Component {
  constructor (props) {
    super(props);
    this.state = {
      isLoading: false,
      modalVisible: false,
      error: ''
    }

    this.bannerError = this.bannerError.bind(this);
    this.didReceiveAd = this.didReceiveAd.bind(this);
  }

  bannerError(e) {
    console.log('banner error', e)
  }

  didReceiveAd(ad) {
    console.log('ad received', ad)
  }

  render () {
    return (
      <View style={styles.container}>
        <AdMobBanner
          bannerSize="banner"
          adUnitID="ca-app-pub-3940256099942544/2934735716"
          testDeviceID="EMULATOR"
          adViewDidReceiveAd={this.didReceiveAd}
          didFailToReceiveAdWithError={this.bannerError} />
      </View>
    );
  }
}
```

Can you please let me know if I am doing something wrong ?

**Comment by sbugert** [comment]
Any errors or warnings? iOS or Android?

I haven't tested react-native 0.30.0 yet, but your code works on 0.29.2. So there's either a linking problem or there's a breaking change in 0.30.0.

**Comment by KunalKapadia** [comment]
@sbugert Sorry, Its Android.

No errors and warning and none of `bannerError` or `didReceiveAd` is getting called.

**Comment by sbugert** [comment]
So, I tested your code on 0.30.0 and it works.
Maybe try a fresh project or deleting node_modules and reinstalling?

Also, I used `react-native link` after installing with npm. rnpm was recently merged into react-native afaik. This should not make any difference though.

**Comment by diogopalhais** [comment]
@KunalKapadia  check this https://github.com/sbugert/react-native-admob/issues/45#issuecomment-241058644
