### ISSUE TITLE
64 bit native library

### ISSUE THREAD

**Issue by malonguwa** [sbugert/react-native-admob#403]
Google Play will start to ONLY accept 64-bit version android App if there is any native code in the project after Aug 2019:
https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html

Does this react-native-admob lib is in 32-bit? or 64-bit? I am still new to the android, the react native 0.58 will included the support of 64-bit version of react native app, does this react-native-admob will be able to provide 64-bit version, so we can able to keep using this lib after 2019 Aug with new Google Play Policy?

**Comment by koenpunt** [comment]
The Google-Mobile-Ads SDK doesn't ship with this library, you have to add that separately. But I assume Google will make sure it's going to be compatible.
