### ISSUE TITLE
Andorid  " FAILURE: Build failed with an exception."

### ISSUE THREAD

**Issue by Kishan009** [sbugert/react-native-admob#410]
* What went wrong:
A problem occurred configuring project ':RNAdMob'.
> Failed to install the following Android SDK packages as some licences have not been accepted.
     platforms;android-23 Android SDK Platform 23
  To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
  Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html

  Using Android SDK: C:\Users\HP\AppData\Local\Android\Sdk

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by Momazo7u7** [comment]
that's a sdk problem.

Go to your android_home folder (the one where you have the android sdks, build tools, etc) , in your case it seems like it is C:\Users\HP\AppData\Local\Android\Sdk . then from there go to tools//bin , and there open a console with shift+right click => open coman window here .  and type "sdkmanager --licenses" (without the quotes) and type "y" every time asked.

Source https://stackoverflow.com/questions/39760172/you-have-not-accepted-the-license-agreements-of-the-following-sdk-components

**Comment by koenpunt** [comment]
@LiteCatDev's comment should fix it.
