### ISSUE TITLE
Accessing view manager configs directly off UIManager via UIManager['RNGADBannerView'] is no longer supported

### ISSUE THREAD

**Issue by octopusbaba** [sbugert/react-native-admob#420]
Will it be updated ? 

or we can update it somewhere inside native-modules ?

Help !

![screenshot_1551248666](https://user-images.githubusercontent.com/4969242/53470095-af265900-3a88-11e9-8472-2e462342ba06.png)

**Comment by PedroFonseca17** [comment]
I need to know about this too !

**Comment by DoWhileGeek** [comment]
I just started using this lib, and this is popping up for me as well.

**Comment by flagman5** [comment]
All,

I've fixed this issue on my environment.

1. Go to node_modules/react-native-admob folder
2. In the file RNAdMobBanner.js, go to line 30
3. Change to UIManager.getViewManagerConfig('RNGADBannerView').Commands.loadBanner,

Re-build and reload.

Note, I am not using PublisherBanner but if you do, then you also have to change it in RNPublisherBanner.js, line 31

**Comment by DoWhileGeek** [comment]
I wish we could get this merged into master

**Comment by octopusbaba** [comment]
I completely ditched off this library and used from firebase & saved my life :) :)

**Comment by baselbj** [comment]
> I completely ditched off this library and used from firebase & saved my life :) :)

can you till me how?

**Comment by octopusbaba** [comment]
@baselbj  it's simple uninstall react-native-admob and following the instruction to use firebase admob.

**Comment by baselbj** [comment]
@octopusbaba I am now using  firebase admob. for me I prefer simple library but unfortunately this library has many issues

**Comment by davidcort** [comment]
I use PublisherBanner and the @flagman5 works for me. Thanks :)

**Comment by mikebouwmans** [comment]
I just copied the RNAdMobBanner.js to an Overrides folder in my src/ and dus did 
`import AdMobBanner from "../Overrides/RNAdMobBanner";`
in stead of `import {AdMobBanner} from "react-native-admob";`

Code can be found here: 
(I just changed the line 30 code @flagman5 suggested and changed `import { createErrorFromErrorData } from './utils;` 
to
`import { createErrorFromErrorData } from 'react-native-admob/utils';
`
