### ISSUE TITLE
Not working with react-native-account-kit

### ISSUE THREAD

**Issue by crsgarcias** [sbugert/react-native-admob#422]
Hi, 

I was using this library in my app, Bu I update mi RN to 0.57.7 and I  added React-native-account-kit in my app, but after this. My app not work

![image](https://user-images.githubusercontent.com/25749111/53605383-fc83f280-3b7c-11e9-9a8f-206c80b38356.png)

![image](https://user-images.githubusercontent.com/25749111/53605392-01e13d00-3b7d-11e9-9293-7fc3b7457d60.png)

I tried all to run, but I can´t get it

**Comment by tmjordan** [comment]
@crsgarcias add this line to your android/app/buil.gradle defaultConfig section:
```
multiDexEnabled true
```

example: 
```
defaultConfig {
        applicationId "you_app_id"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        vectorDrawables.useSupportLibrary = true
        multiDexEnabled true
    }
```

**Comment by crsgarcias** [comment]
@tmjordan  Thank you! I put the configuration in my build.gradle, build

But, now my app is crashing, I´m checking this error

![image](https://user-images.githubusercontent.com/25749111/53645490-99d33b00-3bfe-11e9-9654-241d7698b4c2.png)

**Comment by crsgarcias** [comment]
I can get the error with logcat, and it is:

E/AndroidRuntime( 4147): Process: com.ups, PID: 4147

E/AndroidRuntime( 4147): java.lang.RuntimeException: Unable to get provider com.facebook.accountkit.internal.AccountKitInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.facebook.accountkit.internal.AccountKitInitProvider" on path: DexPathList[[zip file "/data/app/com.ups-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.ups-2, /system/lib]]

E/AndroidRuntime( 4147): 	at android.app.ActivityThread.installProvider(ActivityThread.java:4777)

E/AndroidRuntime( 4147): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4369)

E/AndroidRuntime( 4147): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4309)

E/AndroidRuntime( 4147): 	at android.app.ActivityThread.access$1500(ActivityThread.java:135)

E/AndroidRuntime( 4147): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)

E/AndroidRuntime( 4147): 	at android.os.Handler.dispatchMessage(Handler.java:102)

E/AndroidRuntime( 4147): 	at android.os.Looper.loop(Looper.java:136)

E/AndroidRuntime( 4147): 	at android.app.ActivityThread.main(ActivityThread.java:5001)

E/AndroidRuntime( 4147): 	at java.lang.reflect.Method.invokeNative(Native Method)

E/AndroidRuntime( 4147): 	at java.lang.reflect.Method.invoke(Method.java:515)

E/AndroidRuntime( 4147): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)

E/AndroidRuntime( 4147): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)

E/AndroidRuntime( 4147): 	at dalvik.system.NativeStart.main(Native Method)

E/AndroidRuntime( 4147): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.accountkit.internal.AccountKitInitProvider" on path: DexPathList[[zip file "/data/app/com.ups-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.ups-2, /system/lib]]

E/AndroidRuntime( 4147): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)

E/AndroidRuntime( 4147): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)

E/AndroidRuntime( 4147): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)

E/AndroidRuntime( 4147): 	at android.app.ActivityThread.installProvider(ActivityThread.java:4762)

E/AndroidRuntime( 4147): 	... 12 more

W/ActivityManager(  604):   Force finishing activity com.ups/.MainActivity

W/InputMethodManagerService(  604): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@52a7cf8c attribute=null, token = android.os.BinderProxy@52a26c64

D/MobileDataStateTracker(  604): default: setPolicyDataEnable(enabled=true)

W/ActivityManager(  604): Activity pause timeout for ActivityRecord{52c69f10 u0 com.ups/.MainActivity t21 f}

D/MobileDataStateTracker(  604): default: setPolicyDataEnable(enabled=true)

D/MobileDataStateTracker(  604): default: setPolicyDataEnable(enabled=true)

D/MobileDataStateTracker(  604): default: setPolicyDataEnable(enabled=true)

D/MobileDataStateTracker(  604): default: setPolicyDataEnable(enabled=true)

D/MobileDataStateTracker(  604): default: setPolicyDataEnable(enabled=true)

D/MobileDataStateTracker(  604): default: setPolicyDataEnable(enabled=true)

D/MobileDataStateTracker(  604): default: setPolicyDataEnable(enabled=true)

D/MobileDataStateTracker(  604): default: setPolicyDataEnable(enabled=true)

I/Process ( 4147): Sending signal. PID: 4147 SIG: 9

D/MobileDataStateTracker(  604): default: setPolicyDataEnable(enabled=true)

I/ActivityManager(  604): Process com.ups (pid 4147) has died.

D/MobileDataStateTracker(  604): default: setPolicyDataEnable(enabled=true)

W/InputMethodManagerService(  604): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@52b33d04 attribute=null, token = android.os.BinderProxy@52a26c64

**Comment by crsgarcias** [comment]
Finally after a long time I found the solution

In my android/app/build.gradle add         multiDexEnabled true like this

```
defaultConfig {
        applicationId "com.ups"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 11
        versionName "1.0.11"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        multiDexEnabled true
    }
```

```
dependencies {
implementation 'com.android.support:multidex:1.0.3'
...
}
```

In my MainApplication.java

import android.support.multidex.MultiDexApplication;
import android.support.multidex.MultiDex;
import android.content.Context;

```
public class MainApplication extends Application implements ShareApplication, ReactApplication {
...
@Override
  protected void attachBaseContext(Context base) {
    super.attachBaseContext(base);
    MultiDex.install(this);
  }
...
}
```

And it works with React native AdMob!
