### ISSUE TITLE
This library is dead, and you should not install it for production

### ISSUE THREAD

**Issue by LiteCatDev** [sbugert/react-native-admob#423]
Welp i had hope that sbugert would come back but it seems like he is gone , and he didn' even named some contributors to the library to accept some (good) PR's .

It's about time we start to use re-firebase module , wich sucks because it's not as lightweight as this module .
In case you can't build and you REALLY want to use this library you can use a simple fork that i did 
https://github.com/Momazo7u7/react-native-admob 
it changes just the android configuration to build properly, and removes that annoying yellow warning . Tested in RN 0.58  and RN 0.59-rc3 

sbugert please come back . we need some pr's to be merged :u5272: 

for a migration guide you can use this post
https://dev-yakuza.github.io/en/react-native/react-native-firebase-admob/

RN firebase will also export the admob module to an individual one, but i don't know when. You can check the status here
https://github.com/invertase/react-native-firebase#firebase-modules

**Comment by mdekrey** [comment]
@koenpunt - is this accurate?

For everyone else, see discussion in #399.

**Comment by quytang** [comment]
:| just asked a question [here](https://github.com/sbugert/react-native-admob/issues/425). Maybe I need to fork and try to do it myself 😂

**Comment by flashman2** [comment]
Thanks a lot to Momazo7u7!

**Comment by aprilmintacpineda** [comment]
@LiteCatDev I guess maintaining your fork is the only option left, otherwise @sbugert can come back and add maintainers to the project. I'm not an expert in native but I'd be happy to help :-)

**Comment by LiteCatDev** [comment]
YES, FINALLY another module .

the firebase admob module is now a standalone.!!! 

https://github.com/invertase/react-native-firebase/tree/master/packages/admob

**Comment by ursNj** [comment]
@LiteCatDev this library is coming up with 2.0 and there is a pretty good develpment is happening, please be patient it is a good library...
