### ISSUE TITLE
It seems like this lib is dead, try this one

### ISSUE THREAD

**Issue by Albert0405** [sbugert/react-native-admob#427]
`https://github.com/expo/expo/tree/master/packages/expo-ads-admob`

I'm currently using this lib with the latest react-native version, its very similar to this library but with continuous updates, the only thing you need to do is their painful configuration of `react-native-unimodules`. You need to install that first before you can use any expo libraries in your react-native init projects. 

Give it a try if this library gives you headache because of bugs

**Comment by kabus202** [comment]
@Albert0405  do you have an example repo of usage?

**Comment by Albert0405** [comment]
here https://github.com/deadcoder0904/expo-google-admob/blob/master/App.js

**Comment by kabus202** [comment]
@Albert0405  ty

**Comment by tinmar33** [comment]
Can we use this lib without expo ?

**Comment by Albert0405** [comment]
@tinmar33  yes, but you need to install unimodules in order to use it native projects

**Comment by kesha-antonov** [comment]
@Albert0405 Thanks
I migrated to expo

**Comment by koenpunt** [comment]
I've opened a PR to bring this library up to date with the latest version of React Native, which brings support for CocoaPods and Android X: #472
