### ISSUE TITLE
unknown:ViewManagerPropertyUpdater

### ISSUE THREAD

**Issue by neilspatel** [sbugert/react-native-admob#44]
I am not sure if this is causing my problems with getting mediation for inMobi and MobFox to work but I am getting the following error in the logcat along with a host of similar errors to facebook.react.views. The regular admob ads are working however.

Could not find generated setter for class com.sbugert.rnadmob.RNAdMobBannerViewManager

I am using the following dependencies. 

  "dependencies": {
    "react": "15.2.1",
    "react-native": "^0.30.0",
    "react-native-admob": "^1.1.5"
}

**Comment by sbugert** [comment]
Sorry for the late reply!
Unfortunately, I don't have any experience with mediation networks.

Have you already got it working?

**Comment by neilspatel** [comment]
No worries!

I did get it working. I ended up reverting back to react-native 0.29. I am not if that did it or not but it seems ok now.
