### ISSUE TITLE
What about androidx migration ?

### ISSUE THREAD

**Issue by grean** [sbugert/react-native-admob#446]
Recently you can't compile anymore due to googles androidx update : https://github.com/facebook/react-native/issues/25294
When do you think it will be done ?

**Comment by obsidianart** [comment]
@grean I guess this lib has been abandoned long ago, I'm trying to switch to firebase admob...

**Comment by lachtos** [comment]
What I did was change dependency in build.gradle of react-native-admob to
`ompile 'com.google.android.gms:play-services-ads:17.2.1'`
but that's obviously just a hot fix and I guess we should move on from this package...

**Comment by grean** [comment]
It's working now :) thx
For maintaining purposes when packages seems to be abandoned, i do that : 
1. Fork this package 
2. Fix the problem on my fork and push
3. Modify my package.json like that : git+https://git@github.com/grean/react-native-admob

**Comment by obsidianart** [comment]
switching to firebase with ADmob took around 2 and half hours. The main difference is that firebase doesn't return a promise to wait for when you request an AD. for the rest is pretty much the same.

**Comment by MTTenterprise** [comment]
it looks like the repo is not maintained anymore I have forked the project and added support for android X. 

just add this in package json "react-native-admob":"git+https://github.com/MTTenterprise/react-native-admob"

and you should be good to go

**Comment by IacoCesar** [comment]
[#448 ](https://github.com/sbugert/react-native-admob/issues/448#issuecomment-504807659)

**Comment by alvaro1728** [comment]
> it looks like the repo is not maintained anymore I have forked the project and added support for android X.
> 
> just add this in package json "react-native-admob":"git+https://github.com/MTTenterprise/react-native-admob"
> 
> and you should be good to go

Hi @MTTenterprise, is there anything else I need to do?  I'm getting an error with this line:

    import {AdMobBanner} from 'react-native-admob';
```
Invariant Violation: requireNativeComponent: "RNGADBannerView" was not found in the UIManager.

This error is located at:
    in RNGADBannerView (at RNAdMobBanner.js:51)
    in AdMobBanner (at AdBanner.js:19)
    in RCTView (at View.js:35)
    in View (at AdBanner.js:18)
    in AdBanner (at ShareDialog.js:117)
    in RCTView (at View.js:35)
    in View (at ShareDialog.js:114)
    ...
```

**Comment by koenpunt** [comment]
I've opened a PR to bring this library up to date with the latest version of React Native, and thus bringing support for CocoaPods and support for Android X: #472

**Comment by koenpunt** [comment]
The latest beta (`v2.0.0-beta.6`) should build fine with the latest version of React Native (and thus should support AndroidX).
