### ISSUE TITLE
Android Build failed after install rect-native-admob version 1.3.2 or 2.0.0-5.beta in react native version 0.59.8

### ISSUE THREAD

**Issue by tlweiii6465** [sbugert/react-native-admob#450]
version react native 0.59.8

1. error for rect-native-admob 1.3.2

Users/apple/Desktop/own_project/node_modules/react-native-admob/android/src/main/java/com/sbugert/rnadmob/RNAdMobRewardedVideoAdModule.java:20: error: RNAdMobRewardedVi
deoAdModule is not abstract and does not override abstract method onRewardedVideoCompleted() in RewardedVideoAdListener
public class RNAdMobRewardedVideoAdModule extends ReactContextBaseJavaModule implements RewardedVideoAdListener {
       ^
1 error
---------------------------------
2. error for rect-native-admob 2.0.0-5.beta

Users/apple/Desktop/own_project/4d/4dviewer/android/app/src/debug/AndroidManifest.xml:22:18-91 Error:
        Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
        is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
        Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:7:5-117 to override.

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.
--------------------------------
2.5 error after added tools:replace="android:appComponentFactory at application,
xmlns:tools="http://schemas.android.com/tools" at android manifest header

/Users/apple/Desktop/own_project/4d/4dviewer/android/app/src/main/AndroidManifest.xml:12:5-58:19 Error:
        tools:replace specified at line:12 for attribute android:appComponentFactory, but no new value specified
/Users/apple/Desktop/own_project/4d/4dviewer/android/app/src/main/AndroidManifest.xml Error:
        Validation failed, exiting

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.

---------------------------------

Is anyone know how to fix this issue? Thank.

**Comment by zhuhengtan** [comment]
MARK. Ive got this problem too.
According to some solutions on the internet, this error is cause by androidx.
[watch this](https://blog.csdn.net/zhou906767220/article/details/87934547)
[and this](https://blog.csdn.net/qq_34224268/article/details/83861897)
And the second link fix this problem but in my App there comes another problem😅

**Comment by ank26oct** [comment]
https://github.com/sbugert/react-native-admob/issues/452#issuecomment-506705969
