### ISSUE TITLE
[!] Invalid `Podfile` file: no implicit conversion of nil into String.

### ISSUE THREAD

**Issue by DimaTrue** [sbugert/react-native-admob#455]
Hi, In React-native v. 0.60.0 I run 
npm i --save react-native-admob@next
after that 
cd ios
pod install 
and then i received next: 
[!] Invalid `Podfile` file: no implicit conversion of nil into String.

 #  from /Users/user/Documents/Projects/ProductsApp/ios/Podfile:36
 #  -------------------------------------------
 #  
 >    use_native_modules!
 #  end
 #  -------------------------------------------

when I run 

npm uninstall react-native-admob

It's ok. What is going on? How can I fix that?

**Comment by koenpunt** [comment]
The currently released version has no support for CocoaPods, but I've opened a PR to bring this library up to date with the latest version of React Native, and thus bringing support for CocoaPods: #472
