### ISSUE TITLE
it seems that no one helps

### ISSUE THREAD

**Issue by gunduzcihat** [sbugert/react-native-admob#457]
no one answer the questions.

**Comment by MatheusAlvesA** [comment]
Unfortunately this library is no longer maintained.
But check this: https://github.com/sbugert/react-native-admob/issues/458

**Comment by koenpunt** [comment]
I think this is because most of the problems people have are user errors (e.g. not setting up admob correctly). Issues regarding not working with the latest versions of React Native are being addressed here: #472
