### ISSUE TITLE
A new solution for Android Developers!

### ISSUE THREAD

**Issue by MatheusAlvesA** [sbugert/react-native-admob#458]
Unfortunately this library is no longer maintained by the creator. But.

I just released the 1.0.0 version of my own react-native library that includes AdMob modules.
My code is based on this lib, but i made some refactoring, bug fixes and adaptations for Androidx libs and new react-native framework(0.60.3).

My library is for Android Only, so it is not a solution for IOS :/

If you are developing a react native App for Android Only, check my lib:
https://github.com/MatheusAlvesA/react-native-androide/

**Comment by lotosbin** [comment]
#399 
#462

**Comment by smakosh** [comment]
Your fork doesn't work for me, using `RN 0.60.5`

**Comment by koenpunt** [comment]
Issues regarding new versions of React Native (and thus AndroidX) are being addressed with #472
