### ISSUE TITLE
More than one test device 

### ISSUE THREAD

**Issue by vu-dang** [sbugert/react-native-admob#46]
Please support more than one test device.  Thanks

**Comment by sbugert** [comment]
Hi vu-dang,

This is a feature I hope I can add soon and I see how this is an important feature. I hope I can find some way to make it not break the old api.

**Comment by ndbroadbent** [comment]
I opened a PR to support multiple test IDs: #90

**Comment by eranbes** [comment]
Can you please fix the issue?

**Comment by Tiendq** [comment]
@sbugert Could you look at @ndbroad

**Comment by koenpunt** [comment]
In version 2 it's possible to set multiple test devices using the `testDevices` property. See the README on how to install this version, and check [the release notes](https://github.com/sbugert/react-native-admob/releases/tag/v2.0.0-beta.1) to see what changed.
