### ISSUE TITLE
"RNGADBannerView" was not found in the UIManager

### ISSUE THREAD

**Issue by jothikannan** [sbugert/react-native-admob#460]
Getting "RNGADBannerView" was not found in the UIManager error in RN "react-native": "0.60.4",

I have followed all the solutions given in the older issues, but still, I am getting this error, I believe that the issue arises again with >0.60. Please, someone, help me with
<img width="376" alt="Screen Shot 2019-08-03 at 6 02 11 PM" src="https://user-images.githubusercontent.com/4100047/62412369-f3f98180-b61e-11e9-9891-f4668259b80c.png">
 this

**Comment by adrianchancy** [comment]
I face the same issue. No such issue in Android.

**Comment by jonatasnardi** [comment]
Did you solve this issue? I'm having the same problem :/

**Comment by jonatasnardi** [comment]
@jothikannan @adrianchancy 
I solved this issue linking manually on XCode. Follow these steps:

1) Open XCode e open this section below:

<img width="277" alt="Screen Shot 2019-08-17 at 18 52 07" src="https://user-images.githubusercontent.com/20306168/63217634-29729480-c120-11e9-99c9-d4ab705f6b22.png">

2) Drag and drop the files inside folder `node_modules/react-native-admob/ios` to this section above (except file RNAdMobManager.xcodeproj)

<img width="220" alt="Screen Shot 2019-08-17 at 18 54 37" src="https://user-images.githubusercontent.com/20306168/63217649-7f473c80-c120-11e9-8251-631ac9e0b553.png">

3) run `react-native run-ios`

Then it's working for me.

**Comment by adrianchancy** [comment]
thanks @jonatasnardi 
Anyway, as I could not solve it, I shifted to use react-native-firebase

**Comment by gidox** [comment]
> @jothikannan @adrianchancy
> I solved this issue linking manually on XCode. Follow these steps:
> 
> 1. Open XCode e open this section below:
> 
> <img alt="Screen Shot 2019-08-17 at 18 52 07" width="277" src="https://user-images.githubusercontent.com/20306168/63217634-29729480-c120-11e9-99c9-d4ab705f6b22.png">
> 
> 1. Drag and drop the files inside folder `node_modules/react-native-admob/ios` to this section above (except file RNAdMobManager.xcodeproj)
> 
> <img alt="Screen Shot 2019-08-17 at 18 54 37" width="220" src="https://user-images.githubusercontent.com/20306168/63217649-7f473c80-c120-11e9-8251-631ac9e0b553.png">
> 
> 1. run `react-native run-ios`
> 
> Then it's working for me.

this works for me

**Comment by koenpunt** [comment]
I've pushed a new beta version (`v2.0.0-beta.6`) that includes a `podspec`, so the autolinking functionality should now work, without manually adding the files to the Xcode project.

**Comment by thedevxen** [comment]
> thanks @jonatasnardi
> Anyway, as I could not solve it, I shifted to use react-native-firebase

does react-native-firebase provide admob?

**Comment by thedevxen** [comment]
> I've pushed a new beta version (`v2.0.0-beta.6`) that includes a `podspec`, so the autolinking functionality should now work, without manually adding the files to the Xcode project.

what about android, cuz i am getting the same problem... 😢

**Comment by kostiantyn-solianyk** [comment]
same issue on android

**Comment by fvilar** [comment]
same issue on android...

**Comment by ObedAmpah** [comment]
I also have the same issue on Android

**Comment by rochapablo** [comment]
Any update on this?

**Comment by YousefAlsbaihi** [comment]
i'm not usre if this is still usefull but 
i installed the library again 

1. run this command to unlink if it's linked, remember react native auto-linking is working fine 
`npx react-native unlink react-native-admob`
2. remove the library from the project 
`npm unlink react-native-admob -S`
3. run pod install 
`npx pod-install` OR `cd ios && pod install`
4. install the library again 
`npm i react-native-admob -S` OR `yarn react-native-admob`
5. after installation complete, open ios/Podfile file and add the following 
` pod 'Google-Mobile-Ads-SDK', '7.69.0' `
6. run pod install


that should solve it.

**Comment by sahilwise** [comment]
Any update on this, I am facing the same problem.
