### ISSUE TITLE
 No podspec file was found

### ISSUE THREAD

**Issue by lotosbin** [sbugert/react-native-admob#462]
[!] use_native_modules! skipped the react-native dependency 'react-native-admob'. No podspec file was found.
    - Check to see if there is an updated version that contains the necessary podspec file
    - Contact the library maintainers or send them a PR to add a podspec. The react-native-webview podspec is a good example of a package.json driven
    podspec. See https://github.com/react-native-community/react-native-webview/blob/master/react-native-webview.podspec
    - If necessary, you can disable autolinking for the dependency and link it manually. See
    https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#how-can-i-disable-autolinking-for-unsupported-library

**Comment by lotosbin** [comment]
"react-native-admob": "^2.0.0-beta.5",

**Comment by lotosbin** [comment]
"react-native": "0.60.4",

**Comment by ttawan** [comment]
I have same issue!

**Comment by koenpunt** [comment]
I've opened a PR to bring this library up to date with the latest version of React Native, and thus bringing support for CocoaPods: #472

**Comment by koenpunt** [comment]
The latest beta (`v2.0.0-beta.6`) includes a `podspec` file, and should work with autolinking.
