### ISSUE TITLE
RN 0.60+

### ISSUE THREAD

**Issue by talaikis** [sbugert/react-native-admob#465]
Made several adjustments to this library and released it on npm: https://www.npmjs.com/package/@talaikis/react-native-admob

Interstitial works almost fine (except with "ad already did show" warning) on Android, nothing else tested.

**Comment by koenpunt** [comment]
I've opened a PR to bring this library up to date with the latest version of React Native, and thus bringing support React Native 0.60+, CocoaPods and Android X: #472

**Comment by koenpunt** [comment]
The latest beta (`v2.0.0-beta.6`) includes a `podspec` file, and should work with autolinking.
