### ISSUE TITLE
Internal error, an invalid response was received from the ad server.

### ISSUE THREAD

**Issue by AsocialCoder** [sbugert/react-native-admob#466]
This code working fine with test ads unit ID. However, When I use my setAdUnitID return this error; **Internal error, an invalid response was received from the ad server.**

How can i fix this error?

```
           AdMobInterstitial.setAdUnitID('ca-app-pub-xxxxx/xxxx');
           AdMobInterstitial.setTestDevices([AdMobInterstitial.simulatorId]);
           AdMobInterstitial.requestAd().then(() => AdMobInterstitial.showAd().then(()=>{
                    this.props.navigation.goBack();
           })).catch((err)=>{                    
                    console.log(err);
                    this.props.navigation.goBack();
           });
```

**Comment by Rob2k9** [comment]
Hi try using the google test adunit id if this works its your google admob account sometimes this happens if you have just created your account or if you have not added your payment information into admob

**Comment by koenpunt** [comment]
If it's working with test unit ids, but not with your own, you probably have to wait a bit longer before those become active, and otherwise you might have to change something in your inventory settings in AdMob.
