### ISSUE TITLE
ERROR_CODE_INTERNAL_ERROR

### ISSUE THREAD

**Issue by xvlm** [sbugert/react-native-admob#47]
Hi @sbugert

I am using RN v0.31 ， Android Genymotion

<AdMobBanner
          bannerSize={this.state.bannerSize}
          testDeviceID="EMULATOR"
          adViewDidReceiveAd={this.didReceiveAd}
          didFailToReceiveAdWithError={this.bannerError}
          adUnitID="ca-app-pub-3940256099942544/2934735716"
          />
Ads are appearing when adUnitID="ca-app-pub-3940256099942544/2934735716" 。

I changed adUnitID to "ca-app-pub-3940256099942544/1033173712" then No Ads are appearing。

Console log say “ERROR_CODE_INTERNAL_ERROR”。

**Comment by sbugert** [comment]
Why did you change it in the first place?
The test ad unit id `ca-app-pub-3940256099942544/1033173712` is only for interstitial ads.

Reopen the issue if I misunderstood the problem.

**Comment by pmadruga** [comment]
Having the same issue. 

I have two different unitID's - one for iOS and one for Android.  The iOS (first to be implemented) works and the Android doesn't. It is not an interstitial ad.

**Comment by jsoutherner** [comment]
I aslo have this error when changing ca-app-pub for my own (VideoReward). With testing or even prod interstitial ca-app-pub the ad is showing

**Comment by hiepnm** [comment]
Having the same issue.

**Comment by chen1026241686** [comment]
Having the same issue,has anyone solved this problem?

**Comment by chen1026241686** [comment]
I changed ad id,then it works.maybe you can change your ad id,
https://developers.google.com/admob/android/test-ads
