### ISSUE TITLE
Admob - Native module cannot be null (iOS)

### ISSUE THREAD

**Issue by shairamiri** [sbugert/react-native-admob#471]
Followed installation steps from react-native-admob. Works fine for android but iOS keeps giving same error.

![Simulator Screen Shot - iPhone X - 2019-09-14 at 20 59 09](https://user-images.githubusercontent.com/46130629/64912639-8323aa00-d732-11e9-9fd4-b596e6cf6974.png)

Package.json

{
  "name": "addinghelp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.6.1",
    "@react-native-community/push-notification-ios": "^1.0.2",
    "@react-native-community/slider": "^2.0.0",
    "react": "16.8.6",
    "react-native": "0.60.5",
    "react-native-admob": "^2.0.0-beta.5", 
    "react-native-fbsdk": "^1.0.3",
    "react-native-gesture-handler": "^1.4.1",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-maps": "^0.25.0",
    "react-native-push-notification": "^3.1.9",
    "react-native-reanimated": "^1.2.0",
    "react-native-vector-icons": "^6.6.0",
    "react-navigation": "^4.0.4",
    "react-navigation-drawer": "^2.2.1",
    "react-navigation-stack": "^1.7.3",
    "react-navigation-tabs": "^2.5.2"
  },
  "devDependencies": {
    "@babel/core": "7.6.0",
    "@babel/runtime": "7.6.0",
    "@react-native-community/eslint-config": "0.0.3",
    "babel-jest": "24.9.0",
    "eslint": "6.4.0",
    "jest": "24.9.0",
    "metro-react-native-babel-preset": "0.54.1",
    "react-test-renderer": "16.8.6"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by koenpunt** [comment]
This is because React Native 0.60.x uses CocoaPods by default, which we not yet support. 
I've opened a PR to bring this library up to date with the latest version of React Native, and thus bringing support for CocoaPods and Android X: #472

**Comment by JustSevi4** [comment]
@koenpunt Hello! When your PR will be merged?

**Comment by koenpunt** [comment]
It is now, and is released as `v2.0.0-beta.6`

**Comment by alexandrejeanjean** [comment]
Hello,

I have tried the latest release v2.0.0-beta.6 and unfortunately encountered the same issue...

Anyone else has the same issue again ?

Thanks

**Comment by alexandrejeanjean** [comment]
After researching, i've found that this solutions works for me: 
[https://github.com/sbugert/react-native-admob/issues/460](url)
