### ISSUE TITLE
sbugert 

### ISSUE THREAD

**Issue by magicvn** [sbugert/react-native-admob#5]
Hi sbugert ,

I build for android version with RN 2.0 and got a Warning while debug in google chrome:

**Warning: Native component for "RNAdMob" does not exist**

And banner did not show up

Regards,

**Comment by sbugert** [comment]
What is RN 2.0? Do you mean 0.20.0?

I cannot reproduce the problem, it works for me.
Does the banner show up if you don't enable debug mode?

**Comment by magicvn** [comment]
Hi sbugert,

Thank for your reply,

I meant  React Native 0.20.0

I try reinstall new project and it's work perfectly, I will try to fix in old project

Best Regards.
