### ISSUE TITLE
inserting mediumRectangle every nth of a list

### ISSUE THREAD

**Issue by andyfenelon** [sbugert/react-native-admob#50]
i'm trying to achieve something like this where every nth will be an advert, theres an article https://www.sitepoint.com/monetizing-apps-with-the-google-admob-sdk/  (in java) thats pretty close to what i'm trying to do. 

if i'm using 
```
<AdRectangle
  bannerSize="mediumRectangle"
  adUnitID="xxxxx"
  testDeviceID="EMULATOR"
/>
```
will i need to use a different  unique adUnitID for each advert ? or should you use on single adUnitID for the app across multiple instances ?

![alt text](https://dab1nmslvvntp.cloudfront.net/wp-content/uploads/2016/09/1472839599nativeAd.png "Logo Title Text 1")

**Comment by andyfenelon** [comment]
close, found answer.

**Comment by paddy57** [comment]
can you explain how did you achieve that ?
