### ISSUE TITLE
Ads Not Showing in Signed App

### ISSUE THREAD

**Issue by Sanan4li** [sbugert/react-native-admob#507]
I know this issue is not related to the package but if anyone has faced similar issue then please help.
I am using react-native-admob to display admob ads in my react native app. Everything was working fine. Ads were loading in debug app as well as in release apk. Now, I want to publish app in playstore and for that I need signed apk. I used steps described in react-native docs to generate signed apk. Now, I have separate apk files for each architecture and a universal apk for all architectures but ads are not showing in signed apk. I don't know the reason. Kindly help please.

**Comment by MigueVeliz** [comment]
Any update? im facing the same issue. Please let me know if you solved this. Thanks

**Comment by Sanan4li** [comment]
> Any update? im facing the same issue. Please let me know if you solved this. Thanks

Did your ads work in debug or unsigned apk? I can help you if your ads doesn't appear in signed app but worked in debug app.

**Comment by MigueVeliz** [comment]
Yes, everything worked in debug,  but when I generated a signed apk(ready to submit to the play store) no ads are showing.

**Comment by Sanan4li** [comment]
As android operating system is also from google and they don't allow users to install apps that are not scanned by their antivirus. When you have an unsigned apk you can install it by enabling settings "install apps from unknown resources" but when you have signed apk it has to be scanned by google in order to display ads. According to google

Google scans millions of apps every day to ensure they’re safe for users. If you have been asked to submit your APK, or if you have a problem serving Google ads in your Android application, please complete the form below.

So you have to either submit signed apk if you want to display ads on this link https://support.google.com/admob/contact/android_APK_submission?hl=en or you can check the box appears when you install a signed app saying "Send This App to google for Scanning" Google will start serving ads in your signed apk.

**Comment by pujanov69** [comment]
So, do I need to first publish the app to playstore and wait to see if the add appears?

**Comment by Sanan4li** [comment]
> So, do I need to first publish the app to playstore and wait to see if the add appears?

Did your ad worked in the debug version? If they worked... see my above answer.

**Comment by pujanov69** [comment]
yes.....and it is working even in the unsigned apk........the problem arises only in the signed apk.

**Comment by Sanan4li** [comment]
> yes.....and it is working even in the unsigned apk........the problem arises only in the signed apk.

Please check my above answer.. either you have to submit your app to google on the given link or you can use the 2nd method.. or you can also upload it to playstore they will scan automatically.
This is because google make sure that your app is scanned by their systems before you display ads.

**Comment by iamamanprajapati** [comment]
same issue

**Comment by Sanan4li** [comment]
> same issue
Check this comment

https://github.com/sbugert/react-native-admob/issues/507#issuecomment-597298909

**Comment by MuhammadShaheer97** [comment]
same issue, does not show in production for IOS from apple store. but does for android and does in debug mode

**Comment by iamamanprajapati** [comment]
@MuhammadShaheer97  This issue is present only when your app in development but when you upload your app on the play store or app store then automatically your ads will showing.
