### ISSUE TITLE
rnpm link issue

### ISSUE THREAD

**Issue by RatFou** [sbugert/react-native-admob#54]
Hi,

AdMob component was working well but after I did a "rnpm link" for another component, RNAdMob had an issue when I assembled the release.

I removed all "react-native-admob" values in gradle files and error disappears.

I hope it will help.

**Comment by sbugert** [comment]
Hi RatFou,
Sorry for the late response!

This seems related to #45. I most likely need to add some configuration so rnpm knows the right values for gradle.

Thanks for reporting!

**Comment by koenpunt** [comment]
I believe this is no longer an issue with v2. If still the case, please open a new issue.
