### ISSUE TITLE
use of undeclared identifier 'GADMobileAds' iOS

### ISSUE THREAD

**Issue by Miyaguisan** [sbugert/react-native-admob#545]
Hi,

I have followed all the steps and set up everything and the app works just fine.
The problem comes when I want to ARCHIVE for distribution. The following error shows up:

`Use of undeclared identifier 'GADMobileAds'`

Again... compiling and running the app works fine, but I just can't archive for distribution.
¿What's up with that?

**Comment by tforbus** [comment]
@Miyaguisan Did you figure out how to resolve this? I'm seeing this same error.

**Comment by tforbus** [comment]
I managed to get this working by moving "@import GoogleMobileAds;" into AppDelegate.h, if anyone else stumbles across this through Google as I did.
