### ISSUE TITLE
iOS cant archive but compile & run fine

### ISSUE THREAD

**Issue by Miyaguisan** [sbugert/react-native-admob#546]
Hi,

I have followed all the steps and set up everything and the app works just fine.
The problem comes when I want to ARCHIVE for distribution. The following error shows up:

`Use of undeclared identifier 'GADMobileAds'`

Again... compiling and running the app works fine [both simulator and device, perfect, no problems], but I just can't archive for distribution.
¿What's up with that?

**Comment by murtuzamacdev** [comment]
I am facing the same issue. How did you fix this?
