### ISSUE TITLE
Test Device ID is not working properly in Banner.

### ISSUE THREAD

**Issue by shukerullah** [sbugert/react-native-admob#59]
I am using Ads with my test device id. Sometimes Banner load real ads, but Interstitial all the time showing dummy ads. Something is wrong with Banner.

**Comment by Kris4an7** [comment]
I have the same problem. Banner ads rarely show for me.

**Comment by koenpunt** [comment]
In v2 (available as beta) a lot has been refactored, so I'm pretty sure this issue is now obsolete. Might that not be the case then please open a new issue.
