### ISSUE TITLE
IOS Failed building

### ISSUE THREAD

**Issue by theobouwman** [sbugert/react-native-admob#60]
got this error for ios

```ld: symbol(s) not found for architecture x86_64 
clang: error: linker command failed with exit code 1 (use -v to see invocation)```

Linked everything and added project to xcode

Android is working fine

**Comment by BigPun86** [comment]
+1

**Comment by Dielz98** [comment]
same here +1

**Comment by tony-kaplan** [comment]
try remove the test project?

**Comment by kevineaton** [comment]
I initialized a new react-native app and installed just this library. I ran react-native link as well.  Running on Android worked perfectly. When i ran it on iOS, I received the following error:

In file included from /Users/.../node_modules/react-native-admob/ios/RNAdMobManager.m:2:
/Users/.../node_modules/react-native-admob/ios/BannerView.h:2:9: fatal error: module 'GoogleMobileAds' not found
@import GoogleMobileAds;

**Comment by lamptt** [comment]
Try reinstall [Firebase/Messaging](https://firebase.google.com/docs/ios/setup#frameworks)
if you use CocoaPods, add Firebase/Messaging in pod file and run "pod update"
if not, place GoogleMobileAds.framework from https://developers.google.com/admob/ios/download in ios folder

**Comment by alvaromb** [comment]
Closing. Feel free to ping me if you feel this should be reopened.

**Comment by edencakir** [comment]
@alvaromb I'm facing the same issue that @kevineaton faced before.

**Comment by alvaromb** [comment]
Install Google AdMob SDK. 

Enviado desde mi iPhone

**Comment by jeodiong** [comment]
@theobouwman Use the xcworkspace to build instead of the xcproject?

**Comment by NickAlvesX** [comment]
@jeodiong This solved it to me! Thanks.

**Comment by phillmill** [comment]
@NickAlvesX how did you add the xcworkspace file? The Mac Finder just opens xcode when you try to expand the RNAdMobManager.xcodeproj folder to get to project.xcworkspace
