### ISSUE TITLE
onSizeChange not called

### ISSUE THREAD

**Issue by rhysowen** [sbugert/react-native-admob#63]
React `0.38`. iOS `10.`

`onSizeChange` does not get called. For now, I'm having to explicitly pass through the banner height & width through the `style` props.

**Comment by koenpunt** [comment]
Fixed in version 2, which is currently in beta (v2.0.0-beta.2). See the README on how to install this version, and check [the release notes](https://github.com/sbugert/react-native-admob/releases/tag/v2.0.0-beta.1) to see what changed.
