### ISSUE TITLE
Requesting Interstitial Ad on iOS gives error

### ISSUE THREAD

**Issue by MohsinTariq10** [sbugert/react-native-admob#65]
When i request interstitial Ad i get this error 

`ExceptionsManager.js:71 Argument 0 (RCTResponseSenderBlock) of RNAdMobInterstitial. must not be nullreactConsoleErrorHandler @ ExceptionsManager.js:71console.error @ YellowBox.js:61logIfNoNativeHook @ RCTLog.js:38__callFunction @ MessageQueue.js:236(anonymous function) @ MessageQueue.js:108guard @ MessageQueue.js:46callFunctionReturnFlushedQueue @ MessageQueue.js:107(anonymous function) @ debuggerWorker.js:71
`
`ExceptionsManager.js:71 Argument 0 (<null>) of RNAdMobInterstitial. could not be processed. Aborting method call.reactConsoleErrorHandler @ ExceptionsManager.js:71console.error @ YellowBox.js:61logIfNoNativeHook @ RCTLog.js:38__callFunction @ MessageQueue.js:236(anonymous function) @ MessageQueue.js:108guard @ MessageQueue.js:46callFunctionReturnFlushedQueue @ MessageQueue.js:107(anonymous function) @ debuggerWorker.js:71`

Can anyone help ?

**Comment by MohsinTariq10** [comment]
Banner Ads are working fine

**Comment by MohsinTariq10** [comment]
Using the code inside the examples folder solved the issue but i could not find out why this did happen.

**Comment by ademgcl** [comment]
same problem here. banners working fine. interstitial ad on android also working. but on ios it throws the error mentioned

**Comment by ademgcl** [comment]
now seen that banners also are not clickable on ios. everything seems to be working fine on android though. 
versions:  "react": "15.4.1",  "react-native": "0.39.2",  "react-native-admob": "^1.1.5"

**Comment by wasedaigo** [comment]
The usage in ReadMe is wrong. requestAd and showAd require function to be passed. Calling as follows work as expected.
```
          AdMobInterstitial.requestAd(error => {
            AdMobInterstitial.showAd((error) => {});
          });
```

**Comment by a3diti** [comment]
sometimes there is no error but still the interstitial didn't show, in my case it happened when i was showing an `Alert` in the same time, it seems you can't show an interstitial `simultaneously` with another `Alert` window, this kind of error doesn't show up on the console of XCode
Remove any alert window when showing interstitial.
