### ISSUE TITLE
Package does not work with react native 38 

### ISSUE THREAD

**Issue by bendellarocco** [sbugert/react-native-admob#67]
I have used this package since react native 20 or so.  I recently went from react native 37 to 38 and ads are no longer served.  I downgraded back to 37 and this issue was resolved.

**Comment by emrecanozkok** [comment]
still im tried for android first time and its not worked.

**Comment by mp31415** [comment]
Worked for me with banners (RN 0.39, Android 6.0.1, on device). I did modify MainActivity to initialize the SDK:
    
	import com.google.android.gms.ads.MobileAds;

	public class MainActivity extends ReactActivity {

		...
		
		@Override
		public void onCreate(Bundle savedInstanceState) {
			super.onCreate(savedInstanceState);
			MobileAds.initialize(getApplicationContext(), "ca-app-pub-your-app-id");
		}  	
	}

**Comment by fahr23** [comment]
i have just tried RN 0.30 0.35 and 0.39 . but after added the package (Example android code used)
my app closed unexpectedly... is there someone recently used package?

**Comment by emrecanozkok** [comment]
interstial ads working but banner not work.i will try @mp31415 idea

**Comment by fahr23** [comment]
i  tried @mp31415  idea but i couldn't succeeded.. i will try only interstitial  to see the result. thx...

**Comment by avishayil** [comment]
Same here, not working with 0.38 or 0.39, only with 0.37.

**Comment by Saurer** [comment]
got it working on Android using RN 0.39.2. I've modified MainApplication.java to add the required dependency:
`
import com.sbugert.rnadmob.RNAdMobPackage;

public class MainApplication extends Application implements ReactApplication {
	...
    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
	  new RNAdMobPackage(),
      );
    }
}
`

**Comment by danyleo** [comment]
IOS: Same issue, on 0.37 the package works fine but when i switch to 0.39 it stop working.

![screen shot 2017-01-05 at 3 26 05 pm](https://cloud.githubusercontent.com/assets/24935151/21677795/8286c68a-d35d-11e6-81b3-dd210d6c1576.png)

**Comment by meznaric** [comment]
@danyleo You can fork the library and mitigate breaking changes yourself, until author has the time to fix it. https://github.com/facebook/react-native/wiki/Breaking-Changes#namespace-all-header-imports-to-react-e1577d---javache

**Comment by dkolba** [comment]
@meznaric PR welcome 👍

**Comment by alvaromb** [comment]
Closed by #95
