### ISSUE TITLE
setup instructions 

### ISSUE THREAD

**Issue by arpecop** [sbugert/react-native-admob#69]
MainActivity.java

On top, where imports are:

```
import com.sbugert.rnadmob.RNAdMobPackage;
Under protected List<ReactPackage> getPackages() {:

  return Arrays.<ReactPackage>asList(
    new MainReactPackage(),
    new RNAdMobPackage()
  );

```
There is no similar block in MainActivity.java

**Comment by MayasHaddad** [comment]
@arpecop it's a mistake in README. 
As you can see in the [example](https://github.com/sbugert/react-native-admob/blob/master/Example/android/app/src/main/java/com/example/MainApplication.java#L25), it's to MyApplication.java that you'll add the code.
