### ISSUE TITLE
Slows down App extremely on Android

### ISSUE THREAD

**Issue by BigPun86** [sbugert/react-native-admob#7]
On Android my App slows down extremely like mentioned in the title. I just tried it on emluator until now and it is worse. I will try it later on real device. 

![screen shot 2016-02-29 at 17 30 16](https://cloud.githubusercontent.com/assets/7880624/13400891/2b220bea-df0a-11e5-8942-79f27fc4582f.png)

Any ideas how to solve this or anybody who has same issue?

**Comment by sbugert** [comment]
I've been seeing this as well when running on emulator but had no issues on real devices. Can you report back after trying? Also, turning off the dev mode can work wonders.

I'm quite busy right now but mid march I will start working on this lib again.
Maybe some profiling will clear things up!

**Comment by BigPun86** [comment]
Okay you were right. On device it works perfectly, without any bad side effects. Turning off the dev mode didn´t help me on the emulator.. Thanks though

**Comment by sbugert** [comment]
You're welcome.
I'm closing this for now. But please post again if it turns out to be a problem after all!

**Comment by paddy57** [comment]
i'm showing ad's in each flat list component, which is making my scrolling of flat list very laggy , even in production mode(release mode). Any suggestions ?
