### ISSUE TITLE
Frequency cap being ignored?

### ISSUE THREAD

**Issue by booboothefool** [sbugert/react-native-admob#73]
On my AdMob settings I have a frequency cap set, but I can get an interstitial every time `AdMobInterstitial.requestAd(error => AdMobInterstitial.showAd())`  is called. Shouldn't they be obeying frequency cap?

**Comment by booboothefool** [comment]
The solution was to:

```
    AdMobInterstitial.setTestDeviceID('EMULATOR');
    AdMobInterstitial.setAdUnitID('ca-app-pub-...');
```

Set that ad unit ID ONCE in the app.

**Comment by booboothefool** [comment]
Nevermind... I'm still getting too many interstitials. Anyone have an idea?

**Comment by akiradeveloper** [comment]
@booboothefool You closed this issue and I wonder if you solved this?
