### ISSUE TITLE
AdMobBanner can't click in ios

### ISSUE THREAD

**Issue by lamptt** [sbugert/react-native-admob#75]
I using react-native 0.39.2, react-native-admob ^1.1.5 and my code:

import React from 'react';
import {
    Platform
} from "react-native";
import {AdMobBanner} from 'react-native-admob';
export default class extends React.Component {
    render() {
        if ((Platform.OS === 'ios'))
            return (
                <AdMobBanner style={{height: 50}}
                             adUnitID="your-admob-unit-id-ios"
                             testDeviceID="EMULATOR"/>
            );
        else return (
            <AdMobBanner adUnitID="your-admob-unit-id-android"
                         testDeviceID="EMULATOR"/>
        );
    }
}

But just Android can click in AdMobBanner, IOS can't.

**Comment by vnil** [comment]
I have the same problem, ads not possible to press :/
