### ISSUE TITLE
Always error on AdMobBanner component Android

### ISSUE THREAD

**Issue by cinder92** [sbugert/react-native-admob#76]
Hello im using this plugin to inset an AdMobBanner, i always receive an error `'ERROR_CODE_INTERNAL_ERROR'`

here is my code

```
<AdMobBanner
						  bannerSize="fullBanner"
						  adUnitID="ca-app-pub-6784349169230833/9147926709"
						  testDeviceID="EMULATOR"
						  didFailToReceiveAdWithError={(err) => {
							  //no internet
							  alert(err)
							  console.log(err);
						  }} />
```

**Comment by kelvinpompey** [comment]
I am also encountering this problem.

**Comment by creativefull** [comment]
:+1: i also got error like this

**Comment by croshim** [comment]
Any news?

**Comment by creativefull** [comment]
maybe your device have not google service, i already fix to install google service in my device

**Comment by vseprav** [comment]
Have the same issue

**Comment by booboothefool** [comment]
My Android banners were working fine.. but as of yesterday I'm getting no more ads. Still showing up on iOS though. Any ideas?

**Comment by ayberkanilatsiz** [comment]
My banner working fine on iOS but android have same issue.

**Comment by vseprav** [comment]
My problem was in configuration firebase account , not in code

**Comment by franciscocpg** [comment]
@vseprav 
Could you share your solution please?

**Comment by trungbbvitalify** [comment]
i got the same issue  but  it can be displayed on android when i change ad id to test id

**Comment by vseprav** [comment]
@franciscocpg 
I have added google-services.json to project_root/android/app/ and project_root/android folder, it helps me

**Comment by trungbbvitalify** [comment]
@ayberkanilatsiz my app also is the same on IOS it works fine ,did you resolve it ?

**Comment by ayberkanilatsiz** [comment]
@trungbbvitalify No i am not resolve yet.

**Comment by trungbbvitalify** [comment]
I resolved it .just change android package name to other one .

**Comment by creativefull** [comment]
maybe your provider internet block admob, i already try when i'm using Wifi ads not show, but when i'm using sim card internet, it's work
