### ISSUE TITLE
React Native 0.40 Compatibility

### ISSUE THREAD

**Issue by edencakir** [sbugert/react-native-admob#77]
Is this repo supporting version 0.40?

**Comment by lucianomlima** [comment]
Not yet. But I send a PR that fix this. Wait for merge #78.

**Comment by fcpauldiaz** [comment]
What else is needed to support version 0.40?

**Comment by YoonJaePark** [comment]
Have you solved this problem? not supprot RN 0.4>= Version?

**Comment by edencakir** [comment]
It looks like @lucianomlima solved the iOS part, so we're left with Android. Anyone can make this happen?

**Comment by fcpauldiaz** [comment]
I installed manually this on RN 0.40 and it worked with Android, I just changed the location of the interterstial id.

**Comment by lucianomlima** [comment]
@fcpauldiaz Location of interstitial on iOS or Android too?

**Comment by edencakir** [comment]
@fcpauldiaz @lucianomlima since sbugert seems inactive, can one of you test a working version of 0.40 and fork it? Others and future users can benefit from your work, since there seems to be no other admob repo.

**Comment by fcpauldiaz** [comment]
@lucianomlima only on Android, I haven't tested it on iOS. @edencakir I can do an example over the weekend. If someone needs an example right now, you can check my [app repo](https://github.com/Newton-Labs/ChapiMoneda) just be careful with the production ads.

**Comment by lucianomlima** [comment]
@fcpauldiaz you can send me the code you change?
Maybe I try to update my pull request to fix compatibility for Android too.

**Comment by fcpauldiaz** [comment]
I based all my code from the Example from this repo. The lines that I actually changed are [this](https://github.com/Newton-Labs/ChapiMoneda/blob/master/src/components/app.js#L20-L21), [this](https://github.com/Newton-Labs/ChapiMoneda/blob/master/android/settings.gradle#L8-L9),  [this](https://github.com/Newton-Labs/ChapiMoneda/blob/master/android/app/build.gradle#L140), [this](https://github.com/Newton-Labs/ChapiMoneda/blob/master/android/app/src/main/java/com/chapimoneda/MainApplication.java#L36-L37) and [this](https://github.com/Newton-Labs/ChapiMoneda/blob/master/android/app/src/main/java/com/chapimoneda/MainApplication.java#L10).

And of course the [versions](https://github.com/Newton-Labs/ChapiMoneda/blob/master/package.json#L11-L13) of RN.

**Comment by lucianomlima** [comment]
@fcpauldiaz thanks, I've seen your code and apparently the interstitial issue is not directly related to the RN 0.40+ version.
So, maybe Android platform don't need adjusts for RN 0.40+.

**Comment by fcpauldiaz** [comment]
That's great! So you can make a release now

**Comment by lucianomlima** [comment]
Here in this repo I can't, cause I'm not collaborator.

**Comment by YoonJaePark** [comment]
i just typed commands. 
version 
  "dependencies": {
    "react": "15.4.2",
    "react-native": "0.41.2",
    "react-native-admob": "^1.1.5"
  },

npm i react-native-admob -S
react-native link

pod install
target 'admob' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/AdMob'
  # Pods for admob

  # target 'admob-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  target 'admobTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

Build fali since then. How do you solution with it?

![image](https://cloud.githubusercontent.com/assets/6939460/22679092/e5136e12-ed42-11e6-8c41-236ccebe3685.png)

**Comment by edencakir** [comment]
Do you have a working fork? @lucianomlima

**Comment by lucianomlima** [comment]
@YoonJaePark see #78 or use RN 0.39

**Comment by lucianomlima** [comment]
@edencakir my fork only have a branch with the changes I do in PR #78 
Here I'm still using RN 0.39

**Comment by alvaromb** [comment]
Closed by #95

**Comment by alvaromb** [comment]
Published https://github.com/sbugert/react-native-admob/releases/tag/v1.2.0

Please feel free to ping me if anything is wrong.
