### ISSUE TITLE
Ad lifecycle event callback functions not working for AdMobBanner

### ISSUE THREAD

**Issue by Satya5614** [sbugert/react-native-admob#82]
I am trying to log the information when Ad is received. The ad is displayed on the ios emulator perfectly, but nothing is logged. I have tried all the event callback functions, but none of them is working. Here is my code

```
<AdMobBanner
    adUnitID={AdUnitId}
    testDeviceID="EMULATOR"
    adViewDidReceiveAd={() => {console.log("Ad received");}}
    didFailToReceiveAdWithError={(err) => {console.log(err);}} />
```

Even setting wrong adUnitId intentionally does not trigger `didFailToReceiveAdWithError` callback

**Comment by ndbroadbent** [comment]
This is fixed by #66
