### ISSUE TITLE
Doesn't work avec ReactNative 0.41

### ISSUE THREAD

**Issue by yolosaucisson** [sbugert/react-native-admob#83]
Hi,

I tried this react native module but it doesn't work with react native 0.41.
How can I do?

Sincerely,

**Comment by lucianomlima** [comment]
This package is not compatible for RN 0.40+. see #78 
Use RN 0.39

**Comment by yolosaucisson** [comment]
Will you upgrade it as soon as possible?

**Comment by yolosaucisson** [comment]
Will you upgrade it as soon as possible?

**Comment by lucianomlima** [comment]
Anyone that have one PR merged, become a contributor.
But to merge PR needs to be a collaborator.

**Comment by alvaromb** [comment]
Published https://github.com/sbugert/react-native-admob/releases/tag/v1.2.0

Please feel free to ping me if anything is wrong.
