### ISSUE TITLE
Unable to compile for IOS

### ISSUE THREAD

**Issue by kanekotic** [sbugert/react-native-admob#84]
I was adding the package to my application and is complaining actually of values are redefinitions. This happens after adding the admodFramework. Tried both routes direct import and cocoapod.
![screen shot 2017-02-07 at 17 43 42](https://cloud.githubusercontent.com/assets/3071208/22716787/0a99bb36-ed5d-11e6-9dd6-d895fd0c5b7d.png)
I am using react-native 0.40

**Comment by lucianomlima** [comment]
This package is not compatible for RN 0.40+. see #78 
Use RN 0.39

**Comment by kanekotic** [comment]
any timeline to merge PR #78 ? I have already a bunch of other things working on RN 0.40, so at this point downgrade does not seem something possible for me.

**Comment by lucianomlima** [comment]
Anyone that have one PR merged, become a contributor.
But to merge PR needs to be a collaborator.

**Comment by kanekotic** [comment]
ok so in that case i might become your beta tester and reference directly your branch. 😛

**Comment by alvaromb** [comment]
Closing by #95

**Comment by alvaromb** [comment]
Published https://github.com/sbugert/react-native-admob/releases/tag/v1.2.0

Please feel free to ping me if anything is wrong.
