### ISSUE TITLE
encounter 'undefined is not a function' error while running example app 

### ISSUE THREAD

**Issue by waterstar** [sbugert/react-native-admob#85]
Running the example app on Android simulator and got following error:

<img width="426" alt="screen shot 2017-02-08 at 2 02 22 pm" src="https://cloud.githubusercontent.com/assets/8625997/22725306/9766a966-ee07-11e6-8b8a-07a265b5ea16.png">

**Comment by ibrahimcanbaz** [comment]
try to add it manually, not with `react-native link`

**Comment by fcpauldiaz** [comment]
I had the same error and I had to manually link it

**Comment by koenpunt** [comment]
From the looks of the error message this has nothing to do with the library itself. And a lot of updates of RN have passed in the meantime, so I'm going to close this issue.
If you still encounter problems, feel free to open a new issue.
