### ISSUE TITLE
Why does this lib seem to completely ignore the dashboard settings? Bad ads, etc.

### ISSUE THREAD

**Issue by booboothefool** [sbugert/react-native-admob#87]
I get terrible ads. Things like Black Netflix and really disgusting Dating ads. I turned them off in the dashboard, but they still happen.

Also, it ignores the frequency cap I set on interstitials. So the user basically gets spammed with them. 

Any idea what's wrong?

**Comment by ndbroadbent** [comment]
Hi @booboothefool, I don't know if this is a problem with the library. If you are using the correct `adUnitID`, then all the ads are just being served from the AdMod servers. Maybe it just takes a while to update when you make a change on the dashboard.

**Comment by booboothefool** [comment]
Hey @ndbroadbent. You're totally right. I created a new `adUnitID` where I blocked the bad ads, and forgot to update my config to use it.
