### ISSUE TITLE
Ad requests failing? AdMob seems to always win over other ad networks, any sort of floor cap fails, etc. 

### ISSUE THREAD

**Issue by booboothefool** [sbugert/react-native-admob#92]
<img width="1122" alt="screen shot 2017-02-20 at 12 41 11 pm" src="https://cloud.githubusercontent.com/assets/13257645/23136932/35ba388a-f76d-11e6-8988-72dad065c63c.png">

^ This seems really weird to me. Why do so many requests fail?

Also, setting any kind of eCPM floor cap, even something really low like $0.40, seems to blank all of my ads (blank spots all over my app cause it can't get an ad).

So confused.

**Comment by booboothefool** [comment]
Needed to add the SDKs and mediation adapters

**Comment by tarouboy** [comment]
@booboothefool did you able to finish the setup? It happens to me as well, all requests couldn't return ad impressions.

**Comment by tanguydlv** [comment]
Hi @booboothefool ! Did you finally find a solution? I have the same issue...
