### ISSUE TITLE
Building errors (Redefinition, Duplicate, Property has a previous declaration)

### ISSUE THREAD

**Issue by gsdias** [sbugert/react-native-admob#93]
I'm trying to use this module but I'm getting those errors on build.

![image](https://cloud.githubusercontent.com/assets/1720784/23161799/e6f602d2-f844-11e6-9762-299865888b06.png)

I tried to install Google-Mobile-Ads-SDK with pod and that created a separate project. I don't know if that is the issue.

**Comment by ayberkanilatsiz** [comment]
@gsdias i've same issue too. Do you solve this?

**Comment by gsdias** [comment]
@ayberkanilatsiz still waiting on help from anyone. My guess is I'm doing the import of frameworks in a wrong way.

**Comment by pankaj-ag** [comment]
I am also facing this issue.

**Comment by gsdias** [comment]
@ayberkanilatsiz @pankaj-ag if you use RN v39 it will work. Its not compatible with most recent RN versions

**Comment by alvaromb** [comment]
Published https://github.com/sbugert/react-native-admob/releases/tag/v1.2.0

Please feel free to ping me if anything is wrong.

**Comment by gsdias** [comment]
@alvaromb after upgrading, clean and build again I got this issue
![image](https://cloud.githubusercontent.com/assets/1720784/23311322/211d198c-facf-11e6-9a97-c93e747b3243.png)

**Comment by alvaromb** [comment]
This means you don't have Google's AdMob SDK configured properly. Check out the SDK installation instruction, specially the rewarded ad section.

**Comment by gsdias** [comment]
ok I will but if I comment that to build I got in console when open app the following:
Feb 24 20:28:19 DUB0024-2 BabyTrack[38736]: Warning: Native component for "RNAdMob" does not exist
Feb 24 20:28:19 DUB0024-2 BabyTrack[38736]: Warning: Native component for "RNAdMobDFP" does not exist

**Comment by alvaromb** [comment]
Have you linked the lib? I'm testing it with a current project and it's working fine. Which RN version are you running?

**Comment by gsdias** [comment]
I linked with react-native link react-native-admob. the first error is gone after importing again Google framework but still the second warning and a red dot. let me unlink and link back again

**Comment by gsdias** [comment]
"react-native": "0.41.2",
 "react-native-admob": "^1.2.0",

**Comment by gsdias** [comment]
after a restart in the simulator got working, tks
