### ISSUE TITLE
iOS throws 'Argument list too long'

### ISSUE THREAD

**Issue by francocorreasosa** [sbugert/react-native-admob#96]
I'm getting
```
Check dependencies

Argument list too long: recursive header expansion failed at /Users/franco/Dropbox/Projects/climauy/node_modules/react-native-admob/ios/../../../ios/Pods/React/node_modules/source-map/build.
```

I also tried to remove the package to solved but I'm still getting that error. Please help, my project is stuck because of this.

**Comment by Ehesp** [comment]
Also getting this error.

**Comment by UladzimirKuzmin** [comment]
Same for me

**Comment by PHClement** [comment]
When you install the library it says in the documentation that the step 3 is useless, so please remove the created path in the **Header Search Path**.

> Add react-native-admob static library to your Xcode project like explained here. (Step 3 of this guide is not needed)

**Comment by koenpunt** [comment]
Closing since this issue is now pretty old. If the problem still exists, let me know and I will reopen.

**Comment by cinder92** [comment]
same issue here +1

**Comment by muhammetdemirci** [comment]
same issue here 👍

**Comment by RobertPaul01** [comment]
This issue is fixed in the master branch but still needs to be deployed to npm. I've been running this patch on `post-install` to fix it: https://gist.github.com/RobertPaul01/cf82a96023393cb6571740dccd6abf7a

**Comment by azsidhu** [comment]
same issue here
