### ISSUE TITLE
Add support for Targeting

### ISSUE THREAD

**Issue by vseprav** [sbugert/react-native-admob#98]
I know that AdMob provides targeting information to an ad request.
For example:
```
AdRequest request = new AdRequest.Builder()
        .setBirthday(new GregorianCalendar(1985, 1, 1).getTime())
        .build();
```
Is it possible to add support for that functionality?

**Comment by alvaromb** [comment]
Hi @vseprav @booboothefool!

Can you send a PR for this feature? Currently I won't be implementing this soon, but I would gladly review a contribution.

**Comment by koenpunt** [comment]
I made a start with targeting in #166, so let's track it there. If you have any ideas or suggestions leave them over there as comments.
